<?php
$loot = array(
	array( "id" => "40254", "qual" => "4", "name" => "Umhang der abgewendeten Krise" ),
	array( "id" => "40252", "qual" => "4", "name" => "Umhang der verfinsterten Sonne" ),
	array( "id" => "40253", "qual" => "4", "name" => "Schal der alten Maid" ),
	array( "id" => "40251", "qual" => "4", "name" => "Tuch der Leuchtkraft" ),
	array( "id" => "40062", "qual" => "4", "name" => "Verdaute Seidenrobe" ),
	array( "id" => "40060", "qual" => "4", "name" => "Verformte Gliedmaßen" ),
	array( "id" => "39768", "qual" => "4", "name" => "Gugel der Verschiedenen" ),
	array( "id" => "40063", "qual" => "4", "name" => "Mantel der zerrütteten Verwandtschaft" ),
	array( "id" => "39765", "qual" => "4", "name" => "Bindungen des Sünders" ),
	array( "id" => "39761", "qual" => "4", "name" => "Infektiöse Huschergamaschen" ),
	array( "id" => "40061", "qual" => "4", "name" => "Zitternde Tunika" ),
	array( "id" => "39762", "qual" => "4", "name" => "Umwicklung aus zerrissenen Netzen" ),
	array( "id" => "39760", "qual" => "4", "name" => "Helm des lädierten Stolzes" ),
	array( "id" => "39767", "qual" => "4", "name" => "Unverminderte Kampfplatte" ),
	array( "id" => "39764", "qual" => "4", "name" => "Bindungen der bedauernswerten Beute" ),
	array( "id" => "39759", "qual" => "4", "name" => "Stählender Chitingurt" ),
	array( "id" => "40257", "qual" => "4", "name" => "Kodex des Verteidigers" ),
	array( "id" => "40255", "qual" => "4", "name" => "Letzter Fluch" ),
	array( "id" => "40258", "qual" => "4", "name" => "Talisman der Vorsehung" ),
	array( "id" => "40256", "qual" => "4", "name" => "Grimmiger Tribut" ),
	array( "id" => "39766", "qual" => "4", "name" => "Brut der Matriarchin" ),
	array( "id" => "39763", "qual" => "4", "name" => "Gespensterhieb" ),
	array( "id" => "39758", "qual" => "4", "name" => "Der Kieferknochen" ),
);
?>