<?php
$loot = array(
	array( "id" => "45038", "qual" => "5", "name" => "Fragment von Val'anyr" ),
	array( "id" => "46017", "qual" => "5", "name" => "Val'anyr, Hammer der Uralten Könige" ),
	array( "id" => "45253", "qual" => "4", "name" => "Mantel der unschlüssigen Ruhe" ),
	array( "id" => "45258", "qual" => "4", "name" => "Sandalen des hitzigen Temperaments" ),
	array( "id" => "45260", "qual" => "4", "name" => "Stiefel der hastigen Wiederbelebung" ),
	array( "id" => "45259", "qual" => "4", "name" => "Quarzbeschlagener Harnisch" ),
	array( "id" => "45249", "qual" => "4", "name" => "Messinggefütterte Stiefel" ),
	array( "id" => "45251", "qual" => "4", "name" => "Schulterplatten des Dekonstruktors" ),
	array( "id" => "45252", "qual" => "4", "name" => "Handgelenksschützer des Zeitwissenschaftlers" ),
	array( "id" => "45248", "qual" => "4", "name" => "Uhrwerkbeinplatten" ),
	array( "id" => "45250", "qual" => "4", "name" => "Ring des wahnsinnigen Konstrukts" ),
	array( "id" => "45247", "qual" => "4", "name" => "Siegel des Erderschütterers" ),
	array( "id" => "45254", "qual" => "4", "name" => "Siegel des rachsüchtigen Herzens" ),
	array( "id" => "45255", "qual" => "4", "name" => "Totem von Donnerfall" ),
	array( "id" => "45246", "qual" => "4", "name" => "Golemsplitterspieß" ),
	array( "id" => "45256", "qual" => "4", "name" => "Verzerrte Visage" ),
	array( "id" => "45257", "qual" => "4", "name" => "Zauberstab aus Quarzkristall" ),
	array( "id" => "45446", "qual" => "4", "name" => "Griffe der Vernunft" ),
	array( "id" => "45444", "qual" => "4", "name" => "Handschuhe der ruhigen Hand" ),
	array( "id" => "45445", "qual" => "4", "name" => "Brustplatte des Ergebenen" ),
	array( "id" => "45443", "qual" => "4", "name" => "Glücksbringer der akribischen Zeitberechnung" ),
	array( "id" => "45442", "qual" => "4", "name" => "Sorthalis, Hammer der Wächter" ),
);
?>