<?php
$loot = array(
	array( "id" => "40194", "qual" => "4", "name" => "Schneedeckenrobe" ),
	array( "id" => "40602", "qual" => "4", "name" => "Roben der Mutation" ),
	array( "id" => "40198", "qual" => "4", "name" => "Bänder der Unreinheit" ),
	array( "id" => "40197", "qual" => "4", "name" => "Handschuhe des gefallenen Zauberers" ),
	array( "id" => "40186", "qual" => "4", "name" => "Drängende Bänder" ),
	array( "id" => "40200", "qual" => "4", "name" => "Gürtel des mächtigen Gesangs" ),
	array( "id" => "40193", "qual" => "4", "name" => "Tunika des maskierten Leidens" ),
	array( "id" => "40196", "qual" => "4", "name" => "Beinschützer der Unberührten" ),
	array( "id" => "40184", "qual" => "4", "name" => "Verkrüppelte Treter" ),
	array( "id" => "40185", "qual" => "4", "name" => "Schulterschutz der Möglichkeiten" ),
	array( "id" => "40188", "qual" => "4", "name" => "Stulpen des Ungehorsamen" ),
	array( "id" => "40187", "qual" => "4", "name" => "Scharfe Sabatons" ),
	array( "id" => "40071", "qual" => "4", "name" => "Ketten der Verehrung" ),
	array( "id" => "40065", "qual" => "4", "name" => "Narrenprüfung" ),
	array( "id" => "40069", "qual" => "4", "name" => "Erbe" ),
	array( "id" => "40064", "qual" => "4", "name" => "Gewitteramulett" ),
	array( "id" => "40080", "qual" => "4", "name" => "Verlorenes Juwel" ),
	array( "id" => "40075", "qual" => "4", "name" => "Skrupellosigkeit" ),
	array( "id" => "40107", "qual" => "4", "name" => "Sandgeschliffenes Band" ),
	array( "id" => "40074", "qual" => "4", "name" => "Ring der starken Hand" ),
	array( "id" => "40192", "qual" => "4", "name" => "Verwünschtes Rückgrat" ),
	array( "id" => "40191", "qual" => "4", "name" => "Buchband des Glanzes" ),
	array( "id" => "40189", "qual" => "4", "name" => "Wütender Schrecken" ),
	array( "id" => "40190", "qual" => "4", "name" => "Wirbelndes Schicksal" ),
);
?>