<?php
$loot = array(
	array( "id" => "40437", "qual" => "4", "name" => "Schulterposter des Verbergens" ),
	array( "id" => "40439", "qual" => "4", "name" => "Mantelung der ewigen Schildwache" ),
	array( "id" => "40451", "qual" => "4", "name" => "Hyalinhelm des Scharfschützen" ),
	array( "id" => "40438", "qual" => "4", "name" => "Schulterklappen der Versammlungskammer" ),
	array( "id" => "40453", "qual" => "4", "name" => "Brustplatte der Großen Aspekte" ),
	array( "id" => "40446", "qual" => "4", "name" => "Beinschützer der Drachenbrut" ),
	array( "id" => "40433", "qual" => "4", "name" => "Wyrmruhband" ),
	array( "id" => "40431", "qual" => "4", "name" => "Furor der fünf Schwärme" ),
	array( "id" => "40432", "qual" => "4", "name" => "Illustration der Drachenseele" ),
	array( "id" => "40455", "qual" => "4", "name" => "Stab der Zurückhaltung" ),
	array( "id" => "43345", "qual" => "4", "name" => "Tasche aus Drachenhaut" ),
	array( "id" => "43346", "qual" => "4", "name" => "Große Beutetasche" ),
	array( "id" => "40628", "qual" => "4", "name" => "Stulpen des verlorenen Eroberers" ),
	array( "id" => "40629", "qual" => "4", "name" => "Stulpen des verlorenen Beschützers" ),
	array( "id" => "40630", "qual" => "4", "name" => "Stulpen des verlorenen Bezwingers" ),
	array( "id" => "44002", "qual" => "4", "name" => "Fließende Gewänder des Sanktums" ),
	array( "id" => "44003", "qual" => "4", "name" => "Hochstehende Schiftung" ),
	array( "id" => "44004", "qual" => "4", "name" => "Reichliche Stulpen" ),
	array( "id" => "44000", "qual" => "4", "name" => "Drachensturmbrustplatte" ),
	array( "id" => "44005", "qual" => "4", "name" => "Wimpelumhang" ),
	array( "id" => "44008", "qual" => "4", "name" => "Unbefleckte Fesseln" ),
	array( "id" => "44007", "qual" => "4", "name" => "Kopfstück der Versöhnung" ),
	array( "id" => "44011", "qual" => "4", "name" => "Gamaschen des Geehrten" ),
	array( "id" => "44006", "qual" => "4", "name" => "Obsidiangroßhelm" ),
	array( "id" => "43954", "qual" => "4", "name" => "Zügel des Zwielichtdrachen" ),
);
?>