<?php
$loot = array(
	array( "id" => "39719", "qual" => "4", "name" => "Heuschreckenmantel" ),
	array( "id" => "39721", "qual" => "4", "name" => "Salonschärpe" ),
	array( "id" => "39720", "qual" => "4", "name" => "Gamaschen der Erschöpfung" ),
	array( "id" => "39722", "qual" => "4", "name" => "Schwarmbindungen" ),
	array( "id" => "39701", "qual" => "4", "name" => "Dämmerungswanderer" ),
	array( "id" => "39702", "qual" => "4", "name" => "Arachnoider Goldring" ),
	array( "id" => "39718", "qual" => "4", "name" => "Leichenskarabäushandschützer" ),
	array( "id" => "39704", "qual" => "4", "name" => "Schulterstücke des unnatürlichen Todes" ),
	array( "id" => "39703", "qual" => "4", "name" => "Auslöschender Handschutz" ),
	array( "id" => "39717", "qual" => "4", "name" => "Unaufhaltsame Sabatons" ),
	array( "id" => "39706", "qual" => "4", "name" => "Sabatons der plötzlichen Vergeltung" ),
	array( "id" => "40071", "qual" => "4", "name" => "Ketten der Verehrung" ),
	array( "id" => "40065", "qual" => "4", "name" => "Narrenprüfung" ),
	array( "id" => "40069", "qual" => "4", "name" => "Erbe" ),
	array( "id" => "40064", "qual" => "4", "name" => "Gewitteramulett" ),
	array( "id" => "40080", "qual" => "4", "name" => "Verlorenes Juwel" ),
	array( "id" => "40075", "qual" => "4", "name" => "Skrupellosigkeit" ),
	array( "id" => "40107", "qual" => "4", "name" => "Sandgeschliffenes Band" ),
	array( "id" => "40074", "qual" => "4", "name" => "Ring der starken Hand" ),
	array( "id" => "40208", "qual" => "4", "name" => "Biss der Gruftbestie" ),
	array( "id" => "39716", "qual" => "4", "name" => "Schild der Assimilierung" ),
	array( "id" => "39712", "qual" => "4", "name" => "Edelsteinbesetzter Zauberstab der Neruber" ),
);
?>