<?php
$loot = array(
	array( "id" => "49491", "qual" => "4", "name" => "Fließendes Saphirontuch" ),
	array( "id" => "49482", "qual" => "4", "name" => "Aurora der Erhabenheit" ),
	array( "id" => "49483", "qual" => "4", "name" => "Heiligenschein der Erhabenheit" ),
	array( "id" => "49484", "qual" => "4", "name" => "Schädelkappe der Nemesis" ),
	array( "id" => "49481", "qual" => "4", "name" => "Krone des Netherwinds" ),
	array( "id" => "49477", "qual" => "4", "name" => "Blutfangkapuze" ),
	array( "id" => "49472", "qual" => "4", "name" => "Sturmgrimms Krone" ),
	array( "id" => "49473", "qual" => "4", "name" => "Sturmgrimms Bedeckung" ),
	array( "id" => "49471", "qual" => "4", "name" => "Sturmgrimms Decke" ),
	array( "id" => "49469", "qual" => "4", "name" => "Krone der zehn Stürme" ),
	array( "id" => "49468", "qual" => "4", "name" => "Kopfschutz der zehn Stürme" ),
	array( "id" => "49470", "qual" => "4", "name" => "Helm der zehn Stürme" ),
	array( "id" => "49480", "qual" => "4", "name" => "Helm des Drachenjägers" ),
	array( "id" => "49479", "qual" => "4", "name" => "Kopfschutz des Zorns" ),
	array( "id" => "49478", "qual" => "4", "name" => "Helm des Zorns" ),
	array( "id" => "49467", "qual" => "4", "name" => "Frostgeschmiedeter Großhelm" ),
	array( "id" => "49466", "qual" => "4", "name" => "Frostgeschmiedeter Helm" ),
	array( "id" => "49476", "qual" => "4", "name" => "Krone des Richturteils" ),
	array( "id" => "49475", "qual" => "4", "name" => "Topfhelm des Richturteils" ),
	array( "id" => "49474", "qual" => "4", "name" => "Kapuze des Richturteils" ),
	array( "id" => "49492", "qual" => "4", "name" => "Eskhandars Bindungen" ),
	array( "id" => "49489", "qual" => "4", "name" => "Signifikanter Ring der Bindung" ),
	array( "id" => "49464", "qual" => "4", "name" => "Glänzender Splitter der Flamme" ),
	array( "id" => "49488", "qual" => "4", "name" => "Glänzender Splitter der Flamme" ),
	array( "id" => "49490", "qual" => "4", "name" => "Zauberfoliant des veralteten Grundsteins" ),
	array( "id" => "49295", "qual" => "4", "name" => "Vergrößerter Rucksack aus Onyxias Haut" ),
	array( "id" => "49636", "qual" => "4", "name" => "Zügel des Drachen von Onyxia" ),
	array( "id" => "49294", "qual" => "4", "name" => "Aschgrauer Sack voller Edelsteine" ),
	array( "id" => "49494", "qual" => "4", "name" => "Gewetzter Fangzahn der Mystiker" ),
	array( "id" => "49465", "qual" => "4", "name" => "Stumpfer Räuderipper" ),
	array( "id" => "49499", "qual" => "4", "name" => "Polierte Magierklinge des Azurlieds" ),
	array( "id" => "49495", "qual" => "4", "name" => "Brüniertes Quel'Serrar" ),
	array( "id" => "49501", "qual" => "4", "name" => "Getemperter Vis'kag der Blutvergießer" ),
	array( "id" => "49498", "qual" => "4", "name" => "Geschärfte scharfkantige Obsidianklinge" ),
	array( "id" => "49500", "qual" => "4", "name" => "Wütender Todesbringer" ),
	array( "id" => "49496", "qual" => "4", "name" => "Verstärkter Schattenschlag" ),
	array( "id" => "49497", "qual" => "4", "name" => "Verstärkter Donnerschlag" ),
	array( "id" => "49493", "qual" => "4", "name" => "Langläufiger Blasterwerfer" ),
	array( "id" => "49644", "qual" => "4", "name" => "Kopf von Onyxia" ),
	array( "id" => "49485", "qual" => "4", "name" => "Funkelnder Zahn Onyxias" ),
	array( "id" => "49486", "qual" => "4", "name" => "Poliertes Drachentötersignet" ),
	array( "id" => "49487", "qual" => "4", "name" => "Geläuterter Talisman mit Onyxiablut" ),
);

?>