<?php
$loot = array(
	array( "id" => "39492", "qual" => "4", "name" => "Heldenhafte Frostfeuerrobe" ),
	array( "id" => "39495", "qual" => "4", "name" => "Heldenhafte Frostfeuerhandschuhe" ),
	array( "id" => "39493", "qual" => "4", "name" => "Heldenhafte Frostfeuergamaschen" ),
	array( "id" => "39515", "qual" => "4", "name" => "Robe des heldenhaften Glaubens" ),
	array( "id" => "39519", "qual" => "4", "name" => "Handschuhe des heldenhaften Glaubens" ),
	array( "id" => "39517", "qual" => "4", "name" => "Gamaschen des heldenhaften Glaubens" ),
	array( "id" => "39523", "qual" => "4", "name" => "Gewandung des heldenhaften Glaubens" ),
	array( "id" => "39530", "qual" => "4", "name" => "Handlappen des heldenhaften Glaubens" ),
	array( "id" => "39528", "qual" => "4", "name" => "Hose des heldenhaften Glaubens" ),
	array( "id" => "39497", "qual" => "4", "name" => "Robe des heldenhaften verseuchten Herzens" ),
	array( "id" => "39500", "qual" => "4", "name" => "Handschuhe des heldenhaften verseuchten Herzens" ),
	array( "id" => "39498", "qual" => "4", "name" => "Gamaschen des heldenhaften verseuchten Herzens" ),
	array( "id" => "41950", "qual" => "4", "name" => "Seidene Gewandung des hasserfüllten Gladiators" ),
	array( "id" => "41969", "qual" => "4", "name" => "Seidene Handschützer des hasserfüllten Gladiators" ),
	array( "id" => "41957", "qual" => "4", "name" => "Seidene Beinkleider des hasserfüllten Gladiators" ),
	array( "id" => "41857", "qual" => "4", "name" => "Mondstoffrobe des hasserfüllten Gladiators" ),
	array( "id" => "41872", "qual" => "4", "name" => "Mondstoffhandschuhe des hasserfüllten Gladiators" ),
	array( "id" => "41862", "qual" => "4", "name" => "Mondstoffbeinschützer des hasserfüllten Gladiators" ),
	array( "id" => "41919", "qual" => "4", "name" => "Satinrobe des hasserfüllten Gladiators" ),
	array( "id" => "41938", "qual" => "4", "name" => "Satinhandschuhe des hasserfüllten Gladiators" ),
	array( "id" => "41925", "qual" => "4", "name" => "Satingamaschen des hasserfüllten Gladiators" ),
	array( "id" => "42001", "qual" => "4", "name" => "Teufelsgewebte Gewandung des hasserfüllten Gladiators" ),
	array( "id" => "42015", "qual" => "4", "name" => "Teufelsgewebte Handschützer des hasserfüllten Gladiators" ),
	array( "id" => "42003", "qual" => "4", "name" => "Teufelsgewebte Beinkleider des hasserfüllten Gladiators" ),
	array( "id" => "39547", "qual" => "4", "name" => "Gewand des heldenhaften Traumwandlers" ),
	array( "id" => "39544", "qual" => "4", "name" => "Handschuhe des heldenhaften Traumwandlers" ),
	array( "id" => "39546", "qual" => "4", "name" => "Hosen des heldenhaften Traumwandlers" ),
	array( "id" => "39554", "qual" => "4", "name" => "Gewandung des heldenhaften Traumwandlers" ),
	array( "id" => "39557", "qual" => "4", "name" => "Handschutz des heldenhaften Traumwandlers" ),
	array( "id" => "39555", "qual" => "4", "name" => "Beinschützer des heldenhaften Traumwandlers" ),
	array( "id" => "39538", "qual" => "4", "name" => "Robe des heldenhaften Traumwandlers" ),
	array( "id" => "39543", "qual" => "4", "name" => "Handschützer des heldenhaften Traumwandlers" ),
	array( "id" => "39539", "qual" => "4", "name" => "Gamaschen des heldenhaften Traumwandlers" ),
	array( "id" => "39558", "qual" => "4", "name" => "Brustplatte der heldenhaften Knochensense" ),
	array( "id" => "39560", "qual" => "4", "name" => "Stulpen der heldenhaften Knochensense" ),
	array( "id" => "39564", "qual" => "4", "name" => "Beinplatten der heldenhaften Knochensense" ),
	array( "id" => "41314", "qual" => "4", "name" => "Wyrmbalgrobe des hasserfüllten Gladiators" ),
	array( "id" => "41291", "qual" => "4", "name" => "Wyrmbalghandschuhe des hasserfüllten Gladiators" ),
	array( "id" => "41302", "qual" => "4", "name" => "Wyrmbalgbeinschützer des hasserfüllten Gladiators" ),
	array( "id" => "41659", "qual" => "4", "name" => "Drachenlederrobe des hasserfüllten Gladiators" ),
	array( "id" => "41771", "qual" => "4", "name" => "Drachenlederhandschuhe des hasserfüllten Gladiators" ),
	array( "id" => "41665", "qual" => "4", "name" => "Drachenlederbeinschützer des hasserfüllten Gladiators" ),
	array( "id" => "41308", "qual" => "4", "name" => "Kodobalgrobe des hasserfüllten Gladiators" ),
	array( "id" => "41284", "qual" => "4", "name" => "Kodobalghandschuhe des hasserfüllten Gladiators" ),
	array( "id" => "41296", "qual" => "4", "name" => "Kodobalgbeinschützer des hasserfüllten Gladiators" ),
	array( "id" => "41648", "qual" => "4", "name" => "Ledertunika des hasserfüllten Gladiators" ),
	array( "id" => "41765", "qual" => "4", "name" => "Lederhandschuhe des hasserfüllten Gladiators" ),
	array( "id" => "41653", "qual" => "4", "name" => "Lederbeinschützer des hasserfüllten Gladiators" ),
	array( "id" => "39579", "qual" => "4", "name" => "Tunika des heldenhaften Gruftpirschers" ),
	array( "id" => "39582", "qual" => "4", "name" => "Handschützer des heldenhaften Gruftpirschers" ),
	array( "id" => "39580", "qual" => "4", "name" => "Beinschützer des heldenhaften Gruftpirschers" ),
	array( "id" => "39592", "qual" => "4", "name" => "Halsberge des heldenhaften Erdspalters" ),
	array( "id" => "39593", "qual" => "4", "name" => "Handschuhe des heldenhaften Erdspalters" ),
	array( "id" => "39595", "qual" => "4", "name" => "Kilt des heldenhaften Erdspalters" ),
	array( "id" => "39597", "qual" => "4", "name" => "Brustschutz des heldenhaften Erdspalters" ),
	array( "id" => "39601", "qual" => "4", "name" => "Griffe des heldenhaften Erdspalters" ),
	array( "id" => "39603", "qual" => "4", "name" => "Kilt des heldenhaften Erdspalters" ),
	array( "id" => "39588", "qual" => "4", "name" => "Tunika des heldenhaften Erdspalters" ),
	array( "id" => "39591", "qual" => "4", "name" => "Handschützer des heldenhaften Erdspalters" ),
	array( "id" => "39589", "qual" => "4", "name" => "Beinschützer des heldenhaften Erdspalters" ),
	array( "id" => "41085", "qual" => "4", "name" => "Kettenrüstung des hasserfüllten Gladiators" ),
	array( "id" => "41141", "qual" => "4", "name" => "Kettenstulpen des hasserfüllten Gladiators" ),
	array( "id" => "41203", "qual" => "4", "name" => "Kettengamaschen des hasserfüllten Gladiators" ),
	array( "id" => "40989", "qual" => "4", "name" => "Panzerrüstung des hasserfüllten Gladiators" ),
	array( "id" => "41005", "qual" => "4", "name" => "Panzerstulpen des hasserfüllten Gladiators" ),
	array( "id" => "41031", "qual" => "4", "name" => "Panzergamaschen des hasserfüllten Gladiators" ),
	array( "id" => "41079", "qual" => "4", "name" => "Gekettelte Rüstung des hasserfüllten Gladiators" ),
	array( "id" => "41135", "qual" => "4", "name" => "Gekettelte Stulpen des hasserfüllten Gladiators" ),
	array( "id" => "41162", "qual" => "4", "name" => "Gekettelte Gamaschen des hasserfüllten Gladiators" ),
	array( "id" => "40988", "qual" => "4", "name" => "Ringpanzerrüstung des hasserfüllten Gladiators" ),
	array( "id" => "40999", "qual" => "4", "name" => "Ringpanzerstulpen des hasserfüllten Gladiators" ),
	array( "id" => "41025", "qual" => "4", "name" => "Ringpanzergamaschen des hasserfüllten Gladiators" ),
	array( "id" => "39617", "qual" => "4", "name" => "Kampfplatte des heldenhaften Geißelerben" ),
	array( "id" => "39618", "qual" => "4", "name" => "Stulpen des heldenhaften Geißelerben" ),
	array( "id" => "39620", "qual" => "4", "name" => "Beinplatten des heldenhaften Geißelerben" ),
	array( "id" => "39623", "qual" => "4", "name" => "Brustschutz des heldenhaften Geißelerben" ),
	array( "id" => "39624", "qual" => "4", "name" => "Handschützer des heldenhaften Geißelerben" ),
	array( "id" => "39626", "qual" => "4", "name" => "Beinschützer des heldenhaften Geißelerben" ),
	array( "id" => "39629", "qual" => "4", "name" => "Tunika der heldenhaften Erlösung" ),
	array( "id" => "39632", "qual" => "4", "name" => "Handschuhe der heldenhaften Erlösung" ),
	array( "id" => "39630", "qual" => "4", "name" => "Schienbeinschützer der heldenhaften Erlösung" ),
	array( "id" => "39633", "qual" => "4", "name" => "Brustharnisch der heldenhaften Erlösung" ),
	array( "id" => "39634", "qual" => "4", "name" => "Stulpen der heldenhaften Erlösung" ),
	array( "id" => "39636", "qual" => "4", "name" => "Beinplatten der heldenhaften Erlösung" ),
	array( "id" => "40781", "qual" => "4", "name" => "Schreckensplattenbrustharnisch des hasserfüllten Gladiators" ),
	array( "id" => "40803", "qual" => "4", "name" => "Schreckensplattenstulpen des hasserfüllten Gladiators" ),
	array( "id" => "40841", "qual" => "4", "name" => "Schreckensplattenbeinschützer des hasserfüllten Gladiators" ),
	array( "id" => "40925", "qual" => "4", "name" => "Zierathandschuhe des hasserfüllten Gladiators" ),
	array( "id" => "40904", "qual" => "4", "name" => "Zieratbrustschutz des hasserfüllten Gladiators" ),
	array( "id" => "40937", "qual" => "4", "name" => "Zieratbeinplatten des hasserfüllten Gladiators" ),
	array( "id" => "40782", "qual" => "4", "name" => "Schuppenharnisch des hasserfüllten Gladiators" ),
	array( "id" => "40802", "qual" => "4", "name" => "Schuppenstulpen des hasserfüllten Gladiators" ),
	array( "id" => "40842", "qual" => "4", "name" => "Schuppenbeinschützer des hasserfüllten Gladiators" ),
	array( "id" => "39638", "qual" => "4", "name" => "Brustplatte der heldenhaften Erlösung" ),
	array( "id" => "39639", "qual" => "4", "name" => "Handschützer der heldenhaften Erlösung" ),
	array( "id" => "39641", "qual" => "4", "name" => "Beinschützer der heldenhaften Erlösung" ),
	array( "id" => "39606", "qual" => "4", "name" => "Kampfplatte des heldenhaften Schreckenspanzers" ),
	array( "id" => "39609", "qual" => "4", "name" => "Stulpen des heldenhaften Schreckenspanzers" ),
	array( "id" => "39607", "qual" => "4", "name" => "Beinplatten des heldenhaften Schreckenspanzers" ),
	array( "id" => "39611", "qual" => "4", "name" => "Brustplatte des heldenhaften Schreckenspanzers" ),
	array( "id" => "39622", "qual" => "4", "name" => "Handschützer des heldenhaften Schreckenspanzers" ),
	array( "id" => "39612", "qual" => "4", "name" => "Beinschützer des heldenhaften Schreckenspanzers" ),
	array( "id" => "40752", "qual" => "4", "name" => "Emblem des Heldentums" ),
	array( "id" => "43959", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "44083", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "40783", "qual" => "4", "name" => "Plattenbrustharnisch des hasserfüllten Gladiators" ),
	array( "id" => "40801", "qual" => "4", "name" => "Plattenstulpen des hasserfüllten Gladiators" ),
	array( "id" => "40840", "qual" => "4", "name" => "Plattenbeinschützer des hasserfüllten Gladiators" ),
);
?>