<?php
if($this->get_faction() == 'alliance'){
$loot = array(
	array( "id" => "47753", "qual" => "4", "name" => "Khadgars Stulpen des Triumphs" ),
	array( "id" => "47755", "qual" => "4", "name" => "Khadgars Gamaschen des Triumphs" ),
	array( "id" => "47983", "qual" => "4", "name" => "Velens Handschuhe des Triumphs" ),
	array( "id" => "47985", "qual" => "4", "name" => "Velens Gamaschen des Triumphs" ),
	array( "id" => "48077", "qual" => "4", "name" => "Velens Handwickel des Triumphs" ),
	array( "id" => "48079", "qual" => "4", "name" => "Velens Hosen des Triumphs" ),
	array( "id" => "47782", "qual" => "4", "name" => "Kel'Thuzads Stulpen des Triumphs" ),
	array( "id" => "47780", "qual" => "4", "name" => "Kel'Thuzads Gamaschen des Triumphs" ),
	array( "id" => "41972", "qual" => "4", "name" => "Seidene Handschützer des unerbittlichen Gladiators" ),
	array( "id" => "41960", "qual" => "4", "name" => "Seidene Beinkleider des unerbittlichen Gladiators" ),
	array( "id" => "41875", "qual" => "4", "name" => "Mondstoffhandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41865", "qual" => "4", "name" => "Mondstoffgamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41941", "qual" => "4", "name" => "Satinhandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41928", "qual" => "4", "name" => "Satingamaschen des unerbittlichen Gladiators" ),
	array( "id" => "42018", "qual" => "4", "name" => "Teufelsgewebte Handschützer des unerbittlichen Gladiators" ),
	array( "id" => "42006", "qual" => "4", "name" => "Teufelsgewebte Beinkleider des unerbittlichen Gladiators" ),
	array( "id" => "48163", "qual" => "4", "name" => "Malfurions Handschuhe des Triumphs" ),
	array( "id" => "48165", "qual" => "4", "name" => "Malfurions Beinkleider des Triumphs" ),
	array( "id" => "48212", "qual" => "4", "name" => "Malfurions Handschutz des Triumphs" ),
	array( "id" => "48210", "qual" => "4", "name" => "Malfurions Beinschützer des Triumphs" ),
	array( "id" => "48133", "qual" => "4", "name" => "Malfurions Handschützer des Triumphs" ),
	array( "id" => "48135", "qual" => "4", "name" => "Malfurions Gamaschen des Triumphs" ),
	array( "id" => "48224", "qual" => "4", "name" => "Van Cleefs Stulpen des Triumphs" ),
	array( "id" => "48226", "qual" => "4", "name" => "Van Cleefs Beinplatten des Triumphs" ),
	array( "id" => "41294", "qual" => "4", "name" => "Wyrmbalghandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41305", "qual" => "4", "name" => "Wyrmbalgbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "41774", "qual" => "4", "name" => "Drachenlederhandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41668", "qual" => "4", "name" => "Drachenledergamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41288", "qual" => "4", "name" => "Kodobalghandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41299", "qual" => "4", "name" => "Kodobalgbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "41768", "qual" => "4", "name" => "Lederhandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41656", "qual" => "4", "name" => "Lederbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "48256", "qual" => "4", "name" => "Windläufers Handschützer des Triumphs" ),
	array( "id" => "48258", "qual" => "4", "name" => "Windläufers Beinschützer des Triumphs" ),
	array( "id" => "48317", "qual" => "4", "name" => "Nobundos Handschuhe des Triumphs" ),
	array( "id" => "48319", "qual" => "4", "name" => "Nobundos Kilt des Triumphs" ),
	array( "id" => "48347", "qual" => "4", "name" => "Nobundos Griff des Triumphs" ),
	array( "id" => "48349", "qual" => "4", "name" => "Nobundos Kriegskilt des Triumphs" ),
	array( "id" => "48286", "qual" => "4", "name" => "Nobundos Handschützer des Triumphs" ),
	array( "id" => "48288", "qual" => "4", "name" => "Nobundos Beinschützer des Triumphs" ),
	array( "id" => "41144", "qual" => "4", "name" => "Kettenstulpen des unerbittlichen Gladiators" ),
	array( "id" => "41206", "qual" => "4", "name" => "Kettengamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41008", "qual" => "4", "name" => "Panzerstulpen des unerbittlichen Gladiators" ),
	array( "id" => "41034", "qual" => "4", "name" => "Panzergamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41138", "qual" => "4", "name" => "Gekettelte Stulpen des unerbittlichen Gladiators" ),
	array( "id" => "41200", "qual" => "4", "name" => "Gekettelte Gamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41002", "qual" => "4", "name" => "Ringpanzerstulpen des unerbittlichen Gladiators" ),
	array( "id" => "41028", "qual" => "4", "name" => "Ringpanzergamaschen des unerbittlichen Gladiators" ),
	array( "id" => "48482", "qual" => "4", "name" => "Thassarians Stulpen des Triumphs" ),
	array( "id" => "48484", "qual" => "4", "name" => "Thassarians Beinplatten des Triumphs" ),
	array( "id" => "48539", "qual" => "4", "name" => "Thassarians Handschützer des Triumphs" ),
	array( "id" => "48541", "qual" => "4", "name" => "Thassarians Beinschützer des Triumphs" ),
	array( "id" => "48576", "qual" => "4", "name" => "Turalyons Handschuhe des Triumphs" ),
	array( "id" => "48578", "qual" => "4", "name" => "Turalyons Schienbeinschützer des Triumphs" ),
	array( "id" => "48608", "qual" => "4", "name" => "Turalyons Stulpen des Triumphs" ),
	array( "id" => "48610", "qual" => "4", "name" => "Turalyons Beinplatten des Triumphs" ),
	array( "id" => "40811", "qual" => "4", "name" => "Schreckensplattenstulpen des unerbittlichen Gladiators" ),
	array( "id" => "40851", "qual" => "4", "name" => "Schreckensplattenbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "40928", "qual" => "4", "name" => "Zierathandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "40940", "qual" => "4", "name" => "Zieratgamaschen des unerbittlichen Gladiators" ),
	array( "id" => "40812", "qual" => "4", "name" => "Schuppenstulpen des unerbittlichen Gladiators" ),
	array( "id" => "40852", "qual" => "4", "name" => "Schuppenbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "48640", "qual" => "4", "name" => "Turalyons Handschützer des Triumphs" ),
	array( "id" => "48638", "qual" => "4", "name" => "Turalyons Beinschützer des Triumphs" ),
	array( "id" => "48377", "qual" => "4", "name" => "Wrynns Stulpen des Triumphs" ),
	array( "id" => "48379", "qual" => "4", "name" => "Wrynns Beinplatten des Triumphs" ),
	array( "id" => "48452", "qual" => "4", "name" => "Wrynns Handschützer des Triumphs" ),
	array( "id" => "48446", "qual" => "4", "name" => "Wrynns Beinschützer des Triumphs" ),
	array( "id" => "40810", "qual" => "4", "name" => "Plattenstulpen des unerbittlichen Gladiators" ),
	array( "id" => "40850", "qual" => "4", "name" => "Plattenbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "41910", "qual" => "4", "name" => "Vorherrschaftsmanschetten des unerbittlichen Gladiators" ),
	array( "id" => "41899", "qual" => "4", "name" => "Vorherrschaftskordel des unerbittlichen Gladiators" ),
	array( "id" => "41904", "qual" => "4", "name" => "Vorherrschaftstreter des unerbittlichen Gladiators" ),
	array( "id" => "41894", "qual" => "4", "name" => "Errettermanschetten des unerbittlichen Gladiators" ),
	array( "id" => "41882", "qual" => "4", "name" => "Erretterkordel des unerbittlichen Gladiators" ),
	array( "id" => "41886", "qual" => "4", "name" => "Errettertreter des unerbittlichen Gladiators" ),
	array( "id" => "49181", "qual" => "4", "name" => "Eifermanschetten des unerbittlichen Gladiators" ),
	array( "id" => "49179", "qual" => "4", "name" => "Eiferkordel des unerbittlichen Gladiators" ),
	array( "id" => "49183", "qual" => "4", "name" => "Eifertreter des unerbittlichen Gladiators" ),
	array( "id" => "41641", "qual" => "4", "name" => "Vorherrschaftsarmwickel des unerbittlichen Gladiators" ),
	array( "id" => "41631", "qual" => "4", "name" => "Vorherrschaftsgürtel des unerbittlichen Gladiators" ),
	array( "id" => "41636", "qual" => "4", "name" => "Vorherrschaftsstiefel des unerbittlichen Gladiators" ),
	array( "id" => "41626", "qual" => "4", "name" => "Erretterarmwickel des unerbittlichen Gladiators" ),
	array( "id" => "41618", "qual" => "4", "name" => "Errettergürtel des unerbittlichen Gladiators" ),
	array( "id" => "41622", "qual" => "4", "name" => "Erretterstiefel des unerbittlichen Gladiators" ),
	array( "id" => "41841", "qual" => "4", "name" => "Triumphale Armwickel des unerbittlichen Gladiators" ),
	array( "id" => "41833", "qual" => "4", "name" => "Triumphaler Gürtel des unerbittlichen Gladiators" ),
	array( "id" => "41837", "qual" => "4", "name" => "Triumphale Stiefel des unerbittlichen Gladiators" ),
	array( "id" => "41066", "qual" => "4", "name" => "Vorherrschaftshandgelenksschutz des unerbittlichen Gladiators" ),
	array( "id" => "41071", "qual" => "4", "name" => "Vorherrschaftstaillenschutz des unerbittlichen Gladiators" ),
	array( "id" => "41076", "qual" => "4", "name" => "Vorherrschaftssabatons des unerbittlichen Gladiators" ),
	array( "id" => "41061", "qual" => "4", "name" => "Erretterhandgelenksschutz des unerbittlichen Gladiators" ),
	array( "id" => "41052", "qual" => "4", "name" => "Errettertaillenschutz des unerbittlichen Gladiators" ),
	array( "id" => "41056", "qual" => "4", "name" => "Errettersabatons des unerbittlichen Gladiators" ),
	array( "id" => "41226", "qual" => "4", "name" => "Triumphaler Handgelenksschutz des unerbittlichen Gladiators" ),
	array( "id" => "41236", "qual" => "4", "name" => "Triumphaler Taillenschutz des unerbittlichen Gladiators" ),
	array( "id" => "41231", "qual" => "4", "name" => "Triumphale Sabatons des unerbittlichen Gladiators" ),
	array( "id" => "40984", "qual" => "4", "name" => "Erretterarmschienen des unerbittlichen Gladiators" ),
	array( "id" => "40978", "qual" => "4", "name" => "Errettergurt des unerbittlichen Gladiators" ),
	array( "id" => "40979", "qual" => "4", "name" => "Erretterschienbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "40890", "qual" => "4", "name" => "Triumphale Armschienen des unerbittlichen Gladiators" ),
	array( "id" => "40883", "qual" => "4", "name" => "Triumphaler Gurt des unerbittlichen Gladiators" ),
	array( "id" => "40884", "qual" => "4", "name" => "Triumphale Schienbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "42078", "qual" => "4", "name" => "Vormachtsumhang des unerbittlichen Gladiators" ),
	array( "id" => "42080", "qual" => "4", "name" => "Erlösungsumhang des unerbittlichen Gladiators" ),
	array( "id" => "42076", "qual" => "4", "name" => "Vorherrschaftsumhang des unerbittlichen Gladiators" ),
	array( "id" => "42079", "qual" => "4", "name" => "Erretterumhang des unerbittlichen Gladiators" ),
	array( "id" => "42077", "qual" => "4", "name" => "Unterwerfungsumhang des unerbittlichen Gladiators" ),
	array( "id" => "42081", "qual" => "4", "name" => "Triumphaler Umhang des unerbittlichen Gladiators" ),
	array( "id" => "42082", "qual" => "4", "name" => "Siegesumhang des unerbittlichen Gladiators" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem des Triumphs" ),
	array( "id" => "43959", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "44083", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "42044", "qual" => "4", "name" => "Vormachtsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42046", "qual" => "4", "name" => "Erlösungsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42043", "qual" => "4", "name" => "Vorherrschaftsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42047", "qual" => "4", "name" => "Erretteranhänger des unerbittlichen Gladiators" ),
	array( "id" => "42045", "qual" => "4", "name" => "Unterwerfungsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "46374", "qual" => "4", "name" => "Zerschlagungsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42041", "qual" => "4", "name" => "Triumphaler Anhänger des unerbittlichen Gladiators" ),
	array( "id" => "42042", "qual" => "4", "name" => "Siegesanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42118", "qual" => "4", "name" => "Vormachtsband des unerbittlichen Gladiators" ),
	array( "id" => "42119", "qual" => "4", "name" => "Siegesband des unerbittlichen Gladiators" ),
);
}else{
$loot = array(
	array( "id" => "47772", "qual" => "4", "name" => "Sonnenwanderers Stulpen des Triumphs" ),
	array( "id" => "47770", "qual" => "4", "name" => "Sonnenwanderers Gamaschen des Triumphs" ),
	array( "id" => "48066", "qual" => "4", "name" => "Zabras Handschuhe des Triumphs" ),
	array( "id" => "48064", "qual" => "4", "name" => "Zabras Gamaschen des Triumphs" ),
	array( "id" => "48096", "qual" => "4", "name" => "Zabras Handwickel des Triumphs" ),
	array( "id" => "48094", "qual" => "4", "name" => "Zabras Hosen des Triumphs" ),
	array( "id" => "47803", "qual" => "4", "name" => "Gul'dans Stulpen des Triumphs" ),
	array( "id" => "47805", "qual" => "4", "name" => "Gul'dans Gamaschen des Triumphs" ),
	array( "id" => "41972", "qual" => "4", "name" => "Seidene Handschützer des unerbittlichen Gladiators" ),
	array( "id" => "41960", "qual" => "4", "name" => "Seidene Beinkleider des unerbittlichen Gladiators" ),
	array( "id" => "41875", "qual" => "4", "name" => "Mondstoffhandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41865", "qual" => "4", "name" => "Mondstoffgamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41941", "qual" => "4", "name" => "Satinhandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41928", "qual" => "4", "name" => "Satingamaschen des unerbittlichen Gladiators" ),
	array( "id" => "42018", "qual" => "4", "name" => "Teufelsgewebte Handschützer des unerbittlichen Gladiators" ),
	array( "id" => "42006", "qual" => "4", "name" => "Teufelsgewebte Beinkleider des unerbittlichen Gladiators" ),
	array( "id" => "48182", "qual" => "4", "name" => "Runentotems Handschuhe des Triumphs" ),
	array( "id" => "48180", "qual" => "4", "name" => "Runentotems Beinkleider des Triumphs" ),
	array( "id" => "48193", "qual" => "4", "name" => "Runentotems Handschutz des Triumphs" ),
	array( "id" => "48195", "qual" => "4", "name" => "Runentotems Beinschützer des Triumphs" ),
	array( "id" => "48152", "qual" => "4", "name" => "Runentotems Handschützer des Triumphs" ),
	array( "id" => "48150", "qual" => "4", "name" => "Runentotems Gamaschen des Triumphs" ),
	array( "id" => "48241", "qual" => "4", "name" => "Garonas Stulpen des Triumphs" ),
	array( "id" => "48239", "qual" => "4", "name" => "Garonas Beinplatten des Triumphs" ),
	array( "id" => "41294", "qual" => "4", "name" => "Wyrmbalghandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41305", "qual" => "4", "name" => "Wyrmbalgbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "41774", "qual" => "4", "name" => "Drachenlederhandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41668", "qual" => "4", "name" => "Drachenledergamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41288", "qual" => "4", "name" => "Kodobalghandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41299", "qual" => "4", "name" => "Kodobalgbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "41768", "qual" => "4", "name" => "Lederhandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "41656", "qual" => "4", "name" => "Lederbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "48273", "qual" => "4", "name" => "Windläufers Handschützer des Triumphs" ),
	array( "id" => "48271", "qual" => "4", "name" => "Windläufers Beinschützer des Triumphs" ),
	array( "id" => "48334", "qual" => "4", "name" => "Thralls Handschuhe des Triumphs" ),
	array( "id" => "48332", "qual" => "4", "name" => "Thralls Kilt des Triumphs" ),
	array( "id" => "48364", "qual" => "4", "name" => "Thralls Griff des Triumphs" ),
	array( "id" => "48362", "qual" => "4", "name" => "Thralls Kriegskilt des Triumphs" ),
	array( "id" => "48301", "qual" => "4", "name" => "Thralls Handschützer des Triumphs" ),
	array( "id" => "48303", "qual" => "4", "name" => "Thralls Beinschützer des Triumphs" ),
	array( "id" => "41144", "qual" => "4", "name" => "Kettenstulpen des unerbittlichen Gladiators" ),
	array( "id" => "41206", "qual" => "4", "name" => "Kettengamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41008", "qual" => "4", "name" => "Panzerstulpen des unerbittlichen Gladiators" ),
	array( "id" => "41034", "qual" => "4", "name" => "Panzergamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41138", "qual" => "4", "name" => "Gekettelte Stulpen des unerbittlichen Gladiators" ),
	array( "id" => "41200", "qual" => "4", "name" => "Gekettelte Gamaschen des unerbittlichen Gladiators" ),
	array( "id" => "41002", "qual" => "4", "name" => "Ringpanzerstulpen des unerbittlichen Gladiators" ),
	array( "id" => "41028", "qual" => "4", "name" => "Ringpanzergamaschen des unerbittlichen Gladiators" ),
	array( "id" => "48499", "qual" => "4", "name" => "Koltiras Stulpen des Triumphs" ),
	array( "id" => "48497", "qual" => "4", "name" => "Koltiras Beinplatten des Triumphs" ),
	array( "id" => "48556", "qual" => "4", "name" => "Koltiras Handschützer des Triumphs" ),
	array( "id" => "48554", "qual" => "4", "name" => "Koltiras Beinschützer des Triumphs" ),
	array( "id" => "48593", "qual" => "4", "name" => "Liadrins Handschuhe des Triumphs" ),
	array( "id" => "48591", "qual" => "4", "name" => "Liadrins Schienbeinschützer des Triumphs" ),
	array( "id" => "48625", "qual" => "4", "name" => "Liadrins Stulpen des Triumphs" ),
	array( "id" => "48623", "qual" => "4", "name" => "Liadrins Beinplatten des Triumphs" ),
	array( "id" => "40811", "qual" => "4", "name" => "Schreckensplattenstulpen des unerbittlichen Gladiators" ),
	array( "id" => "40851", "qual" => "4", "name" => "Schreckensplattenbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "40928", "qual" => "4", "name" => "Zierathandschuhe des unerbittlichen Gladiators" ),
	array( "id" => "40940", "qual" => "4", "name" => "Zieratgamaschen des unerbittlichen Gladiators" ),
	array( "id" => "40812", "qual" => "4", "name" => "Schuppenstulpen des unerbittlichen Gladiators" ),
	array( "id" => "40852", "qual" => "4", "name" => "Schuppenbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "48658", "qual" => "4", "name" => "Liadrins Handschützer des Triumphs" ),
	array( "id" => "48660", "qual" => "4", "name" => "Liadrins Beinschützer des Triumphs" ),
	array( "id" => "48392", "qual" => "4", "name" => "Höllschreis Stulpen des Triumphs" ),
	array( "id" => "48394", "qual" => "4", "name" => "Höllschreis Beinplatten des Triumphs" ),
	array( "id" => "48462", "qual" => "4", "name" => "Höllschreis Handschützer des Triumphs" ),
	array( "id" => "48464", "qual" => "4", "name" => "Höllschreis Beinschützer des Triumphs" ),
	array( "id" => "40810", "qual" => "4", "name" => "Plattenstulpen des unerbittlichen Gladiators" ),
	array( "id" => "40850", "qual" => "4", "name" => "Plattenbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "41910", "qual" => "4", "name" => "Vorherrschaftsmanschetten des unerbittlichen Gladiators" ),
	array( "id" => "41899", "qual" => "4", "name" => "Vorherrschaftskordel des unerbittlichen Gladiators" ),
	array( "id" => "41904", "qual" => "4", "name" => "Vorherrschaftstreter des unerbittlichen Gladiators" ),
	array( "id" => "41894", "qual" => "4", "name" => "Errettermanschetten des unerbittlichen Gladiators" ),
	array( "id" => "41882", "qual" => "4", "name" => "Erretterkordel des unerbittlichen Gladiators" ),
	array( "id" => "41886", "qual" => "4", "name" => "Errettertreter des unerbittlichen Gladiators" ),
	array( "id" => "49181", "qual" => "4", "name" => "Eifermanschetten des unerbittlichen Gladiators" ),
	array( "id" => "49179", "qual" => "4", "name" => "Eiferkordel des unerbittlichen Gladiators" ),
	array( "id" => "49183", "qual" => "4", "name" => "Eifertreter des unerbittlichen Gladiators" ),
	array( "id" => "41641", "qual" => "4", "name" => "Vorherrschaftsarmwickel des unerbittlichen Gladiators" ),
	array( "id" => "41631", "qual" => "4", "name" => "Vorherrschaftsgürtel des unerbittlichen Gladiators" ),
	array( "id" => "41636", "qual" => "4", "name" => "Vorherrschaftsstiefel des unerbittlichen Gladiators" ),
	array( "id" => "41626", "qual" => "4", "name" => "Erretterarmwickel des unerbittlichen Gladiators" ),
	array( "id" => "41618", "qual" => "4", "name" => "Errettergürtel des unerbittlichen Gladiators" ),
	array( "id" => "41622", "qual" => "4", "name" => "Erretterstiefel des unerbittlichen Gladiators" ),
	array( "id" => "41841", "qual" => "4", "name" => "Triumphale Armwickel des unerbittlichen Gladiators" ),
	array( "id" => "41833", "qual" => "4", "name" => "Triumphaler Gürtel des unerbittlichen Gladiators" ),
	array( "id" => "41837", "qual" => "4", "name" => "Triumphale Stiefel des unerbittlichen Gladiators" ),
	array( "id" => "41066", "qual" => "4", "name" => "Vorherrschaftshandgelenksschutz des unerbittlichen Gladiators" ),
	array( "id" => "41071", "qual" => "4", "name" => "Vorherrschaftstaillenschutz des unerbittlichen Gladiators" ),
	array( "id" => "41076", "qual" => "4", "name" => "Vorherrschaftssabatons des unerbittlichen Gladiators" ),
	array( "id" => "41061", "qual" => "4", "name" => "Erretterhandgelenksschutz des unerbittlichen Gladiators" ),
	array( "id" => "41052", "qual" => "4", "name" => "Errettertaillenschutz des unerbittlichen Gladiators" ),
	array( "id" => "41056", "qual" => "4", "name" => "Errettersabatons des unerbittlichen Gladiators" ),
	array( "id" => "41226", "qual" => "4", "name" => "Triumphaler Handgelenksschutz des unerbittlichen Gladiators" ),
	array( "id" => "41236", "qual" => "4", "name" => "Triumphaler Taillenschutz des unerbittlichen Gladiators" ),
	array( "id" => "41231", "qual" => "4", "name" => "Triumphale Sabatons des unerbittlichen Gladiators" ),
	array( "id" => "40984", "qual" => "4", "name" => "Erretterarmschienen des unerbittlichen Gladiators" ),
	array( "id" => "40978", "qual" => "4", "name" => "Errettergurt des unerbittlichen Gladiators" ),
	array( "id" => "40979", "qual" => "4", "name" => "Erretterschienbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "40890", "qual" => "4", "name" => "Triumphale Armschienen des unerbittlichen Gladiators" ),
	array( "id" => "40883", "qual" => "4", "name" => "Triumphaler Gurt des unerbittlichen Gladiators" ),
	array( "id" => "40884", "qual" => "4", "name" => "Triumphale Schienbeinschützer des unerbittlichen Gladiators" ),
	array( "id" => "42078", "qual" => "4", "name" => "Vormachtsumhang des unerbittlichen Gladiators" ),
	array( "id" => "42080", "qual" => "4", "name" => "Erlösungsumhang des unerbittlichen Gladiators" ),
	array( "id" => "42076", "qual" => "4", "name" => "Vorherrschaftsumhang des unerbittlichen Gladiators" ),
	array( "id" => "42079", "qual" => "4", "name" => "Erretterumhang des unerbittlichen Gladiators" ),
	array( "id" => "42077", "qual" => "4", "name" => "Unterwerfungsumhang des unerbittlichen Gladiators" ),
	array( "id" => "42081", "qual" => "4", "name" => "Triumphaler Umhang des unerbittlichen Gladiators" ),
	array( "id" => "42082", "qual" => "4", "name" => "Siegesumhang des unerbittlichen Gladiators" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem des Triumphs" ),
	array( "id" => "43959", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "44083", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "42044", "qual" => "4", "name" => "Vormachtsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42046", "qual" => "4", "name" => "Erlösungsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42043", "qual" => "4", "name" => "Vorherrschaftsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42047", "qual" => "4", "name" => "Erretteranhänger des unerbittlichen Gladiators" ),
	array( "id" => "42045", "qual" => "4", "name" => "Unterwerfungsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "46374", "qual" => "4", "name" => "Zerschlagungsanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42041", "qual" => "4", "name" => "Triumphaler Anhänger des unerbittlichen Gladiators" ),
	array( "id" => "42042", "qual" => "4", "name" => "Siegesanhänger des unerbittlichen Gladiators" ),
	array( "id" => "42118", "qual" => "4", "name" => "Vormachtsband des unerbittlichen Gladiators" ),
	array( "id" => "42119", "qual" => "4", "name" => "Siegesband des unerbittlichen Gladiators" ),
);
}

?>