<?php
$loot = array(
	array( "id" => "45665", "qual" => "4", "name" => "Pharos Handschuhe" ),
	array( "id" => "45619", "qual" => "4", "name" => "Bindungen des Sternenwächters" ),
	array( "id" => "45611", "qual" => "4", "name" => "Solarbindungen" ),
	array( "id" => "45616", "qual" => "4", "name" => "Sternenbesetzte Umklammerung" ),
	array( "id" => "45610", "qual" => "4", "name" => "Allumfassender Blick" ),
	array( "id" => "45615", "qual" => "4", "name" => "Treter des Ebenenwandlers" ),
	array( "id" => "45594", "qual" => "4", "name" => "Beinplatten der endlosen Leere" ),
	array( "id" => "45599", "qual" => "4", "name" => "Sabatons der leblosen Nacht" ),
	array( "id" => "45617", "qual" => "4", "name" => "Kosmos" ),
	array( "id" => "45620", "qual" => "4", "name" => "Sternensplitterschneide" ),
	array( "id" => "45607", "qual" => "4", "name" => "Fangzahn des Vergessens" ),
	array( "id" => "45612", "qual" => "4", "name" => "Konstellas" ),
	array( "id" => "45613", "qual" => "4", "name" => "Traumbinder" ),
	array( "id" => "45587", "qual" => "4", "name" => "Bollwerk von Algalon" ),
	array( "id" => "45570", "qual" => "4", "name" => "Armbrust der Himmelsschmiede" ),
	array( "id" => "45609", "qual" => "4", "name" => "Kometenschweif" ),
	array( "id" => "46053", "qual" => "4", "name" => "Antwortcode Alpha" ),
	array( "id" => "45588", "qual" => "4", "name" => "Tuch des Himmelsgeborenen" ),
	array( "id" => "45618", "qual" => "4", "name" => "Sonnenglimmerumhang" ),
	array( "id" => "45608", "qual" => "4", "name" => "Branns Siegelring" ),
	array( "id" => "45614", "qual" => "4", "name" => "Sternenlichtkreis" ),
);
?>