<?php
$loot = array(
	array( "id" => "40271", "qual" => "4", "name" => "Schärpe der Einsamkeit" ),
	array( "id" => "40269", "qual" => "4", "name" => "Stiefel der Überzeugung" ),
	array( "id" => "40260", "qual" => "4", "name" => "Gürtel des Gefolterten" ),
	array( "id" => "40270", "qual" => "4", "name" => "Stiefel der septischen Wunden" ),
	array( "id" => "40262", "qual" => "4", "name" => "Handschuhe des berechneten Risikos" ),
	array( "id" => "40272", "qual" => "4", "name" => "Gurt des Schachzugs" ),
	array( "id" => "40261", "qual" => "4", "name" => "Grobe verfärbte Kampfhandschuhe" ),
	array( "id" => "40263", "qual" => "4", "name" => "Fleischloser Gurt" ),
	array( "id" => "40259", "qual" => "4", "name" => "Taillenschutz der göttlichen Anmut" ),
	array( "id" => "40071", "qual" => "4", "name" => "Ketten der Verehrung" ),
	array( "id" => "40065", "qual" => "4", "name" => "Narrenprüfung" ),
	array( "id" => "40069", "qual" => "4", "name" => "Erbe" ),
	array( "id" => "40064", "qual" => "4", "name" => "Gewitteramulett" ),
	array( "id" => "40080", "qual" => "4", "name" => "Verlorenes Juwel" ),
	array( "id" => "40075", "qual" => "4", "name" => "Skrupellosigkeit" ),
	array( "id" => "40107", "qual" => "4", "name" => "Sandgeschliffenes Band" ),
	array( "id" => "40074", "qual" => "4", "name" => "Ring der starken Hand" ),
	array( "id" => "40273", "qual" => "4", "name" => "Überzähliger Arm" ),
	array( "id" => "40267", "qual" => "4", "name" => "Totem der Verhexung" ),
	array( "id" => "40268", "qual" => "4", "name" => "Buchband der Toleranz" ),
	array( "id" => "40264", "qual" => "4", "name" => "Gespaltener Großhammer" ),
	array( "id" => "40266", "qual" => "4", "name" => "Heldenhingabe" ),
	array( "id" => "40265", "qual" => "4", "name" => "Gesang der Pfeile" ),
);
?>