<?php
$loot = array(
	array( "id" => "40254", "qual" => "4", "name" => "Umhang der abgewendeten Krise" ),
	array( "id" => "40252", "qual" => "4", "name" => "Umhang der verfinsterten Sonne" ),
	array( "id" => "40253", "qual" => "4", "name" => "Schal der alten Maid" ),
	array( "id" => "40251", "qual" => "4", "name" => "Tuch der Leuchtkraft" ),
	array( "id" => "40339", "qual" => "4", "name" => "Gothiks Gugel" ),
	array( "id" => "40338", "qual" => "4", "name" => "Bindungen des Verlangens" ),
	array( "id" => "40329", "qual" => "4", "name" => "Kapuze des Exodus" ),
	array( "id" => "40341", "qual" => "4", "name" => "Fesselsattelgurt" ),
	array( "id" => "40333", "qual" => "4", "name" => "Gamaschen der flüchtigen Momente" ),
	array( "id" => "40340", "qual" => "4", "name" => "Helm der entfesselten Energie" ),
	array( "id" => "40331", "qual" => "4", "name" => "Gamaschen der fehlgeschlagenen Flucht" ),
	array( "id" => "40328", "qual" => "4", "name" => "Helm des lebensnotwendigen Schutzes" ),
	array( "id" => "40334", "qual" => "4", "name" => "Niederdrückende Schulterplatten" ),
	array( "id" => "40332", "qual" => "4", "name" => "Armschienen der Beihilfe" ),
	array( "id" => "40330", "qual" => "4", "name" => "Armschienen des unerbittlichen Angriffs" ),
	array( "id" => "40257", "qual" => "4", "name" => "Kodex des Verteidigers" ),
	array( "id" => "40255", "qual" => "4", "name" => "Letzter Fluch" ),
	array( "id" => "40258", "qual" => "4", "name" => "Talisman der Vorsehung" ),
	array( "id" => "40256", "qual" => "4", "name" => "Grimmiger Tribut" ),
	array( "id" => "40342", "qual" => "4", "name" => "Götze der Erweckung" ),
	array( "id" => "40337", "qual" => "4", "name" => "Buchband der Wiederauferstehung" ),
	array( "id" => "40336", "qual" => "4", "name" => "Leben und Tod" ),
	array( "id" => "40335", "qual" => "4", "name" => "Berührung des Grauens" ),
);
?>