<?php
$loot = array(
	array( "id" => "45038", "qual" => "5", "name" => "Fragment von Val'anyr" ),
	array( "id" => "46017", "qual" => "5", "name" => "Val'anyr, Hammer der Uralten Könige" ),
	array( "id" => "45117", "qual" => "4", "name" => "Handlappen des Konstrukteurs" ),
	array( "id" => "45119", "qual" => "4", "name" => "Umarmung des Leviathan" ),
	array( "id" => "45108", "qual" => "4", "name" => "Bindungen des Mechanikers" ),
	array( "id" => "45118", "qual" => "4", "name" => "Brille des Dampfarbeiters" ),
	array( "id" => "45109", "qual" => "4", "name" => "Handschuhe des feurigen Ungetüms" ),
	array( "id" => "45107", "qual" => "4", "name" => "Eisennietenkriegshelm" ),
	array( "id" => "45111", "qual" => "4", "name" => "Mimirons Gelenkstücke des Infernos" ),
	array( "id" => "45116", "qual" => "4", "name" => "Freyas Halsreif des Walls" ),
	array( "id" => "45113", "qual" => "4", "name" => "Leuchtender Ring der Wiedergewinnung" ),
	array( "id" => "45106", "qual" => "4", "name" => "Stärke des Automaten" ),
	array( "id" => "45112", "qual" => "4", "name" => "Die Windungen des Leviathan" ),
	array( "id" => "45115", "qual" => "4", "name" => "Betankungshandbuch für den Leviathan" ),
	array( "id" => "45114", "qual" => "4", "name" => "Totem des Dampfrufers" ),
	array( "id" => "45110", "qual" => "4", "name" => "Titanenwache" ),
	array( "id" => "45086", "qual" => "4", "name" => "Aufgehende Sonne" ),
	array( "id" => "45135", "qual" => "4", "name" => "Stiefel der feurigen Entschlossenheit" ),
	array( "id" => "45136", "qual" => "4", "name" => "Schulterpolster der schlafenden Energien" ),
	array( "id" => "45134", "qual" => "4", "name" => "Plated Leggings of Ruination" ),
	array( "id" => "45133", "qual" => "4", "name" => "Anhänger der feurigen Verwüstung" ),
	array( "id" => "45132", "qual" => "4", "name" => "Goldener Saronitdrache" ),
);
?>