<?php
$loot = array(
	array( "id" => "40381", "qual" => "4", "name" => "Mitgefühl" ),
	array( "id" => "40380", "qual" => "4", "name" => "Handschuhe der Herrlichkeit" ),
	array( "id" => "40376", "qual" => "4", "name" => "Beinwickel des besiegten Drachen" ),
	array( "id" => "40362", "qual" => "4", "name" => "Handschuhe der schnellen Reaktionen" ),
	array( "id" => "40379", "qual" => "4", "name" => "Beinschützer des Totenackers" ),
	array( "id" => "40367", "qual" => "4", "name" => "Stiefel des großen Konstruktes" ),
	array( "id" => "40366", "qual" => "4", "name" => "Plattenhelm des großen Wyrm" ),
	array( "id" => "40377", "qual" => "4", "name" => "Schulterstücke des edlen Geburtsrechts" ),
	array( "id" => "40365", "qual" => "4", "name" => "Brustplatte der eisigen Qual" ),
	array( "id" => "40363", "qual" => "4", "name" => "Knochenverzierte Gamaschen" ),
	array( "id" => "40378", "qual" => "4", "name" => "Endloses Erbarmen" ),
	array( "id" => "40374", "qual" => "4", "name" => "Kosmische Lichter" ),
	array( "id" => "40369", "qual" => "4", "name" => "Eisschlagamulett" ),
	array( "id" => "40370", "qual" => "4", "name" => "Torwächter" ),
	array( "id" => "40375", "qual" => "4", "name" => "Ring der vergehenden Schönheit" ),
	array( "id" => "40371", "qual" => "4", "name" => "Banditeninsigne" ),
	array( "id" => "40373", "qual" => "4", "name" => "Extrakt nekromantischer Macht" ),
	array( "id" => "40372", "qual" => "4", "name" => "Rune des Rückstoßes" ),
	array( "id" => "40382", "qual" => "4", "name" => "Seele der Toten" ),
	array( "id" => "40368", "qual" => "4", "name" => "Meuchelmörder" ),
	array( "id" => "44577", "qual" => "4", "name" => "Heroischer Schlüssel der fokussierenden Iris" ),
	array( "id" => "44581", "qual" => "4", "name" => "Heroischer Schlüssel der fokussierenden Iris" ),
);
?>