<?php
$loot = array(
	array( "id" => "40418", "qual" => "4", "name" => "Tapfere Frostfeuerrobe" ),
	array( "id" => "40415", "qual" => "4", "name" => "Tapfere Frostfeuerhandschuhe" ),
	array( "id" => "40417", "qual" => "4", "name" => "Tapfere Frostfeuergamaschen" ),
	array( "id" => "40449", "qual" => "4", "name" => "Robe des tapferen Glaubens" ),
	array( "id" => "40445", "qual" => "4", "name" => "Handschuhe des tapferen Glaubens" ),
	array( "id" => "40448", "qual" => "4", "name" => "Gamaschen des tapferen Glaubens" ),
	array( "id" => "40458", "qual" => "4", "name" => "Gewandung des tapferen Glaubens" ),
	array( "id" => "40454", "qual" => "4", "name" => "Handlappen des tapferen Glaubens" ),
	array( "id" => "40457", "qual" => "4", "name" => "Hose des tapferen Glaubens" ),
	array( "id" => "40423", "qual" => "4", "name" => "Robe des tapferen verseuchten Herzens" ),
	array( "id" => "40420", "qual" => "4", "name" => "Handschuhe des tapferen verseuchten Herzens" ),
	array( "id" => "40422", "qual" => "4", "name" => "Gamaschen des tapferen verseuchten Herzens" ),
	array( "id" => "41951", "qual" => "4", "name" => "Seidene Gewandung des tödlichen Gladiators" ),
	array( "id" => "41970", "qual" => "4", "name" => "Seidene Handschützer des tödlichen Gladiators" ),
	array( "id" => "41958", "qual" => "4", "name" => "Seidene Beinkleider des tödlichen Gladiators" ),
	array( "id" => "41858", "qual" => "4", "name" => "Mondstoffrobe des tödlichen Gladiators" ),
	array( "id" => "41873", "qual" => "4", "name" => "Mondstoffhandschuhe des tödlichen Gladiators" ),
	array( "id" => "41863", "qual" => "4", "name" => "Mondstoffbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41920", "qual" => "4", "name" => "Satinrobe des tödlichen Gladiators" ),
	array( "id" => "41939", "qual" => "4", "name" => "Satinhandschuhe des tödlichen Gladiators" ),
	array( "id" => "41926", "qual" => "4", "name" => "Satingamaschen des tödlichen Gladiators" ),
	array( "id" => "41997", "qual" => "4", "name" => "Teufelsgewebte Gewandung des tödlichen Gladiators" ),
	array( "id" => "42016", "qual" => "4", "name" => "Teufelsgewebte Handschützer des tödlichen Gladiators" ),
	array( "id" => "42004", "qual" => "4", "name" => "Teufelsgewebte Beinkleider des tödlichen Gladiators" ),
	array( "id" => "40469", "qual" => "4", "name" => "Gewand des tapferen Traumwandlers" ),
	array( "id" => "40466", "qual" => "4", "name" => "Handschuhe des tapferen Traumwandlers" ),
	array( "id" => "40468", "qual" => "4", "name" => "Hosen des tapferen Traumwandlers" ),
	array( "id" => "40471", "qual" => "4", "name" => "Gewandung des tapferen Traumwandlers" ),
	array( "id" => "40472", "qual" => "4", "name" => "Handschutz des tapferen Traumwandlers" ),
	array( "id" => "40493", "qual" => "4", "name" => "Beinschützer des tapferen Traumwandlers" ),
	array( "id" => "40463", "qual" => "4", "name" => "Robe des tapferen Traumwandlers" ),
	array( "id" => "40460", "qual" => "4", "name" => "Handschützer des tapferen Traumwandlers" ),
	array( "id" => "40462", "qual" => "4", "name" => "Gamaschen des tapferen Traumwandlers" ),
	array( "id" => "40495", "qual" => "4", "name" => "Brustplatte der tapferen Knochensense" ),
	array( "id" => "40496", "qual" => "4", "name" => "Stulpen der tapferen Knochensense" ),
	array( "id" => "40500", "qual" => "4", "name" => "Beinplatten der tapferen Knochensense" ),
	array( "id" => "41315", "qual" => "4", "name" => "Wyrmbalgrobe des tödlichen Gladiators" ),
	array( "id" => "41292", "qual" => "4", "name" => "Wyrmbalghandschuhe des tödlichen Gladiators" ),
	array( "id" => "41303", "qual" => "4", "name" => "Wyrmbalgbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41660", "qual" => "4", "name" => "Drachenlederrobe des tödlichen Gladiators" ),
	array( "id" => "41772", "qual" => "4", "name" => "Drachenlederhandschuhe des tödlichen Gladiators" ),
	array( "id" => "41666", "qual" => "4", "name" => "Drachenlederbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41309", "qual" => "4", "name" => "Kodobalgrobe des tödlichen Gladiators" ),
	array( "id" => "41286", "qual" => "4", "name" => "Kodobalghandschuhe des tödlichen Gladiators" ),
	array( "id" => "41297", "qual" => "4", "name" => "Kodobalgbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41649", "qual" => "4", "name" => "Ledertunika des tödlichen Gladiators" ),
	array( "id" => "41766", "qual" => "4", "name" => "Lederhandschuhe des tödlichen Gladiators" ),
	array( "id" => "41654", "qual" => "4", "name" => "Lederbeinschützer des tödlichen Gladiators" ),
	array( "id" => "40503", "qual" => "4", "name" => "Tunika des tapferen Gruftpirschers" ),
	array( "id" => "40504", "qual" => "4", "name" => "Handschützer des tapferen Gruftpirschers" ),
	array( "id" => "40506", "qual" => "4", "name" => "Beinschützer des tapferen Gruftpirschers" ),
	array( "id" => "40514", "qual" => "4", "name" => "Halsberge des tapferen Erdspalters" ),
	array( "id" => "40515", "qual" => "4", "name" => "Handschuhe des tapferen Erdspalters" ),
	array( "id" => "40517", "qual" => "4", "name" => "Kilt des tapferen Erdspalters" ),
	array( "id" => "40523", "qual" => "4", "name" => "Brustschutz des tapferen Erdspalters" ),
	array( "id" => "40520", "qual" => "4", "name" => "Griffe des tapferen Erdspalters" ),
	array( "id" => "40522", "qual" => "4", "name" => "Kilt des tapferen Erdspalters" ),
	array( "id" => "40508", "qual" => "4", "name" => "Tunika des tapferen Erdspalters" ),
	array( "id" => "40509", "qual" => "4", "name" => "Handschützer des tapferen Erdspalters" ),
	array( "id" => "40512", "qual" => "4", "name" => "Beinschützer des tapferen Erdspalters" ),
	array( "id" => "41086", "qual" => "4", "name" => "Kettenrüstung des tödlichen Gladiators" ),
	array( "id" => "41142", "qual" => "4", "name" => "Kettenstulpen des tödlichen Gladiators" ),
	array( "id" => "41204", "qual" => "4", "name" => "Kettengamaschen des tödlichen Gladiators" ),
	array( "id" => "40991", "qual" => "4", "name" => "Panzerrüstung des tödlichen Gladiators" ),
	array( "id" => "41006", "qual" => "4", "name" => "Panzerstulpen des tödlichen Gladiators" ),
	array( "id" => "41032", "qual" => "4", "name" => "Panzergamaschen des tödlichen Gladiators" ),
	array( "id" => "41080", "qual" => "4", "name" => "Gekettelte Rüstung des tödlichen Gladiators" ),
	array( "id" => "41136", "qual" => "4", "name" => "Gekettelte Stulpen des tödlichen Gladiators" ),
	array( "id" => "41198", "qual" => "4", "name" => "Gekettelte Gamaschen des tödlichen Gladiators" ),
	array( "id" => "40990", "qual" => "4", "name" => "Ringpanzerrüstung des tödlichen Gladiators" ),
	array( "id" => "41000", "qual" => "4", "name" => "Ringpanzerstulpen des tödlichen Gladiators" ),
	array( "id" => "41026", "qual" => "4", "name" => "Ringpanzergamaschen des tödlichen Gladiators" ),
	array( "id" => "40550", "qual" => "4", "name" => "Kampfplatte des tapferen Geißelerben" ),
	array( "id" => "40552", "qual" => "4", "name" => "Stulpen des tapferen Geißelerben" ),
	array( "id" => "40556", "qual" => "4", "name" => "Beinplatten des tapferen Geißelerben" ),
	array( "id" => "40559", "qual" => "4", "name" => "Brustschutz des tapferen Geißelerben" ),
	array( "id" => "40563", "qual" => "4", "name" => "Handschützer des tapferen Geißelerben" ),
	array( "id" => "40567", "qual" => "4", "name" => "Beinschützer des tapferen Geißelerben" ),
	array( "id" => "40569", "qual" => "4", "name" => "Tunika der tapferen Erlösung" ),
	array( "id" => "40570", "qual" => "4", "name" => "Handschuhe der tapferen Erlösung" ),
	array( "id" => "40572", "qual" => "4", "name" => "Schienbeinschützer der tapferen Erlösung" ),
	array( "id" => "40574", "qual" => "4", "name" => "Brustharnisch der tapferen Erlösung" ),
	array( "id" => "40575", "qual" => "4", "name" => "Stulpen der tapferen Erlösung" ),
	array( "id" => "40577", "qual" => "4", "name" => "Beinplatten der tapferen Erlösung" ),
	array( "id" => "40784", "qual" => "4", "name" => "Schreckensplattenbrustharnisch des tödlichen Gladiators" ),
	array( "id" => "40806", "qual" => "4", "name" => "Schreckensplattenstulpen des tödlichen Gladiators" ),
	array( "id" => "40845", "qual" => "4", "name" => "Schreckensplattenbeinschützer des tödlichen Gladiators" ),
	array( "id" => "40785", "qual" => "4", "name" => "Schuppenharnisch des tödlichen Gladiators" ),
	array( "id" => "40805", "qual" => "4", "name" => "Schuppenstulpen des tödlichen Gladiators" ),
	array( "id" => "40846", "qual" => "4", "name" => "Schuppenbeinschützer des tödlichen Gladiators" ),
	array( "id" => "40905", "qual" => "4", "name" => "Zieratbrustschutz des tödlichen Gladiators" ),
	array( "id" => "40926", "qual" => "4", "name" => "Zierathandschuhe des tödlichen Gladiators" ),
	array( "id" => "40938", "qual" => "4", "name" => "Zieratbeinplatten des tödlichen Gladiators" ),
	array( "id" => "40579", "qual" => "4", "name" => "Brustplatte der tapferen Erlösung" ),
	array( "id" => "40580", "qual" => "4", "name" => "Handschützer der tapferen Erlösung" ),
	array( "id" => "40583", "qual" => "4", "name" => "Beinschützer der tapferen Erlösung" ),
	array( "id" => "40525", "qual" => "4", "name" => "Kampfplatte des tapferen Schreckenspanzers" ),
	array( "id" => "40527", "qual" => "4", "name" => "Stulpen des tapferen Schreckenspanzers" ),
	array( "id" => "40529", "qual" => "4", "name" => "Beinplatten des tapferen Schreckenspanzers" ),
	array( "id" => "40544", "qual" => "4", "name" => "Brustplatte des tapferen Schreckenspanzers" ),
	array( "id" => "40545", "qual" => "4", "name" => "Handschützer des tapferen Schreckenspanzers" ),
	array( "id" => "40547", "qual" => "4", "name" => "Beinschützer des tapferen Schreckenspanzers" ),
	array( "id" => "40753", "qual" => "4", "name" => "Emblem der Ehre" ),
	array( "id" => "43959", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "44083", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "40786", "qual" => "4", "name" => "Plattenbrustharnisch des tödlichen Gladiators" ),
	array( "id" => "40804", "qual" => "4", "name" => "Plattenstulpen des tödlichen Gladiators" ),
	array( "id" => "40844", "qual" => "4", "name" => "Plattenbeinschützer des tödlichen Gladiators" ),
);
?>