<?php
$loot = array(
	array( "id" => "47042", "qual" => "4", "name" => "Stolz der Eredar" ),
	array( "id" => "47051", "qual" => "4", "name" => "Gamaschen der besänftigenden Berührung" ),
	array( "id" => "47000", "qual" => "4", "name" => "Kürass des verhängnisvollen Schicksals" ),
	array( "id" => "47055", "qual" => "4", "name" => "Armschienen der Herbstweide" ),
	array( "id" => "47056", "qual" => "4", "name" => "Armschienen der nebulösen Omen" ),
	array( "id" => "46999", "qual" => "4", "name" => "Blutbadgürtel" ),
	array( "id" => "47057", "qual" => "4", "name" => "Beinplatten des erlöschenden Lichts" ),
	array( "id" => "47052", "qual" => "4", "name" => "Beinschützer der fieberhaften Hingabe" ),
	array( "id" => "46997", "qual" => "4", "name" => "Schienbeinschützer des anbrechenden Morgens" ),
	array( "id" => "47043", "qual" => "4", "name" => "Kraft des Dämonenlords" ),
	array( "id" => "47223", "qual" => "4", "name" => "Ring des Dunkelheilers" ),
	array( "id" => "47041", "qual" => "4", "name" => "Trost der Besiegten" ),
	array( "id" => "47053", "qual" => "4", "name" => "Symbol der Sünde" ),
	array( "id" => "46996", "qual" => "4", "name" => "Löwenkopfschlitzer" ),
	array( "id" => "46994", "qual" => "4", "name" => "Klauenstoß" ),
	array( "id" => "47242", "qual" => "4", "name" => "Trophäe des Kreuzzugs" ),
	array( "id" => "47275", "qual" => "4", "name" => "Stolz des Dämonenlords" ),
	array( "id" => "47274", "qual" => "4", "name" => "Hose der besänftigenden Berührung" ),
	array( "id" => "47270", "qual" => "4", "name" => "Weste des verhängnisvollen Schicksals" ),
	array( "id" => "47277", "qual" => "4", "name" => "Bindungen der Herbstweide" ),
	array( "id" => "47280", "qual" => "4", "name" => "Gelenkbänder der nebulösen Omen" ),
	array( "id" => "47268", "qual" => "4", "name" => "Blutbadgurt" ),
	array( "id" => "47279", "qual" => "4", "name" => "Gamaschen des erlöschenden Lichts" ),
	array( "id" => "47273", "qual" => "4", "name" => "Beinplatten der fieberhaften Hingabe" ),
	array( "id" => "47269", "qual" => "4", "name" => "Sabatons des anbrechenden Morgens" ),
	array( "id" => "47272", "qual" => "4", "name" => "Kraft der Eredar" ),
	array( "id" => "47278", "qual" => "4", "name" => "Kreis des Dunkelheilers" ),
	array( "id" => "47271", "qual" => "4", "name" => "Trost der Gefallenen" ),
	array( "id" => "47276", "qual" => "4", "name" => "Talisman der achtlosen Sünden" ),
	array( "id" => "47266", "qual" => "4", "name" => "Blutfuror" ),
	array( "id" => "47267", "qual" => "4", "name" => "Totenkopfarmbrust" ),
	array( "id" => "47242", "qual" => "4", "name" => "Trophäe des Kreuzzugs" ),
);
?>