<?php
$loot = array(
	array( "id" => "40250", "qual" => "4", "name" => "Gealterter Winterumhang" ),
	array( "id" => "40254", "qual" => "4", "name" => "Umhang der abgewendeten Krise" ),
	array( "id" => "40252", "qual" => "4", "name" => "Umhang der verfinsterten Sonne" ),
	array( "id" => "40253", "qual" => "4", "name" => "Schal der alten Maid" ),
	array( "id" => "40251", "qual" => "4", "name" => "Tuch der Leuchtkraft" ),
	array( "id" => "40234", "qual" => "4", "name" => "Heigans faulige Gewänder" ),
	array( "id" => "40236", "qual" => "4", "name" => "Tragende Echos" ),
	array( "id" => "40238", "qual" => "4", "name" => "Handschuhe des Tanzbären" ),
	array( "id" => "40205", "qual" => "4", "name" => "Stängelhautgürtel" ),
	array( "id" => "40235", "qual" => "4", "name" => "Helm of Pilgrimage" ),
	array( "id" => "40209", "qual" => "4", "name" => "Bindungen des Klapprigen" ),
	array( "id" => "40201", "qual" => "4", "name" => "Gamaschen der gigantischen Schritte" ),
	array( "id" => "40237", "qual" => "4", "name" => "Eruptionsgezeichnete Stiefel" ),
	array( "id" => "40203", "qual" => "4", "name" => "Brustplatte des gepeinigten Zorns" ),
	array( "id" => "40210", "qual" => "4", "name" => "Brustschutz der bitteren Reize" ),
	array( "id" => "40204", "qual" => "4", "name" => "Beinschützer des Apostels" ),
	array( "id" => "40206", "qual" => "4", "name" => "Eisenfedertreter" ),
	array( "id" => "40257", "qual" => "4", "name" => "Kodex des Verteidigers" ),
	array( "id" => "40255", "qual" => "4", "name" => "Letzter Fluch" ),
	array( "id" => "40258", "qual" => "4", "name" => "Talisman der Vorsehung" ),
	array( "id" => "40256", "qual" => "4", "name" => "Grimmiger Tribut" ),
	array( "id" => "40207", "qual" => "4", "name" => "Siegel des Bewusstseins" ),
	array( "id" => "40208", "qual" => "4", "name" => "Biss der Gruftbestie" ),
	array( "id" => "40233", "qual" => "4", "name" => "Stecken des Untodes" ),
);
?>