<?php
$loot = array(
	array( "id" => "46970", "qual" => "4", "name" => "Tuch des ungezähmten Raubtiers" ),
	array( "id" => "46976", "qual" => "4", "name" => "Schal der erfrischenden Winde" ),
	array( "id" => "46992", "qual" => "4", "name" => "Fließende Gewänder des Aufstiegs" ),
	array( "id" => "46972", "qual" => "4", "name" => "Kordel des finsteren Nebels" ),
	array( "id" => "46974", "qual" => "4", "name" => "Gamaschen der gebrochenen Bestie" ),
	array( "id" => "46988", "qual" => "4", "name" => "Stiefel des unablässigen Sturms" ),
	array( "id" => "46960", "qual" => "4", "name" => "Brustplatte der Böswilligkeit" ),
	array( "id" => "46990", "qual" => "4", "name" => "Gürtel des Eisgräbers" ),
	array( "id" => "46962", "qual" => "4", "name" => "Brustplatte der gewaltigen Monstrosität" ),
	array( "id" => "46961", "qual" => "4", "name" => "Knochenschmetternde Armplatten" ),
	array( "id" => "46985", "qual" => "4", "name" => "Stiefel des Mutigen" ),
	array( "id" => "46959", "qual" => "4", "name" => "Band des wilden Temperaments" ),
	array( "id" => "46979", "qual" => "4", "name" => "Klinge von Tarasque" ),
	array( "id" => "46958", "qual" => "4", "name" => "Stahlklingenbrecher" ),
	array( "id" => "46963", "qual" => "4", "name" => "Kristallplattenwall" ),
	array( "id" => "47242", "qual" => "4", "name" => "Trophäe des Kreuzzugs" ),
	array( "id" => "47257", "qual" => "4", "name" => "Umhang des ungezähmten Raubtiers" ),
	array( "id" => "47256", "qual" => "4", "name" => "Tuch der erfrischenden Winde" ),
	array( "id" => "47264", "qual" => "4", "name" => "Fließende Roben des Aufstiegs" ),
	array( "id" => "47258", "qual" => "4", "name" => "Gürtel des finsteren Nebels" ),
	array( "id" => "47259", "qual" => "4", "name" => "Beinwickel der gebrochenen Bestie" ),
	array( "id" => "47262", "qual" => "4", "name" => "Stiefel des harschen Winters" ),
	array( "id" => "47251", "qual" => "4", "name" => "Kürass der Böswilligkeit" ),
	array( "id" => "47265", "qual" => "4", "name" => "Bindungen des Eisgräbers" ),
	array( "id" => "47254", "qual" => "4", "name" => "Halsberge der gewaltigen Monstrosität" ),
	array( "id" => "47253", "qual" => "4", "name" => "Knochenschmetternde Unterarmschienen" ),
	array( "id" => "47263", "qual" => "4", "name" => "Sabatons des Mutigen" ),
	array( "id" => "47252", "qual" => "4", "name" => "Ring des wilden Temperaments" ),
	array( "id" => "47261", "qual" => "4", "name" => "Haken von Tarasque" ),
	array( "id" => "47255", "qual" => "4", "name" => "Stygischer Klingenbrecher" ),
	array( "id" => "47260", "qual" => "4", "name" => "Einsame Barriere" ),
	array( "id" => "47242", "qual" => "4", "name" => "Trophäe des Kreuzzugs" ),
);
?>