<?php
$loot = array(
	array( "id" => "40428", "qual" => "4", "name" => "Titanenausguck" ),
	array( "id" => "40427", "qual" => "4", "name" => "Kreis der arkanen Dämpfe" ),
	array( "id" => "40426", "qual" => "4", "name" => "Siegel des Pakts" ),
	array( "id" => "40433", "qual" => "4", "name" => "Wyrmruhband" ),
	array( "id" => "40430", "qual" => "4", "name" => "Majestätische Drachenstatuette" ),
	array( "id" => "40429", "qual" => "4", "name" => "Scharlachroter Stahl" ),
	array( "id" => "43345", "qual" => "4", "name" => "Tasche aus Drachenhaut" ),
	array( "id" => "43347", "qual" => "4", "name" => "Beutetasche" ),
	array( "id" => "40613", "qual" => "4", "name" => "Handschuhe des verlorenen Eroberers" ),
	array( "id" => "40614", "qual" => "4", "name" => "Handschuhe des verlorenen Beschützers" ),
	array( "id" => "40615", "qual" => "4", "name" => "Handschuhe des verlorenen Bezwingers" ),
	array( "id" => "43988", "qual" => "4", "name" => "Winddichter Umhang" ),
	array( "id" => "43990", "qual" => "4", "name" => "Klingenzerfetzte Tunika" ),
	array( "id" => "43991", "qual" => "4", "name" => "Beinschützer der Ruhe" ),
	array( "id" => "43989", "qual" => "4", "name" => "Erinnerungsgurt" ),
	array( "id" => "43992", "qual" => "4", "name" => "Flugamulett" ),
	array( "id" => "43995", "qual" => "4", "name" => "Verliebte Gugel" ),
	array( "id" => "43996", "qual" => "4", "name" => "Sabatons des Firmaments" ),
	array( "id" => "43994", "qual" => "4", "name" => "Bearbeitete Beinplatten" ),
	array( "id" => "43993", "qual" => "4", "name" => "Großring der Kollision" ),
	array( "id" => "43986", "qual" => "4", "name" => "Reins of the Black Drake" ),
);
?>