<?php
$loot = array(
	array( "id" => "39272", "qual" => "4", "name" => "Tuch der Chirurgie" ),
	array( "id" => "39284", "qual" => "4", "name" => "Miasmamantelung" ),
	array( "id" => "39396", "qual" => "4", "name" => "Robe der Blaumeux" ),
	array( "id" => "39309", "qual" => "4", "name" => "Gamaschen des Ausbilders" ),
	array( "id" => "39237", "qual" => "4", "name" => "Schiftung des wiederaufgenommenen Kampfes" ),
	array( "id" => "39279", "qual" => "4", "name" => "Blasenbedeckter Gürtel des Verfalls" ),
	array( "id" => "39191", "qual" => "4", "name" => "Splitterbesetzte Gamaschen" ),
	array( "id" => "39215", "qual" => "4", "name" => "Stiefel des Gefolgsmanns" ),
	array( "id" => "39294", "qual" => "4", "name" => "Lichtbogenversengter Helm" ),
	array( "id" => "39248", "qual" => "4", "name" => "Tunika des verlorenen Rudels" ),
	array( "id" => "39194", "qual" => "4", "name" => "Verrostete Stachelverbundstulpen" ),
	array( "id" => "39251", "qual" => "4", "name" => "Nekrogenischer Gürtel" ),
	array( "id" => "39379", "qual" => "4", "name" => "Gurt des spektralen Reiters" ),
	array( "id" => "39188", "qual" => "4", "name" => "Ritterlicher Brustharnisch" ),
	array( "id" => "39345", "qual" => "4", "name" => "Gurt des auferstandenen Phantoms" ),
	array( "id" => "39146", "qual" => "4", "name" => "Halsschmuck der Auflösung" ),
	array( "id" => "39232", "qual" => "4", "name" => "Anhänger der verlorenen Begabungen" ),
	array( "id" => "39193", "qual" => "4", "name" => "Band der ignorierten Bitten" ),
	array( "id" => "39388", "qual" => "4", "name" => "Geisterweltglas" ),
	array( "id" => "39344", "qual" => "4", "name" => "Töter der Leblosen" ),
	array( "id" => "39281", "qual" => "4", "name" => "Infektionsabweiser" ),
	array( "id" => "39200", "qual" => "4", "name" => "Trauernde Zauberklinge" ),
	array( "id" => "39394", "qual" => "4", "name" => "Verzauberter Kerzenleuchter" ),
	array( "id" => "40622", "qual" => "4", "name" => "Schiftung des verlorenen Eroberers" ),
	array( "id" => "40623", "qual" => "4", "name" => "Schiftung des verlorenen Beschützers" ),
	array( "id" => "40624", "qual" => "4", "name" => "Schiftung des verlorenen Bezwingers" ),
	array( "id" => "40610", "qual" => "4", "name" => "Brustschutz des verlorenen Eroberers" ),
	array( "id" => "40611", "qual" => "4", "name" => "Brustschutz des verlorenen Beschützers" ),
	array( "id" => "40612", "qual" => "4", "name" => "Brustschutz des verlorenen Bezwingers" ),
	array( "id" => "40619", "qual" => "4", "name" => "Gamaschen des verlorenen Eroberers" ),
	array( "id" => "40620", "qual" => "4", "name" => "Gamaschen des verlorenen Beschützers" ),
	array( "id" => "40621", "qual" => "4", "name" => "Gamaschen des verlorenen Bezwingers" ),
);
?>