<?php
$loot = array(
	array( "id" => "40247", "qual" => "4", "name" => "Gugel der unschuldigen Freuden" ),
	array( "id" => "40289", "qual" => "4", "name" => "Mitfühlende Amicia" ),
	array( "id" => "40602", "qual" => "4", "name" => "Roben der Mutation" ),
	array( "id" => "39733", "qual" => "4", "name" => "Zeichen der Hochachtung" ),
	array( "id" => "40303", "qual" => "4", "name" => "Wickel des Verfolgten" ),
	array( "id" => "40326", "qual" => "4", "name" => "Stiefel der aussichtslosen Wünsche" ),
	array( "id" => "40296", "qual" => "4", "name" => "Bedeckung der Stille" ),
	array( "id" => "39768", "qual" => "4", "name" => "Gugel der Verschiedenen" ),
	array( "id" => "40319", "qual" => "4", "name" => "Brustharnisch des Misstrauens" ),
	array( "id" => "40260", "qual" => "4", "name" => "Gürtel des Gefolterten" ),
	array( "id" => "40205", "qual" => "4", "name" => "Stängelhautgürtel" ),
	array( "id" => "40270", "qual" => "4", "name" => "Stiefel der septischen Wunden" ),
	array( "id" => "40193", "qual" => "4", "name" => "Tunika des maskierten Leidens" ),
	array( "id" => "40209", "qual" => "4", "name" => "Bindungen des Klapprigen" ),
	array( "id" => "40302", "qual" => "4", "name" => "Stulpen des Wohltäters" ),
	array( "id" => "39718", "qual" => "4", "name" => "Leichenskarabäushandschützer" ),
	array( "id" => "40242", "qual" => "4", "name" => "Grotesker Handschutz" ),
	array( "id" => "39760", "qual" => "4", "name" => "Helm des lädierten Stolzes" ),
	array( "id" => "40185", "qual" => "4", "name" => "Schulterschutz der Möglichkeiten" ),
	array( "id" => "40203", "qual" => "4", "name" => "Brustplatte des gepeinigten Zorns" ),
	array( "id" => "40332", "qual" => "4", "name" => "Armschienen der Beihilfe" ),
	array( "id" => "40188", "qual" => "4", "name" => "Stulpen des Ungehorsamen" ),
	array( "id" => "40259", "qual" => "4", "name" => "Taillenschutz der göttlichen Anmut" ),
	array( "id" => "40204", "qual" => "4", "name" => "Beinschützer des Apostels" ),
	array( "id" => "39717", "qual" => "4", "name" => "Unaufhaltsame Sabatons" ),
	array( "id" => "40206", "qual" => "4", "name" => "Eisenfedertreter" ),
	array( "id" => "40297", "qual" => "4", "name" => "Sabatons der Ausdauer" ),
	array( "id" => "40350", "qual" => "4", "name" => "Urne der verlorenen Erinnerungen" ),
	array( "id" => "40191", "qual" => "4", "name" => "Buchband des Glanzes" ),
	array( "id" => "39716", "qual" => "4", "name" => "Schild der Assimilierung" ),
	array( "id" => "40281", "qual" => "4", "name" => "Nebel des Zwielichts" ),
	array( "id" => "39714", "qual" => "4", "name" => "Eingesponnener Tod" ),
	array( "id" => "39730", "qual" => "4", "name" => "Witwenzorn" ),
	array( "id" => "40239", "qual" => "4", "name" => "Die Hand Nerubs" ),
	array( "id" => "40280", "qual" => "4", "name" => "Alptraumserzeuger" ),
	array( "id" => "40343", "qual" => "4", "name" => "Armageddon" ),
	array( "id" => "40265", "qual" => "4", "name" => "Gesang der Pfeile" ),
	array( "id" => "40346", "qual" => "4", "name" => "Letzte Reise" ),
	array( "id" => "40637", "qual" => "4", "name" => "Mantel des verlorenen Eroberers" ),
	array( "id" => "40638", "qual" => "4", "name" => "Mantel des verlorenen Beschützers" ),
	array( "id" => "40639", "qual" => "4", "name" => "Mantel des verlorenen Bezwingers" ),
	array( "id" => "40625", "qual" => "4", "name" => "Brustplatte des verlorenen Eroberers" ),
	array( "id" => "40626", "qual" => "4", "name" => "Brustplatte des verlorenen Beschützers" ),
	array( "id" => "40627", "qual" => "4", "name" => "Brustplatte des verlorenen Bezwingers" ),
	array( "id" => "40634", "qual" => "4", "name" => "Beinplatten des verlorenen Eroberers" ),
	array( "id" => "40635", "qual" => "4", "name" => "Beinplatten des verlorenen Beschützers" ),
	array( "id" => "40636", "qual" => "4", "name" => "Beinplatten des verlorenen Bezwingers" ),
);
?>