<?php
$loot = array(
	array( "id" => "47225", "qual" => "4", "name" => "Maiden's Favor" ),
	array( "id" => "47183", "qual" => "4", "name" => "Strength of the Nerub" ),
	array( "id" => "47203", "qual" => "4", "name" => "Armbands of the Ashen Saint" ),
	array( "id" => "47235", "qual" => "4", "name" => "Gloves of the Lifeless Touch" ),
	array( "id" => "47187", "qual" => "4", "name" => "Leggings of the Deepening Void" ),
	array( "id" => "47194", "qual" => "4", "name" => "Footpads of the Icy Floe" ),
	array( "id" => "47151", "qual" => "4", "name" => "Bracers of Dark Determination" ),
	array( "id" => "47186", "qual" => "4", "name" => "Legwraps of the Awakening" ),
	array( "id" => "47204", "qual" => "4", "name" => "Chestguard of Flowing Elements" ),
	array( "id" => "47152", "qual" => "4", "name" => "Belt of Deathly Dominion" ),
	array( "id" => "47184", "qual" => "4", "name" => "Legguards of the Lurking Threat" ),
	array( "id" => "47234", "qual" => "4", "name" => "Gloves of Bitter Reprisal" ),
	array( "id" => "47195", "qual" => "4", "name" => "Belt of the Forgotten Martyr" ),
	array( "id" => "47150", "qual" => "4", "name" => "Greaves of the 7th Legion" ),
	array( "id" => "47054", "qual" => "4", "name" => "Band of Deplorable Violence" ),
	array( "id" => "47149", "qual" => "4", "name" => "Signet of the Traitor King" ),
	array( "id" => "47182", "qual" => "4", "name" => "Reign of the Unliving" ),
	array( "id" => "47148", "qual" => "4", "name" => "Stormpike Cleaver" ),
	array( "id" => "47193", "qual" => "4", "name" => "Misery's End" ),
	array( "id" => "47233", "qual" => "4", "name" => "Archon Glaive" ),
	array( "id" => "47242", "qual" => "4", "name" => "Trophäe des Kreuzzugs" ),
	array( "id" => "47328", "qual" => "4", "name" => "Maiden's Adoration" ),
	array( "id" => "47320", "qual" => "4", "name" => "Might of the Nerub" ),
	array( "id" => "47324", "qual" => "4", "name" => "Bindings of the Ashen Saint" ),
	array( "id" => "47326", "qual" => "4", "name" => "Handwraps of the Lifeless Touch" ),
	array( "id" => "47317", "qual" => "4", "name" => "Breeches of the Deepening Void" ),
	array( "id" => "47321", "qual" => "4", "name" => "Boots of the Icy Floe" ),
	array( "id" => "47313", "qual" => "4", "name" => "Armbands of Dark Determination" ),
	array( "id" => "47318", "qual" => "4", "name" => "Leggings of the Awakening" ),
	array( "id" => "47325", "qual" => "4", "name" => "Cuirass of Flowing Elements" ),
	array( "id" => "47311", "qual" => "4", "name" => "Waistguard of Deathly Dominion" ),
	array( "id" => "47319", "qual" => "4", "name" => "Leggings of the Lurking Threat" ),
	array( "id" => "47330", "qual" => "4", "name" => "Gauntlets of Bitter Reprisal" ),
	array( "id" => "47323", "qual" => "4", "name" => "Girdle of the Forgotten Martyr" ),
	array( "id" => "47312", "qual" => "4", "name" => "Greaves of the Saronite Citadel" ),
	array( "id" => "47327", "qual" => "4", "name" => "Lurid Manifestation" ),
	array( "id" => "47315", "qual" => "4", "name" => "Band of the Traitor King" ),
	array( "id" => "47316", "qual" => "4", "name" => "Reign of the Dead" ),
	array( "id" => "47314", "qual" => "4", "name" => "Hellscream Slicer" ),
	array( "id" => "47322", "qual" => "4", "name" => "Suffering's End" ),
	array( "id" => "47329", "qual" => "4", "name" => "Hellion Glaive" ),
	array( "id" => "47242", "qual" => "4", "name" => "Trophäe des Kreuzzugs" ),
);
?>