<?php
$loot = array(
	array( "id" => "46132", "qual" => "4", "name" => "Erobererstulpen der Kirin Tor" ),
	array( "id" => "46133", "qual" => "4", "name" => "Eroberergamaschen der Kirin Tor" ),
	array( "id" => "46188", "qual" => "4", "name" => "Weihehandschuhe des Eroberers" ),
	array( "id" => "46195", "qual" => "4", "name" => "Weihegamaschen des Eroberers" ),
	array( "id" => "46163", "qual" => "4", "name" => "Weihehandlappen des Eroberers" ),
	array( "id" => "46170", "qual" => "4", "name" => "Weihehose des Eroberers" ),
	array( "id" => "46135", "qual" => "4", "name" => "Todesbringerhandschuhe des Eroberers" ),
	array( "id" => "46139", "qual" => "4", "name" => "Todesbringergamaschen des Eroberers" ),
	array( "id" => "41971", "qual" => "4", "name" => "Seidenhandschützer des wütenden Gladiators" ),
	array( "id" => "41959", "qual" => "4", "name" => "Satinhosen des wütenden Gladiators" ),
	array( "id" => "41874", "qual" => "4", "name" => "Mondstoffhandschuhe des wütenden Gladiators" ),
	array( "id" => "41864", "qual" => "4", "name" => "Mondstoffgamaschen des wütenden Gladiators" ),
	array( "id" => "41940", "qual" => "4", "name" => "Satinhandschuhe des wütenden Gladiators" ),
	array( "id" => "41927", "qual" => "4", "name" => "Satingamaschen des wütenden Gladiators" ),
	array( "id" => "42017", "qual" => "4", "name" => "Teufelsgewebte Handschützer des wütenden Gladiators" ),
	array( "id" => "42005", "qual" => "4", "name" => "Teufelsgewebte Hosen des wütenden Gladiators" ),
	array( "id" => "46189", "qual" => "4", "name" => "Nachtweisenhandschuhe des Eroberers" ),
	array( "id" => "46192", "qual" => "4", "name" => "Nachtweisenbeinkleider des Eroberers" ),
	array( "id" => "46158", "qual" => "4", "name" => "Nachtweisenhandschutz des Eroberers" ),
	array( "id" => "46160", "qual" => "4", "name" => "Nachtweisenbeinschützer des Eroberers" ),
	array( "id" => "46183", "qual" => "4", "name" => "Nachtweisenhandschützer des Eroberers" ),
	array( "id" => "46185", "qual" => "4", "name" => "Nachtweisengamaschen des Eroberers" ),
	array( "id" => "46124", "qual" => "4", "name" => "Schreckensklingenstulpen des Eroberers" ),
	array( "id" => "46126", "qual" => "4", "name" => "Schreckensklingenbeinplatten des Eroberers" ),
	array( "id" => "41293", "qual" => "4", "name" => "Wyrmbalghandschuhe des wütenden Gladiators" ),
	array( "id" => "41304", "qual" => "4", "name" => "Wyrmbalgbeinschützer des wütenden Gladiators" ),
	array( "id" => "41773", "qual" => "4", "name" => "Drachenlederhandschuhe des wütenden Gladiators" ),
	array( "id" => "41667", "qual" => "4", "name" => "Drachenlederbeinschützer des wütenden Gladiators" ),
	array( "id" => "41287", "qual" => "4", "name" => "Kodobalghandschuhe des wütenden Gladiators" ),
	array( "id" => "41298", "qual" => "4", "name" => "Kodobalgbeinschützer des wütenden Gladiators" ),
	array( "id" => "41767", "qual" => "4", "name" => "Lederhandschuhe des wütenden Gladiators" ),
	array( "id" => "41655", "qual" => "4", "name" => "Lederbeinschützer des wütenden Gladiators" ),
	array( "id" => "46142", "qual" => "4", "name" => "Geißeljägerhandschützer des Eroberers" ),
	array( "id" => "46144", "qual" => "4", "name" => "Geißeljägerbeinschützer des Eroberers" ),
	array( "id" => "46207", "qual" => "4", "name" => "Weltenbrecherhandschuhe des Eroberers" ),
	array( "id" => "46210", "qual" => "4", "name" => "Weltenbrecherkilt des Eroberers" ),
	array( "id" => "46200", "qual" => "4", "name" => "Weltenbrecherhandschutz des Eroberers" ),
	array( "id" => "46208", "qual" => "4", "name" => "Weltenbrecherkriegskilt des Eroberers" ),
	array( "id" => "46199", "qual" => "4", "name" => "Weltenbrecherhandschützer des Eroberers" ),
	array( "id" => "46202", "qual" => "4", "name" => "Weltenbrecherbeinschützer des Eroberers" ),
	array( "id" => "41143", "qual" => "4", "name" => "Kettenstulpen des wütenden Gladiators" ),
	array( "id" => "41205", "qual" => "4", "name" => "Kettengamaschen des wütenden Gladiators" ),
	array( "id" => "41007", "qual" => "4", "name" => "Panzerstulpen des wütenden Gladiators" ),
	array( "id" => "41033", "qual" => "4", "name" => "Panzergamaschen des wütenden Gladiators" ),
	array( "id" => "41137", "qual" => "4", "name" => "Gekettelte Stulpen des wütenden Gladiators" ),
	array( "id" => "41199", "qual" => "4", "name" => "Gekettelte Gamaschen des wütenden Gladiators" ),
	array( "id" => "41001", "qual" => "4", "name" => "Ringpanzerstulpen des wütenden Gladiators" ),
	array( "id" => "41027", "qual" => "4", "name" => "Ringpanzergamaschen des wütenden Gladiators" ),
	array( "id" => "46113", "qual" => "4", "name" => "Dunkle Runenstulpen des Eroberers" ),
	array( "id" => "46116", "qual" => "4", "name" => "Dunkle Runenbeinplatten des Eroberers" ),
	array( "id" => "46119", "qual" => "4", "name" => "Dunkle Runenhandschützer des Eroberers" ),
	array( "id" => "46121", "qual" => "4", "name" => "Dunkle Runenbeinschützer des Eroberers" ),
	array( "id" => "46179", "qual" => "4", "name" => "Aegishandschuhe des Eroberers" ),
	array( "id" => "46181", "qual" => "4", "name" => "Aegisschienbeinschützer des Eroberers" ),
	array( "id" => "46155", "qual" => "4", "name" => "Aegisstulpen des Eroberers" ),
	array( "id" => "46153", "qual" => "4", "name" => "Aegisbeinplatten des Eroberers" ),
	array( "id" => "40809", "qual" => "4", "name" => "Schreckensplattenstulpen des wütenden Gladiators" ),
	array( "id" => "40848", "qual" => "4", "name" => "Schreckensplattenbeinschützer des wütenden Gladiators" ),
	array( "id" => "40927", "qual" => "4", "name" => "Zierathandschuhe des wütenden Gladiators" ),
	array( "id" => "40939", "qual" => "4", "name" => "Zieratbeinplatten des wütenden Gladiators" ),
	array( "id" => "40808", "qual" => "4", "name" => "Schuppenstulpen des wütenden Gladiators" ),
	array( "id" => "40849", "qual" => "4", "name" => "Schuppenbeinschützer des wütenden Gladiators" ),
	array( "id" => "46174", "qual" => "4", "name" => "Aegishandschützer des Eroberers" ),
	array( "id" => "46176", "qual" => "4", "name" => "Aegisbeinschützer des Eroberers" ),
	array( "id" => "46148", "qual" => "4", "name" => "Blockadenbrecherstulpen des Eroberers" ),
	array( "id" => "46150", "qual" => "4", "name" => "Blockadenbrecherbeinplatten des Eroberers" ),
	array( "id" => "46164", "qual" => "4", "name" => "Blockadenbrecherhandschützer des Eroberers" ),
	array( "id" => "46169", "qual" => "4", "name" => "Blockadenbrecherbeinschützer des Eroberers" ),
	array( "id" => "40807", "qual" => "4", "name" => "Plattenstulpen des wütenden Gladiators" ),
	array( "id" => "40847", "qual" => "4", "name" => "Plattenbeinschützer des wütenden Gladiators" ),
	array( "id" => "41909", "qual" => "4", "name" => "Vorherrschaftsmanschetten des wütenden Gladiators" ),
	array( "id" => "41898", "qual" => "4", "name" => "Vorherrschaftskordel des wütenden Gladiators" ),
	array( "id" => "41903", "qual" => "4", "name" => "Vorherrschaftsschuhe des wütenden Gladiators" ),
	array( "id" => "41893", "qual" => "4", "name" => "Errettermanschetten des wütenden Gladiators" ),
	array( "id" => "41881", "qual" => "4", "name" => "Erretterkordel des wütenden Gladiators" ),
	array( "id" => "41885", "qual" => "4", "name" => "Erretterschuhe des wütenden Gladiators" ),
	array( "id" => "41640", "qual" => "4", "name" => "Vorherrschaftsarmwickel des wütenden Gladiators" ),
	array( "id" => "41630", "qual" => "4", "name" => "Vorherrschaftsgürtel des wütenden Gladiators" ),
	array( "id" => "41635", "qual" => "4", "name" => "Vorherrschaftsstiefel des wütenden Gladiators" ),
	array( "id" => "41625", "qual" => "4", "name" => "Erretterarmwickel des wütenden Gladiators" ),
	array( "id" => "41617", "qual" => "4", "name" => "Errettergürtel des wütenden Gladiators" ),
	array( "id" => "41621", "qual" => "4", "name" => "Erretterstiefel des wütenden Gladiators" ),
	array( "id" => "41840", "qual" => "4", "name" => "Triumphale Armwickel des wütenden Gladiators" ),
	array( "id" => "41832", "qual" => "4", "name" => "Triumphaler Gürtel des wütenden Gladiators" ),
	array( "id" => "41836", "qual" => "4", "name" => "Triumphale Stiefel des wütenden Gladiators" ),
	array( "id" => "41065", "qual" => "4", "name" => "Vorherrschaftshandgelenksschutz des wütenden Gladiators" ),
	array( "id" => "41070", "qual" => "4", "name" => "Vorherrschaftstaillenschutz des wütenden Gladiators" ),
	array( "id" => "41075", "qual" => "4", "name" => "Vorherrschaftssabatons des wütenden Gladiators" ),
	array( "id" => "41060", "qual" => "4", "name" => "Erretterhandgelenksschutz des wütenden Gladiators" ),
	array( "id" => "41051", "qual" => "4", "name" => "Errettertaillenschutz des wütenden Gladiators" ),
	array( "id" => "41055", "qual" => "4", "name" => "Errettersabatons des wütenden Gladiators" ),
	array( "id" => "41225", "qual" => "4", "name" => "Triumphale Handgelenksschützer des wütenden Gladiators" ),
	array( "id" => "41235", "qual" => "4", "name" => "Triumphaler Taillenschutz des wütenden Gladiators" ),
	array( "id" => "41230", "qual" => "4", "name" => "Triumphale Sabatons des wütenden Gladiators" ),
	array( "id" => "40983", "qual" => "4", "name" => "Erretterarmschienen des wütenden Gladiators" ),
	array( "id" => "40976", "qual" => "4", "name" => "Errettergurt des wütenden Gladiators" ),
	array( "id" => "40977", "qual" => "4", "name" => "Erretterschienbeinschützer des wütenden Gladiators" ),
	array( "id" => "40889", "qual" => "4", "name" => "Triumphale Armschienen des wütenden Gladiators" ),
	array( "id" => "40881", "qual" => "4", "name" => "Triumphaler Gurt des wütenden Gladiators" ),
	array( "id" => "40882", "qual" => "4", "name" => "Triumphale Schienbeinschützer des wütenden Gladiators" ),
	array( "id" => "42071", "qual" => "4", "name" => "Vormachtsumhang des wütenden Gladiators" ),
	array( "id" => "42073", "qual" => "4", "name" => "Erlösungsumhang des wütenden Gladiators" ),
	array( "id" => "42069", "qual" => "4", "name" => "Vorherrschaftsumhang des wütenden Gladiators" ),
	array( "id" => "42072", "qual" => "4", "name" => "Erretterumhang des wütenden Gladiators" ),
	array( "id" => "42070", "qual" => "4", "name" => "Unterwerfungsumhang des wütenden Gladiators" ),
	array( "id" => "42074", "qual" => "4", "name" => "Triumphaler Umhang des wütenden Gladiators" ),
	array( "id" => "42075", "qual" => "4", "name" => "Siegesumhang des wütenden Gladiators" ),
	array( "id" => "45624", "qual" => "4", "name" => "Emblem der Eroberung" ),
	array( "id" => "43959", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "44083", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "42037", "qual" => "4", "name" => "Vormachtsanhänger des wütenden Gladiators" ),
	array( "id" => "42039", "qual" => "4", "name" => "Erlösungsanhäger des wütenden Gladiators" ),
	array( "id" => "42036", "qual" => "4", "name" => "Vorherrschaftsanhänger des wütenden Gladiators" ),
	array( "id" => "42040", "qual" => "4", "name" => "Erretteranhänger des wütenden Gladiators" ),
	array( "id" => "42038", "qual" => "4", "name" => "Unterwerfungsanhänger des wütenden Gladiators" ),
	array( "id" => "46373", "qual" => "4", "name" => "Zerschlagungsanhänger des wütenden Gladiators" ),
	array( "id" => "42034", "qual" => "4", "name" => "Triumphaler Anhänger des wütenden Gladiators" ),
	array( "id" => "42035", "qual" => "4", "name" => "Siegesanhänger des wütenden Gladiators" ),
	array( "id" => "42116", "qual" => "4", "name" => "Vorherrschaftsband des wütenden Gladiators" ),
	array( "id" => "42117", "qual" => "4", "name" => "Triumphales Band des wütenden Gladiators" ),
);

?>