<?php
$loot = array(
	array( "id" => "47745", "qual" => "4", "name" => "Gloves of Looming Shadow" ),
	array( "id" => "49231", "qual" => "4", "name" => "Boots of the Grieving Soul" ),
	array( "id" => "47746", "qual" => "4", "name" => "Helm of the Snowy Grotto" ),
	array( "id" => "47739", "qual" => "4", "name" => "Rüstung der unbeständigen Schatten" ),
	array( "id" => "47744", "qual" => "4", "name" => "Handschuhe des Azurpropheten" ),
	array( "id" => "47738", "qual" => "4", "name" => "Sabatons des beständigen Vortex'" ),
	array( "id" => "47747", "qual" => "4", "name" => "Nachtbanns Anhänger" ),
	array( "id" => "47700", "qual" => "4", "name" => "Schleife der Zwillingsval'kyr" ),
	array( "id" => "47742", "qual" => "4", "name" => "Kelch von Benedictus" ),
	array( "id" => "47736", "qual" => "4", "name" => "Icefall Blade" ),
	array( "id" => "47737", "qual" => "4", "name" => "Abrechnnung" ),
	array( "id" => "47743", "qual" => "4", "name" => "Erleuchtung" ),
	array( "id" => "47741", "qual" => "4", "name" => "Baelgun's Heavy Crossbow" ),
	array( "id" => "47740", "qual" => "4", "name" => "The Diplomat" ),
	array( "id" => "47889", "qual" => "4", "name" => "Bedrohliche Schattenwickel" ),
	array( "id" => "49232", "qual" => "4", "name" => "Sandalen der trauernden Seele" ),
	array( "id" => "47891", "qual" => "4", "name" => "Helm of the High Mesa" ),
	array( "id" => "47887", "qual" => "4", "name" => "Vest of Shifting Shadows" ),
	array( "id" => "47893", "qual" => "4", "name" => "Sen'jin Ritualist Gloves" ),
	array( "id" => "47885", "qual" => "4", "name" => "Schienbeinschützer des beständigen Vortex'" ),
	array( "id" => "47890", "qual" => "4", "name" => "Nachtbanns Amulett" ),
	array( "id" => "47888", "qual" => "4", "name" => "Band der Zwillingsval'kyr" ),
	array( "id" => "47913", "qual" => "4", "name" => "Lichtbanns Fokus" ),
	array( "id" => "47886", "qual" => "4", "name" => "Nemesis Blade" ),
	array( "id" => "47884", "qual" => "4", "name" => "Schneide der Agonie" ),
	array( "id" => "47892", "qual" => "4", "name" => "Illumination" ),
	array( "id" => "47883", "qual" => "4", "name" => "Widebarrel Flintlock" ),
);
?>