<?php
$loot = array(
	array( "id" => "40562", "qual" => "4", "name" => "Kapuze der Rationalität" ),
	array( "id" => "40555", "qual" => "4", "name" => "Mantelung der Dissemination" ),
	array( "id" => "40194", "qual" => "4", "name" => "Schneedeckenrobe" ),
	array( "id" => "40561", "qual" => "4", "name" => "Leine der rücksichtslosen Magie" ),
	array( "id" => "40560", "qual" => "4", "name" => "Gamaschen des übermütigen Zauberwirkers" ),
	array( "id" => "40558", "qual" => "4", "name" => "Arkanische Trampler" ),
	array( "id" => "40594", "qual" => "4", "name" => "Schiftung der Katatonie" ),
	array( "id" => "40539", "qual" => "4", "name" => "Brustharnisch des Eremiten" ),
	array( "id" => "40541", "qual" => "4", "name" => "Bereifte Handschuhe der Schlagfertigkeit" ),
	array( "id" => "40566", "qual" => "4", "name" => "Dünne Geduldsfäden" ),
	array( "id" => "40543", "qual" => "4", "name" => "Helm des Blauen Aspekts" ),
	array( "id" => "40588", "qual" => "4", "name" => "Tunika des Artefaktwächters" ),
	array( "id" => "40564", "qual" => "4", "name" => "Handschuhe des Winterspektakels" ),
	array( "id" => "40549", "qual" => "4", "name" => "Stiefel des erneuerten Schwarms" ),
	array( "id" => "40590", "qual" => "4", "name" => "Schulterstücke des erhöhten Horts" ),
	array( "id" => "40589", "qual" => "4", "name" => "Beinplatten der Souveränität" ),
	array( "id" => "40592", "qual" => "4", "name" => "Stiefel der heilenden Energien" ),
	array( "id" => "40591", "qual" => "4", "name" => "Sabatons der Melancholie" ),
	array( "id" => "40532", "qual" => "4", "name" => "Lebendige Eiskristalle" ),
	array( "id" => "40531", "qual" => "4", "name" => "Mal des Norgannon" ),
	array( "id" => "43952", "qual" => "4", "name" => "Zügel des Azurdrachen" ),
	array( "id" => "44577", "qual" => "4", "name" => "Heroischer Schlüssel der fokussierenden Iris" ),
	array( "id" => "44650", "qual" => "1", "name" => "Herz der Magie" ),
);
?>