<?php
$loot = array(
	array( "id" => "49307", "qual" => "4", "name" => "Wallendes Saphirontuch" ),
	array( "id" => "49316", "qual" => "4", "name" => "Reif der Erhabenheit" ),
	array( "id" => "49317", "qual" => "4", "name" => "Kronenreif der Erhabenheit" ),
	array( "id" => "49315", "qual" => "4", "name" => "Schädelbedeckung der Nemesis" ),
	array( "id" => "49318", "qual" => "4", "name" => "Kapuze des Netherwinds" ),
	array( "id" => "49322", "qual" => "4", "name" => "Blutfangmaske" ),
	array( "id" => "49327", "qual" => "4", "name" => "Sturmgrimms Geweih" ),
	array( "id" => "49328", "qual" => "4", "name" => "Sturmgrimms Helm" ),
	array( "id" => "49326", "qual" => "4", "name" => "Sturmgrimms Kapuze" ),
	array( "id" => "49331", "qual" => "4", "name" => "Helmkappe der zehn Stürme" ),
	array( "id" => "49330", "qual" => "4", "name" => "Gugel der zehn Stürme" ),
	array( "id" => "49329", "qual" => "4", "name" => "Blick der zehn Stürme" ),
	array( "id" => "49319", "qual" => "4", "name" => "Visier des Drachenjägers" ),
	array( "id" => "49320", "qual" => "4", "name" => "Gesichtsschutz des Zorns" ),
	array( "id" => "49321", "qual" => "4", "name" => "Großhelm des Zorns" ),
	array( "id" => "49333", "qual" => "4", "name" => "Frostgeschmiedeter Helm" ),
	array( "id" => "49332", "qual" => "4", "name" => "Frostgeschmiedeter Ringhelm" ),
	array( "id" => "49323", "qual" => "4", "name" => "Bedeckung des Richturteils" ),
	array( "id" => "49325", "qual" => "4", "name" => "Helm des Richturteils" ),
	array( "id" => "49324", "qual" => "4", "name" => "Helm des Richtspruchs" ),
	array( "id" => "49306", "qual" => "4", "name" => "Eskhandars Halsreif" ),
	array( "id" => "49309", "qual" => "4", "name" => "Runenverzierter Ring der Bindung" ),
	array( "id" => "49463", "qual" => "4", "name" => "Geläuterter Splitter der Flamme" ),
	array( "id" => "49310", "qual" => "4", "name" => "Geläuterter Splitter der Schuppe" ),
	array( "id" => "49308", "qual" => "4", "name" => "Zauberfoliant des antiken Grundsteins" ),
	array( "id" => "49304", "qual" => "4", "name" => "Geschärfter Fangzahn der Mystiker" ),
	array( "id" => "49437", "qual" => "4", "name" => "Verrosteter Räuderipper" ),
	array( "id" => "49298", "qual" => "4", "name" => "Glitzernde Magierklinge des Azurlieds" ),
	array( "id" => "49303", "qual" => "4", "name" => "Schimmerndes Quel'Serrar" ),
	array( "id" => "49296", "qual" => "4", "name" => "Angesengter Vis'kag der Blutvergießer" ),
	array( "id" => "49299", "qual" => "4", "name" => "Wuchtige scharfkantige Obsidianklinge" ),
	array( "id" => "49297", "qual" => "4", "name" => "Machterfüllter Todesbringer" ),
	array( "id" => "49302", "qual" => "4", "name" => "Zurückeroberter Schattenschlag" ),
	array( "id" => "49301", "qual" => "4", "name" => "Zurückeroberter Donnerschlag" ),
	array( "id" => "49305", "qual" => "4", "name" => "Kurzläufiger Blasterwerfer" ),
	array( "id" => "49644", "qual" => "4", "name" => "Kopf von Onyxia" ),
	array( "id" => "49485", "qual" => "4", "name" => "Funkelnder Zahn Onyxias" ),
	array( "id" => "49486", "qual" => "4", "name" => "Poliertes Drachentötersignet" ),
	array( "id" => "49487", "qual" => "4", "name" => "Geläuterter Talisman mit Onyxiablut" ),
	array( "id" => "49295", "qual" => "4", "name" => "Vergrößerter Rucksack aus Onyxias Haut" ),
	array( "id" => "49294", "qual" => "4", "name" => "Aschgrauer Sack voller Edelsteine" ),
	array( "id" => "49636", "qual" => "4", "name" => "Zügel des Drachen von Onyxia" ),
);

?>