<?php
if($this->get_faction() == 'alliance'){
$loot = array(
	array( "id" => "47752", "qual" => "4", "name" => "Khadgars Stulpen der Eroberung" ),
	array( "id" => "47750", "qual" => "4", "name" => "Khadgars Gamaschen der Eroberung" ),
	array( "id" => "47982", "qual" => "4", "name" => "Velens Handschuhe der Eroberung" ),
	array( "id" => "47980", "qual" => "4", "name" => "Velens Gamaschen der Eroberung" ),
	array( "id" => "48072", "qual" => "4", "name" => "Velens Handwickel der Eroberung" ),
	array( "id" => "48074", "qual" => "4", "name" => "Velens Hosen der Eroberung" ),
	array( "id" => "47783", "qual" => "4", "name" => "Kel'Thuzads Stulpen der Eroberung" ),
	array( "id" => "47785", "qual" => "4", "name" => "Kel'Thuzads Gamaschen der Eroberung" ),
	array( "id" => "41971", "qual" => "4", "name" => "Seidenhandschützer des wütenden Gladiators" ),
	array( "id" => "41959", "qual" => "4", "name" => "Satinhosen des wütenden Gladiators" ),
	array( "id" => "41874", "qual" => "4", "name" => "Mondstoffhandschuhe des wütenden Gladiators" ),
	array( "id" => "41864", "qual" => "4", "name" => "Mondstoffgamaschen des wütenden Gladiators" ),
	array( "id" => "41940", "qual" => "4", "name" => "Satinhandschuhe des wütenden Gladiators" ),
	array( "id" => "41927", "qual" => "4", "name" => "Satingamaschen des wütenden Gladiators" ),
	array( "id" => "42017", "qual" => "4", "name" => "Teufelsgewebte Handschützer des wütenden Gladiators" ),
	array( "id" => "42005", "qual" => "4", "name" => "Teufelsgewebte Hosen des wütenden Gladiators" ),
	array( "id" => "48162", "qual" => "4", "name" => "Malfurions Handschuhe der Eroberung" ),
	array( "id" => "48160", "qual" => "4", "name" => "Malfurions Beinkleider der Eroberung" ),
	array( "id" => "48213", "qual" => "4", "name" => "Malfurions Handschutz der Eroberung" ),
	array( "id" => "48215", "qual" => "4", "name" => "Malfurions Beinschützer der Eroberung" ),
	array( "id" => "48132", "qual" => "4", "name" => "Malfurions Handschützer der Eroberung" ),
	array( "id" => "48130", "qual" => "4", "name" => "Malfurions Gamaschen der Eroberung" ),
	array( "id" => "48222", "qual" => "4", "name" => "Van Cleefs Stulpen der Eroberung" ),
	array( "id" => "48220", "qual" => "4", "name" => "Van Cleefs Beinplatten der Eroberung" ),
	array( "id" => "41293", "qual" => "4", "name" => "Wyrmbalghandschuhe des wütenden Gladiators" ),
	array( "id" => "41304", "qual" => "4", "name" => "Wyrmbalgbeinschützer des wütenden Gladiators" ),
	array( "id" => "41773", "qual" => "4", "name" => "Drachenlederhandschuhe des wütenden Gladiators" ),
	array( "id" => "41667", "qual" => "4", "name" => "Drachenlederbeinschützer des wütenden Gladiators" ),
	array( "id" => "41287", "qual" => "4", "name" => "Kodobalghandschuhe des wütenden Gladiators" ),
	array( "id" => "41298", "qual" => "4", "name" => "Kodobalgbeinschützer des wütenden Gladiators" ),
	array( "id" => "41767", "qual" => "4", "name" => "Lederhandschuhe des wütenden Gladiators" ),
	array( "id" => "41655", "qual" => "4", "name" => "Lederbeinschützer des wütenden Gladiators" ),
	array( "id" => "48254", "qual" => "4", "name" => "Windläufers Handschützer der Eroberung" ),
	array( "id" => "48252", "qual" => "4", "name" => "Windläufers Beinschützer der Eroberung" ),
	array( "id" => "48312", "qual" => "4", "name" => "Nobundos Handschuhe der Eroberung" ),
	array( "id" => "48314", "qual" => "4", "name" => "Nobundos Kilt der Eroberung" ),
	array( "id" => "48342", "qual" => "4", "name" => "Nobundos Griff der Eroberung" ),
	array( "id" => "48344", "qual" => "4", "name" => "Nobundos Kriegskilt der Eroberung" ),
	array( "id" => "48284", "qual" => "4", "name" => "Nobundos Handschützer der Eroberung" ),
	array( "id" => "48282", "qual" => "4", "name" => "Nobundos Beinschützer der Eroberung" ),
	array( "id" => "41143", "qual" => "4", "name" => "Kettenstulpen des wütenden Gladiators" ),
	array( "id" => "41205", "qual" => "4", "name" => "Kettengamaschen des wütenden Gladiators" ),
	array( "id" => "41007", "qual" => "4", "name" => "Panzerstulpen des wütenden Gladiators" ),
	array( "id" => "41033", "qual" => "4", "name" => "Panzergamaschen des wütenden Gladiators" ),
	array( "id" => "41137", "qual" => "4", "name" => "Gekettelte Stulpen des wütenden Gladiators" ),
	array( "id" => "41199", "qual" => "4", "name" => "Gekettelte Gamaschen des wütenden Gladiators" ),
	array( "id" => "41001", "qual" => "4", "name" => "Ringpanzerstulpen des wütenden Gladiators" ),
	array( "id" => "41027", "qual" => "4", "name" => "Ringpanzergamaschen des wütenden Gladiators" ),
	array( "id" => "48480", "qual" => "4", "name" => "Thassarians Stulpen der Eroberung" ),
	array( "id" => "48476", "qual" => "4", "name" => "Thassarians Beinplatten der Eroberung" ),
	array( "id" => "48537", "qual" => "4", "name" => "Thassarians Handschützer der Eroberung" ),
	array( "id" => "48533", "qual" => "4", "name" => "Thassarians Beinschützer der Eroberung" ),
	array( "id" => "48574", "qual" => "4", "name" => "Turalyons Handschuhe der Eroberung" ),
	array( "id" => "48568", "qual" => "4", "name" => "Turalyons Schienbeinschützer der Eroberung" ),
	array( "id" => "48603", "qual" => "4", "name" => "Turalyons Stulpen der Eroberung" ),
	array( "id" => "48605", "qual" => "4", "name" => "Turalyons Beinplatten der Eroberung" ),
	array( "id" => "40809", "qual" => "4", "name" => "Schreckensplattenstulpen des wütenden Gladiators" ),
	array( "id" => "40848", "qual" => "4", "name" => "Schreckensplattenbeinschützer des wütenden Gladiators" ),
	array( "id" => "40927", "qual" => "4", "name" => "Zierathandschuhe des wütenden Gladiators" ),
	array( "id" => "40939", "qual" => "4", "name" => "Zieratbeinplatten des wütenden Gladiators" ),
	array( "id" => "40808", "qual" => "4", "name" => "Schuppenstulpen des wütenden Gladiators" ),
	array( "id" => "40849", "qual" => "4", "name" => "Schuppenbeinschützer des wütenden Gladiators" ),
	array( "id" => "48633", "qual" => "4", "name" => "Turalyons Handschützer der Eroberung" ),
	array( "id" => "48635", "qual" => "4", "name" => "Turalyons Beinschützer der Eroberung" ),
	array( "id" => "48375", "qual" => "4", "name" => "Wrynns Stulpen der Eroberung" ),
	array( "id" => "48373", "qual" => "4", "name" => "Wrynns Beinplatten der Eroberung" ),
	array( "id" => "48449", "qual" => "4", "name" => "Wrynns Handschützer der Eroberung" ),
	array( "id" => "48445", "qual" => "4", "name" => "Wrynns Beinschützer der Eroberung" ),
	array( "id" => "40807", "qual" => "4", "name" => "Plattenstulpen des wütenden Gladiators" ),
	array( "id" => "40847", "qual" => "4", "name" => "Plattenbeinschützer des wütenden Gladiators" ),
	array( "id" => "41909", "qual" => "4", "name" => "Vorherrschaftsmanschetten des wütenden Gladiators" ),
	array( "id" => "41898", "qual" => "4", "name" => "Vorherrschaftskordel des wütenden Gladiators" ),
	array( "id" => "41903", "qual" => "4", "name" => "Vorherrschaftsschuhe des wütenden Gladiators" ),
	array( "id" => "41893", "qual" => "4", "name" => "Errettermanschetten des wütenden Gladiators" ),
	array( "id" => "41881", "qual" => "4", "name" => "Erretterkordel des wütenden Gladiators" ),
	array( "id" => "41885", "qual" => "4", "name" => "Erretterschuhe des wütenden Gladiators" ),
	array( "id" => "41640", "qual" => "4", "name" => "Vorherrschaftsarmwickel des wütenden Gladiators" ),
	array( "id" => "41630", "qual" => "4", "name" => "Vorherrschaftsgürtel des wütenden Gladiators" ),
	array( "id" => "41635", "qual" => "4", "name" => "Vorherrschaftsstiefel des wütenden Gladiators" ),
	array( "id" => "41625", "qual" => "4", "name" => "Erretterarmwickel des wütenden Gladiators" ),
	array( "id" => "41617", "qual" => "4", "name" => "Errettergürtel des wütenden Gladiators" ),
	array( "id" => "41621", "qual" => "4", "name" => "Erretterstiefel des wütenden Gladiators" ),
	array( "id" => "41840", "qual" => "4", "name" => "Triumphale Armwickel des wütenden Gladiators" ),
	array( "id" => "41832", "qual" => "4", "name" => "Triumphaler Gürtel des wütenden Gladiators" ),
	array( "id" => "41836", "qual" => "4", "name" => "Triumphale Stiefel des wütenden Gladiators" ),
	array( "id" => "41065", "qual" => "4", "name" => "Vorherrschaftshandgelenksschutz des wütenden Gladiators" ),
	array( "id" => "41070", "qual" => "4", "name" => "Vorherrschaftstaillenschutz des wütenden Gladiators" ),
	array( "id" => "41075", "qual" => "4", "name" => "Vorherrschaftssabatons des wütenden Gladiators" ),
	array( "id" => "41060", "qual" => "4", "name" => "Erretterhandgelenksschutz des wütenden Gladiators" ),
	array( "id" => "41051", "qual" => "4", "name" => "Errettertaillenschutz des wütenden Gladiators" ),
	array( "id" => "41055", "qual" => "4", "name" => "Errettersabatons des wütenden Gladiators" ),
	array( "id" => "41225", "qual" => "4", "name" => "Triumphale Handgelenksschützer des wütenden Gladiators" ),
	array( "id" => "41235", "qual" => "4", "name" => "Triumphaler Taillenschutz des wütenden Gladiators" ),
	array( "id" => "41230", "qual" => "4", "name" => "Triumphale Sabatons des wütenden Gladiators" ),
	array( "id" => "40983", "qual" => "4", "name" => "Erretterarmschienen des wütenden Gladiators" ),
	array( "id" => "40976", "qual" => "4", "name" => "Errettergurt des wütenden Gladiators" ),
	array( "id" => "40977", "qual" => "4", "name" => "Erretterschienbeinschützer des wütenden Gladiators" ),
	array( "id" => "40889", "qual" => "4", "name" => "Triumphale Armschienen des wütenden Gladiators" ),
	array( "id" => "40881", "qual" => "4", "name" => "Triumphaler Gurt des wütenden Gladiators" ),
	array( "id" => "40882", "qual" => "4", "name" => "Triumphale Schienbeinschützer des wütenden Gladiators" ),
	array( "id" => "42071", "qual" => "4", "name" => "Vormachtsumhang des wütenden Gladiators" ),
	array( "id" => "42073", "qual" => "4", "name" => "Erlösungsumhang des wütenden Gladiators" ),
	array( "id" => "42069", "qual" => "4", "name" => "Vorherrschaftsumhang des wütenden Gladiators" ),
	array( "id" => "42072", "qual" => "4", "name" => "Erretterumhang des wütenden Gladiators" ),
	array( "id" => "42070", "qual" => "4", "name" => "Unterwerfungsumhang des wütenden Gladiators" ),
	array( "id" => "42074", "qual" => "4", "name" => "Triumphaler Umhang des wütenden Gladiators" ),
	array( "id" => "42075", "qual" => "4", "name" => "Siegesumhang des wütenden Gladiators" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem des Triumphs" ),
	array( "id" => "43959", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "44083", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "42037", "qual" => "4", "name" => "Vormachtsanhänger des wütenden Gladiators" ),
	array( "id" => "42039", "qual" => "4", "name" => "Erlösungsanhäger des wütenden Gladiators" ),
	array( "id" => "42036", "qual" => "4", "name" => "Vorherrschaftsanhänger des wütenden Gladiators" ),
	array( "id" => "42040", "qual" => "4", "name" => "Erretteranhänger des wütenden Gladiators" ),
	array( "id" => "42038", "qual" => "4", "name" => "Unterwerfungsanhänger des wütenden Gladiators" ),
	array( "id" => "46373", "qual" => "4", "name" => "Zerschlagungsanhänger des wütenden Gladiators" ),
	array( "id" => "42034", "qual" => "4", "name" => "Triumphaler Anhänger des wütenden Gladiators" ),
	array( "id" => "42035", "qual" => "4", "name" => "Siegesanhänger des wütenden Gladiators" ),
	array( "id" => "42116", "qual" => "4", "name" => "Vorherrschaftsband des wütenden Gladiators" ),
	array( "id" => "42117", "qual" => "4", "name" => "Triumphales Band des wütenden Gladiators" ),
);
}else{
$loot = array(
	array( "id" => "47773", "qual" => "4", "name" => "Sonnenwanderers Stulpen der Eroberung" ),
	array( "id" => "47775", "qual" => "4", "name" => "Sonnenwanderers Gamaschen der Eroberung" ),
	array( "id" => "48067", "qual" => "4", "name" => "Zabras Handschuhe der Eroberung" ),
	array( "id" => "48069", "qual" => "4", "name" => "Zabras Gamaschen der Eroberung" ),
	array( "id" => "48097", "qual" => "4", "name" => "Zabras Handwickel der Eroberung" ),
	array( "id" => "48099", "qual" => "4", "name" => "Zabras Hosen der Eroberung" ),
	array( "id" => "47802", "qual" => "4", "name" => "Gul'dans Stulpen der Eroberung" ),
	array( "id" => "47800", "qual" => "4", "name" => "Gul'dans Gamaschen der Eroberung" ),
	array( "id" => "41971", "qual" => "4", "name" => "Seidenhandschützer des wütenden Gladiators" ),
	array( "id" => "41959", "qual" => "4", "name" => "Satinhosen des wütenden Gladiators" ),
	array( "id" => "41874", "qual" => "4", "name" => "Mondstoffhandschuhe des wütenden Gladiators" ),
	array( "id" => "41864", "qual" => "4", "name" => "Mondstoffgamaschen des wütenden Gladiators" ),
	array( "id" => "41940", "qual" => "4", "name" => "Satinhandschuhe des wütenden Gladiators" ),
	array( "id" => "41927", "qual" => "4", "name" => "Satingamaschen des wütenden Gladiators" ),
	array( "id" => "42017", "qual" => "4", "name" => "Teufelsgewebte Handschützer des wütenden Gladiators" ),
	array( "id" => "42005", "qual" => "4", "name" => "Teufelsgewebte Hosen des wütenden Gladiators" ),
	array( "id" => "48183", "qual" => "4", "name" => "Runentotems Handschuhe der Eroberung" ),
	array( "id" => "48185", "qual" => "4", "name" => "Runentotems Beinkleider der Eroberung" ),
	array( "id" => "48192", "qual" => "4", "name" => "Runentotems Handschutz der Eroberung" ),
	array( "id" => "48190", "qual" => "4", "name" => "Runentotems Beinschützer der Eroberung" ),
	array( "id" => "48153", "qual" => "4", "name" => "Runentotems Handschützer der Eroberung" ),
	array( "id" => "48155", "qual" => "4", "name" => "Runentotems Gamaschen der Eroberung" ),
	array( "id" => "48244", "qual" => "4", "name" => "Garonas Stulpen der Eroberung" ),
	array( "id" => "48246", "qual" => "4", "name" => "Garonas Beinplatten der Eroberung" ),
	array( "id" => "41293", "qual" => "4", "name" => "Wyrmbalghandschuhe des wütenden Gladiators" ),
	array( "id" => "41304", "qual" => "4", "name" => "Wyrmbalgbeinschützer des wütenden Gladiators" ),
	array( "id" => "41773", "qual" => "4", "name" => "Drachenlederhandschuhe des wütenden Gladiators" ),
	array( "id" => "41667", "qual" => "4", "name" => "Drachenlederbeinschützer des wütenden Gladiators" ),
	array( "id" => "41287", "qual" => "4", "name" => "Kodobalghandschuhe des wütenden Gladiators" ),
	array( "id" => "41298", "qual" => "4", "name" => "Kodobalgbeinschützer des wütenden Gladiators" ),
	array( "id" => "41767", "qual" => "4", "name" => "Lederhandschuhe des wütenden Gladiators" ),
	array( "id" => "41655", "qual" => "4", "name" => "Lederbeinschützer des wütenden Gladiators" ),
	array( "id" => "48276", "qual" => "4", "name" => "Windläufers Handschützer der Eroberung" ),
	array( "id" => "48278", "qual" => "4", "name" => "Windläufers Beinschützer der Eroberung" ),
	array( "id" => "48337", "qual" => "4", "name" => "Thralls Handschuhe der Eroberung" ),
	array( "id" => "48339", "qual" => "4", "name" => "Thralls Kilt der Eroberung" ),
	array( "id" => "48367", "qual" => "4", "name" => "Thralls Griff der Eroberung" ),
	array( "id" => "48369", "qual" => "4", "name" => "Thralls Kriegskilt der Eroberung" ),
	array( "id" => "48296", "qual" => "4", "name" => "Thralls Handschützer der Eroberung" ),
	array( "id" => "48298", "qual" => "4", "name" => "Thralls Beinschützer der Eroberung" ),
	array( "id" => "41143", "qual" => "4", "name" => "Kettenstulpen des wütenden Gladiators" ),
	array( "id" => "41205", "qual" => "4", "name" => "Kettengamaschen des wütenden Gladiators" ),
	array( "id" => "41007", "qual" => "4", "name" => "Panzerstulpen des wütenden Gladiators" ),
	array( "id" => "41033", "qual" => "4", "name" => "Panzergamaschen des wütenden Gladiators" ),
	array( "id" => "41137", "qual" => "4", "name" => "Gekettelte Stulpen des wütenden Gladiators" ),
	array( "id" => "41199", "qual" => "4", "name" => "Gekettelte Gamaschen des wütenden Gladiators" ),
	array( "id" => "41001", "qual" => "4", "name" => "Ringpanzerstulpen des wütenden Gladiators" ),
	array( "id" => "41027", "qual" => "4", "name" => "Ringpanzergamaschen des wütenden Gladiators" ),
	array( "id" => "48502", "qual" => "4", "name" => "Koltiras Stulpen der Eroberung" ),
	array( "id" => "48504", "qual" => "4", "name" => "Koltiras Beinplatten der Eroberung" ),
	array( "id" => "48559", "qual" => "4", "name" => "Koltiras Handschützer der Eroberung" ),
	array( "id" => "48561", "qual" => "4", "name" => "Koltiras Beinschützer der Eroberung" ),
	array( "id" => "48598", "qual" => "4", "name" => "Liadrins Handschuhe der Eroberung" ),
	array( "id" => "48596", "qual" => "4", "name" => "Liadrins Schienbeinschützer der Eroberung" ),
	array( "id" => "48630", "qual" => "4", "name" => "Liadrins Stulpen der Eroberung" ),
	array( "id" => "48628", "qual" => "4", "name" => "Liadrins Beinplatten der Eroberung" ),
	array( "id" => "40809", "qual" => "4", "name" => "Schreckensplattenstulpen des wütenden Gladiators" ),
	array( "id" => "40848", "qual" => "4", "name" => "Schreckensplattenbeinschützer des wütenden Gladiators" ),
	array( "id" => "40927", "qual" => "4", "name" => "Zierathandschuhe des wütenden Gladiators" ),
	array( "id" => "40939", "qual" => "4", "name" => "Zieratbeinplatten des wütenden Gladiators" ),
	array( "id" => "40808", "qual" => "4", "name" => "Schuppenstulpen des wütenden Gladiators" ),
	array( "id" => "40849", "qual" => "4", "name" => "Schuppenbeinschützer des wütenden Gladiators" ),
	array( "id" => "48653", "qual" => "4", "name" => "Liadrins Handschützer der Eroberung" ),
	array( "id" => "48655", "qual" => "4", "name" => "Liadrins Beinschützer der Eroberung" ),
	array( "id" => "48387", "qual" => "4", "name" => "Höllschreis Stulpen der Eroberung" ),
	array( "id" => "48389", "qual" => "4", "name" => "Höllschreis Beinplatten der Eroberung" ),
	array( "id" => "48457", "qual" => "4", "name" => "Höllschreis Handschützer der Eroberung" ),
	array( "id" => "48459", "qual" => "4", "name" => "Höllschreis Beinschützer der Eroberung" ),
	array( "id" => "40807", "qual" => "4", "name" => "Plattenstulpen des wütenden Gladiators" ),
	array( "id" => "40847", "qual" => "4", "name" => "Plattenbeinschützer des wütenden Gladiators" ),
	array( "id" => "41909", "qual" => "4", "name" => "Vorherrschaftsmanschetten des wütenden Gladiators" ),
	array( "id" => "41898", "qual" => "4", "name" => "Vorherrschaftskordel des wütenden Gladiators" ),
	array( "id" => "41903", "qual" => "4", "name" => "Vorherrschaftsschuhe des wütenden Gladiators" ),
	array( "id" => "41893", "qual" => "4", "name" => "Errettermanschetten des wütenden Gladiators" ),
	array( "id" => "41881", "qual" => "4", "name" => "Erretterkordel des wütenden Gladiators" ),
	array( "id" => "41885", "qual" => "4", "name" => "Erretterschuhe des wütenden Gladiators" ),
	array( "id" => "41640", "qual" => "4", "name" => "Vorherrschaftsarmwickel des wütenden Gladiators" ),
	array( "id" => "41630", "qual" => "4", "name" => "Vorherrschaftsgürtel des wütenden Gladiators" ),
	array( "id" => "41635", "qual" => "4", "name" => "Vorherrschaftsstiefel des wütenden Gladiators" ),
	array( "id" => "41625", "qual" => "4", "name" => "Erretterarmwickel des wütenden Gladiators" ),
	array( "id" => "41617", "qual" => "4", "name" => "Errettergürtel des wütenden Gladiators" ),
	array( "id" => "41621", "qual" => "4", "name" => "Erretterstiefel des wütenden Gladiators" ),
	array( "id" => "41840", "qual" => "4", "name" => "Triumphale Armwickel des wütenden Gladiators" ),
	array( "id" => "41832", "qual" => "4", "name" => "Triumphaler Gürtel des wütenden Gladiators" ),
	array( "id" => "41836", "qual" => "4", "name" => "Triumphale Stiefel des wütenden Gladiators" ),
	array( "id" => "41065", "qual" => "4", "name" => "Vorherrschaftshandgelenksschutz des wütenden Gladiators" ),
	array( "id" => "41070", "qual" => "4", "name" => "Vorherrschaftstaillenschutz des wütenden Gladiators" ),
	array( "id" => "41075", "qual" => "4", "name" => "Vorherrschaftssabatons des wütenden Gladiators" ),
	array( "id" => "41060", "qual" => "4", "name" => "Erretterhandgelenksschutz des wütenden Gladiators" ),
	array( "id" => "41051", "qual" => "4", "name" => "Errettertaillenschutz des wütenden Gladiators" ),
	array( "id" => "41055", "qual" => "4", "name" => "Errettersabatons des wütenden Gladiators" ),
	array( "id" => "41225", "qual" => "4", "name" => "Triumphale Handgelenksschützer des wütenden Gladiators" ),
	array( "id" => "41235", "qual" => "4", "name" => "Triumphaler Taillenschutz des wütenden Gladiators" ),
	array( "id" => "41230", "qual" => "4", "name" => "Triumphale Sabatons des wütenden Gladiators" ),
	array( "id" => "40983", "qual" => "4", "name" => "Erretterarmschienen des wütenden Gladiators" ),
	array( "id" => "40976", "qual" => "4", "name" => "Errettergurt des wütenden Gladiators" ),
	array( "id" => "40977", "qual" => "4", "name" => "Erretterschienbeinschützer des wütenden Gladiators" ),
	array( "id" => "40889", "qual" => "4", "name" => "Triumphale Armschienen des wütenden Gladiators" ),
	array( "id" => "40881", "qual" => "4", "name" => "Triumphaler Gurt des wütenden Gladiators" ),
	array( "id" => "40882", "qual" => "4", "name" => "Triumphale Schienbeinschützer des wütenden Gladiators" ),
	array( "id" => "42071", "qual" => "4", "name" => "Vormachtsumhang des wütenden Gladiators" ),
	array( "id" => "42073", "qual" => "4", "name" => "Erlösungsumhang des wütenden Gladiators" ),
	array( "id" => "42069", "qual" => "4", "name" => "Vorherrschaftsumhang des wütenden Gladiators" ),
	array( "id" => "42072", "qual" => "4", "name" => "Erretterumhang des wütenden Gladiators" ),
	array( "id" => "42070", "qual" => "4", "name" => "Unterwerfungsumhang des wütenden Gladiators" ),
	array( "id" => "42074", "qual" => "4", "name" => "Triumphaler Umhang des wütenden Gladiators" ),
	array( "id" => "42075", "qual" => "4", "name" => "Siegesumhang des wütenden Gladiators" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem des Triumphs" ),
	array( "id" => "43959", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "44083", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "42037", "qual" => "4", "name" => "Vormachtsanhänger des wütenden Gladiators" ),
	array( "id" => "42039", "qual" => "4", "name" => "Erlösungsanhäger des wütenden Gladiators" ),
	array( "id" => "42036", "qual" => "4", "name" => "Vorherrschaftsanhänger des wütenden Gladiators" ),
	array( "id" => "42040", "qual" => "4", "name" => "Erretteranhänger des wütenden Gladiators" ),
	array( "id" => "42038", "qual" => "4", "name" => "Unterwerfungsanhänger des wütenden Gladiators" ),
	array( "id" => "46373", "qual" => "4", "name" => "Zerschlagungsanhänger des wütenden Gladiators" ),
	array( "id" => "42034", "qual" => "4", "name" => "Triumphaler Anhänger des wütenden Gladiators" ),
	array( "id" => "42035", "qual" => "4", "name" => "Siegesanhänger des wütenden Gladiators" ),
	array( "id" => "42116", "qual" => "4", "name" => "Vorherrschaftsband des wütenden Gladiators" ),
	array( "id" => "42117", "qual" => "4", "name" => "Triumphales Band des wütenden Gladiators" ),
);
}

?>