<?php
$loot = array(
	array( "id" => "46131", "qual" => "4", "name" => "Tapferkeitsstulpen der Kirin Tor" ),
	array( "id" => "45367", "qual" => "4", "name" => "Tapferkeitsgamaschen der Kirin Tor" ),
	array( "id" => "45387", "qual" => "4", "name" => "Weihehandschuhe der Tapferkeit" ),
	array( "id" => "45388", "qual" => "4", "name" => "Weihegamaschen der Tapferkeit" ),
	array( "id" => "45392", "qual" => "4", "name" => "Weihehandlappen der Tapferkeit" ),
	array( "id" => "45394", "qual" => "4", "name" => "Weihehose der Tapferkeit" ),
	array( "id" => "45419", "qual" => "4", "name" => "Todesbringerhandschuhe der Tapferkeit" ),
	array( "id" => "45420", "qual" => "4", "name" => "Todesbringergamaschen der Tapferkeit" ),
	array( "id" => "41970", "qual" => "4", "name" => "Seidene Handschützer des tödlichen Gladiators" ),
	array( "id" => "41958", "qual" => "4", "name" => "Seidene Beinkleider des tödlichen Gladiators" ),
	array( "id" => "41873", "qual" => "4", "name" => "Mondstoffhandschuhe des tödlichen Gladiators" ),
	array( "id" => "41863", "qual" => "4", "name" => "Mondstoffbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41939", "qual" => "4", "name" => "Satinhandschuhe des tödlichen Gladiators" ),
	array( "id" => "41926", "qual" => "4", "name" => "Satingamaschen des tödlichen Gladiators" ),
	array( "id" => "42016", "qual" => "4", "name" => "Teufelsgewebte Handschützer des tödlichen Gladiators" ),
	array( "id" => "42004", "qual" => "4", "name" => "Teufelsgewebte Beinkleider des tödlichen Gladiators" ),
	array( "id" => "45351", "qual" => "4", "name" => "Nachtweisenhandschuhe der Tapferkeit" ),
	array( "id" => "45353", "qual" => "4", "name" => "Nachtweisenbeinkleider der Tapferkeit" ),
	array( "id" => "45355", "qual" => "4", "name" => "Nachtweisenhandschutz der Tapferkeit" ),
	array( "id" => "45357", "qual" => "4", "name" => "Nachtweisenbeinschützer der Tapferkeit" ),
	array( "id" => "45345", "qual" => "4", "name" => "Nachtweisenhandschützer der Tapferkeit" ),
	array( "id" => "45347", "qual" => "4", "name" => "Nachtweisengamaschen der Tapferkeit" ),
	array( "id" => "45397", "qual" => "4", "name" => "Schreckensklingenstulpen der Tapferkeit" ),
	array( "id" => "45399", "qual" => "4", "name" => "Schreckensklingenbeinplatten der Tapferkeit" ),
	array( "id" => "41292", "qual" => "4", "name" => "Wyrmbalghandschuhe des tödlichen Gladiators" ),
	array( "id" => "41303", "qual" => "4", "name" => "Wyrmbalgbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41772", "qual" => "4", "name" => "Drachenlederhandschuhe des tödlichen Gladiators" ),
	array( "id" => "41666", "qual" => "4", "name" => "Drachenlederbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41286", "qual" => "4", "name" => "Kodobalghandschuhe des tödlichen Gladiators" ),
	array( "id" => "41297", "qual" => "4", "name" => "Kodobalgbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41766", "qual" => "4", "name" => "Lederhandschuhe des tödlichen Gladiators" ),
	array( "id" => "41654", "qual" => "4", "name" => "Lederbeinschützer des tödlichen Gladiators" ),
	array( "id" => "45360", "qual" => "4", "name" => "Geißeljägerhandschützer der Tapferkeit" ),
	array( "id" => "45362", "qual" => "4", "name" => "Geißeljägerbeinschützer der Tapferkeit" ),
	array( "id" => "45406", "qual" => "4", "name" => "Weltenbrecherhandschuhe der Tapferkeit" ),
	array( "id" => "45409", "qual" => "4", "name" => "Weltenbrecherkilt der Tapferkeit" ),
	array( "id" => "45414", "qual" => "4", "name" => "Weltenbrecherhandschutz der Tapferkeit" ),
	array( "id" => "45416", "qual" => "4", "name" => "Weltenbrecherkriegskilt der Tapferkeit" ),
	array( "id" => "45401", "qual" => "4", "name" => "Weltenbrecherhandschützer der Tapferkeit" ),
	array( "id" => "45403", "qual" => "4", "name" => "Weltenbrecherbeinschützer der Tapferkeit" ),
	array( "id" => "41142", "qual" => "4", "name" => "Kettenstulpen des tödlichen Gladiators" ),
	array( "id" => "41204", "qual" => "4", "name" => "Kettengamaschen des tödlichen Gladiators" ),
	array( "id" => "41006", "qual" => "4", "name" => "Panzerstulpen des tödlichen Gladiators" ),
	array( "id" => "41032", "qual" => "4", "name" => "Panzergamaschen des tödlichen Gladiators" ),
	array( "id" => "41136", "qual" => "4", "name" => "Gekettelte Stulpen des tödlichen Gladiators" ),
	array( "id" => "41198", "qual" => "4", "name" => "Gekettelte Gamaschen des tödlichen Gladiators" ),
	array( "id" => "41000", "qual" => "4", "name" => "Ringpanzerstulpen des tödlichen Gladiators" ),
	array( "id" => "41026", "qual" => "4", "name" => "Ringpanzergamaschen des tödlichen Gladiators" ),
	array( "id" => "45341", "qual" => "4", "name" => "Dunkle Runenstulpen der Tapferkeit" ),
	array( "id" => "45343", "qual" => "4", "name" => "Dunkle Runenbeinplatten der Tapferkeit" ),
	array( "id" => "45337", "qual" => "4", "name" => "Dunkle Runenhandschützer der Tapferkeit" ),
	array( "id" => "45338", "qual" => "4", "name" => "Dunkle Runenbeinschützer der Tapferkeit" ),
	array( "id" => "45370", "qual" => "4", "name" => "Aegishandschuhe der Tapferkeit" ),
	array( "id" => "45371", "qual" => "4", "name" => "Aegisschienbeinschützer der Tapferkeit" ),
	array( "id" => "45376", "qual" => "4", "name" => "Aegisstulpen der Tapferkeit" ),
	array( "id" => "45379", "qual" => "4", "name" => "Aegisbeinplatten der Tapferkeit" ),
	array( "id" => "40806", "qual" => "4", "name" => "Schreckensplattenstulpen des tödlichen Gladiators" ),
	array( "id" => "40845", "qual" => "4", "name" => "Schreckensplattenbeinschützer des tödlichen Gladiators" ),
	array( "id" => "40926", "qual" => "4", "name" => "Zierathandschuhe des tödlichen Gladiators" ),
	array( "id" => "40938", "qual" => "4", "name" => "Zieratbeinplatten des tödlichen Gladiators" ),
	array( "id" => "40805", "qual" => "4", "name" => "Schuppenstulpen des tödlichen Gladiators" ),
	array( "id" => "40846", "qual" => "4", "name" => "Schuppenbeinschützer des tödlichen Gladiators" ),
	array( "id" => "45383", "qual" => "4", "name" => "Aegishandschützer der Tapferkeit" ),
	array( "id" => "45384", "qual" => "4", "name" => "Aegisbeinschützer der Tapferkeit" ),
	array( "id" => "45430", "qual" => "4", "name" => "Blockadenbrecherstulpen der Tapferkeit" ),
	array( "id" => "45432", "qual" => "4", "name" => "Blockadenbrecherbeinplatten der Tapferkeit" ),
	array( "id" => "45426", "qual" => "4", "name" => "Blockadenbrecherhandschützer der Tapferkeit" ),
	array( "id" => "45427", "qual" => "4", "name" => "Blockadenbrecherbeinschützer der Tapferkeit" ),
	array( "id" => "40804", "qual" => "4", "name" => "Plattenstulpen des tödlichen Gladiators" ),
	array( "id" => "40844", "qual" => "4", "name" => "Plattenbeinschützer des tödlichen Gladiators" ),
	array( "id" => "41908", "qual" => "4", "name" => "Vorherrschaftsmanschetten des tödlichen Gladiators" ),
	array( "id" => "41897", "qual" => "4", "name" => "Vorherrschaftskordel des tödlichen Gladiators" ),
	array( "id" => "41902", "qual" => "4", "name" => "Vorherrschaftstreter des tödlichen Gladiators" ),
	array( "id" => "41892", "qual" => "4", "name" => "Errettermanschetten des tödlichen Gladiators" ),
	array( "id" => "41880", "qual" => "4", "name" => "Erretterkordel des tödlichen Gladiators" ),
	array( "id" => "41884", "qual" => "4", "name" => "Errettertreter des tödlichen Gladiators" ),
	array( "id" => "41639", "qual" => "4", "name" => "Vorherrschaftsarmwickel des tödlichen Gladiators" ),
	array( "id" => "41629", "qual" => "4", "name" => "Vorherrschaftsgürtel des tödlichen Gladiators" ),
	array( "id" => "41634", "qual" => "4", "name" => "Vorherrschaftsstiefel des tödlichen Gladiators" ),
	array( "id" => "41624", "qual" => "4", "name" => "Erretterarmwickel des tödlichen Gladiators" ),
	array( "id" => "41616", "qual" => "4", "name" => "Errettergürtel des tödlichen Gladiators" ),
	array( "id" => "41620", "qual" => "4", "name" => "Erretterstiefel des tödlichen Gladiators" ),
	array( "id" => "41839", "qual" => "4", "name" => "Triumphale Armwickel des tödlichen Gladiators" ),
	array( "id" => "41831", "qual" => "4", "name" => "Triumphaler Gürtel des tödlichen Gladiators" ),
	array( "id" => "41835", "qual" => "4", "name" => "Triumphale Stiefel des tödlichen Gladiators" ),
	array( "id" => "41064", "qual" => "4", "name" => "Vorherrschaftshandgelenksschützer des tödlichen Gladiators" ),
	array( "id" => "41069", "qual" => "4", "name" => "Vorherrschaftstaillenschutz des tödlichen Gladiators" ),
	array( "id" => "41074", "qual" => "4", "name" => "Vorherrschaftssabatons des tödlichen Gladiators" ),
	array( "id" => "41059", "qual" => "4", "name" => "Erretterhandgelenksschützer des tödlichen Gladiators" ),
	array( "id" => "41048", "qual" => "4", "name" => "Errettertaillenschutz des tödlichen Gladiators" ),
	array( "id" => "41054", "qual" => "4", "name" => "Errettersabatons des tödlichen Gladiators" ),
	array( "id" => "41224", "qual" => "4", "name" => "Triumphale Handgelenksschützer des tödlichen Gladiators" ),
	array( "id" => "41234", "qual" => "4", "name" => "Triumphaler Taillenschutz des tödlichen Gladiators" ),
	array( "id" => "41229", "qual" => "4", "name" => "Triumphale Sabatons des tödlichen Gladiators" ),
	array( "id" => "40982", "qual" => "4", "name" => "Erretterarmschienen des tödlichen Gladiators" ),
	array( "id" => "40974", "qual" => "4", "name" => "Errettergurt des tödlichen Gladiators" ),
	array( "id" => "40975", "qual" => "4", "name" => "Erretterschienbeinschützer des tödlichen Gladiators" ),
	array( "id" => "40888", "qual" => "4", "name" => "Triumphale Armschienen des tödlichen Gladiators" ),
	array( "id" => "40879", "qual" => "4", "name" => "Triumphaler Gurt des tödlichen Gladiators" ),
	array( "id" => "40880", "qual" => "4", "name" => "Triumphale Schienbeinschützer des tödlichen Gladiators" ),
	array( "id" => "42064", "qual" => "4", "name" => "Vormachtsumhang des tödlichen Gladiators" ),
	array( "id" => "42066", "qual" => "4", "name" => "Erlösungsumhang des tödlichen Gladiators" ),
	array( "id" => "42062", "qual" => "4", "name" => "Vorherrschaftsumhang des tödlichen Gladiators" ),
	array( "id" => "42065", "qual" => "4", "name" => "Erretterumhang des tödlichen Gladiators" ),
	array( "id" => "42063", "qual" => "4", "name" => "Unterwerfungsumhang des tödlichen Gladiators" ),
	array( "id" => "42067", "qual" => "4", "name" => "Triumphaler Umhang des tödlichen Gladiators" ),
	array( "id" => "42068", "qual" => "4", "name" => "Siegesumhang des tödlichen Gladiators" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem des Triumphs" ),
	array( "id" => "43959", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "44083", "qual" => "4", "name" => "Zügel des großen schwarzen Kriegsmammuts" ),
	array( "id" => "42030", "qual" => "4", "name" => "Vormachtsanhänger des tödlichen Gladiators" ),
	array( "id" => "42032", "qual" => "4", "name" => "Erlösungsanhänger des tödlichen Gladiators" ),
	array( "id" => "42029", "qual" => "4", "name" => "Vorherrschaftsanhänger des tödlichen Gladiators" ),
	array( "id" => "42033", "qual" => "4", "name" => "Erretteranhänger des tödlichen Gladiators" ),
	array( "id" => "42031", "qual" => "4", "name" => "Unterwerfungsanhänger des tödlichen Gladiators" ),
	array( "id" => "42027", "qual" => "4", "name" => "Triumphaler Anhänger des tödlichen Gladiators" ),
	array( "id" => "42028", "qual" => "4", "name" => "Siegesanhänger des tödlichen Gladiators" ),
	array( "id" => "42114", "qual" => "4", "name" => "Vormachtsband des tödlichen Gladiators" ),
	array( "id" => "42115", "qual" => "4", "name" => "Siegesband des tödlichen Gladiators" ),
);

?>