<?php
$loot = array(
	array( "id" => "39732", "qual" => "4", "name" => "Faerlinas Wahnsinn" ),
	array( "id" => "39731", "qual" => "4", "name" => "Korrekte Bindungen" ),
	array( "id" => "39733", "qual" => "4", "name" => "Zeichen der Hochachtung" ),
	array( "id" => "39735", "qual" => "4", "name" => "Gürtel der falschen Würde" ),
	array( "id" => "39756", "qual" => "4", "name" => "Tunika des Vorurteils" ),
	array( "id" => "39727", "qual" => "4", "name" => "Ausrenkende Handschützer" ),
	array( "id" => "39724", "qual" => "4", "name" => "Brustschutz des Kults" ),
	array( "id" => "39734", "qual" => "4", "name" => "Schienbeinschützer der Buße" ),
	array( "id" => "39723", "qual" => "4", "name" => "Angesengter Großhelm" ),
	array( "id" => "39725", "qual" => "4", "name" => "Schulterklappen des trauernden Dieners" ),
	array( "id" => "39729", "qual" => "4", "name" => "Armschienen des Tyrannen" ),
	array( "id" => "39726", "qual" => "4", "name" => "Hartherzige Stulpen" ),
	array( "id" => "40071", "qual" => "4", "name" => "Ketten der Verehrung" ),
	array( "id" => "40065", "qual" => "4", "name" => "Narrenprüfung" ),
	array( "id" => "40069", "qual" => "4", "name" => "Erbe" ),
	array( "id" => "40064", "qual" => "4", "name" => "Gewitteramulett" ),
	array( "id" => "40080", "qual" => "4", "name" => "Verlorenes Juwel" ),
	array( "id" => "40075", "qual" => "4", "name" => "Skrupellosigkeit" ),
	array( "id" => "40107", "qual" => "4", "name" => "Sandgeschliffenes Band" ),
	array( "id" => "40108", "qual" => "4", "name" => "Ergriffene Schönheit" ),
	array( "id" => "40074", "qual" => "4", "name" => "Ring der starken Hand" ),
	array( "id" => "39757", "qual" => "4", "name" => "Götze der Verehrung" ),
	array( "id" => "39728", "qual" => "4", "name" => "Totem des Elends" ),
	array( "id" => "39730", "qual" => "4", "name" => "Witwenzorn" ),
);
?>