<?php
$loot = array(
	array( "id" => "40254", "qual" => "4", "name" => "Umhang der abgewendeten Krise" ),
	array( "id" => "40252", "qual" => "4", "name" => "Umhang der verfinsterten Sonne" ),
	array( "id" => "40253", "qual" => "4", "name" => "Schal der alten Maid" ),
	array( "id" => "40251", "qual" => "4", "name" => "Tuch der Leuchtkraft" ),
	array( "id" => "40287", "qual" => "4", "name" => "Gugel der Eitelkeit" ),
	array( "id" => "40286", "qual" => "4", "name" => "Mantel des Verdorbenen" ),
	array( "id" => "40351", "qual" => "4", "name" => "Mantel des ermüdeten Weisen" ),
	array( "id" => "40289", "qual" => "4", "name" => "Mitfühlende Amicia" ),
	array( "id" => "40277", "qual" => "4", "name" => "Tunika der Milde" ),
	array( "id" => "40285", "qual" => "4", "name" => "Entweihte Vergangenheit" ),
	array( "id" => "40288", "qual" => "4", "name" => "Schiftung der Inkohärenz" ),
	array( "id" => "40283", "qual" => "4", "name" => "Strahlungsresistente Tunika" ),
	array( "id" => "40282", "qual" => "4", "name" => "Schleimstrombänder" ),
	array( "id" => "40275", "qual" => "4", "name" => "Verdorbener gekettelter Gürtel" ),
	array( "id" => "40279", "qual" => "4", "name" => "Brustschutz des Erschöpften" ),
	array( "id" => "40274", "qual" => "4", "name" => "Armschienen der Befreiung" ),
	array( "id" => "40278", "qual" => "4", "name" => "Gurt der Ritterlichkeit" ),
	array( "id" => "40257", "qual" => "4", "name" => "Kodex des Verteidigers" ),
	array( "id" => "40255", "qual" => "4", "name" => "Letzter Fluch" ),
	array( "id" => "40258", "qual" => "4", "name" => "Talisman der Vorsehung" ),
	array( "id" => "40256", "qual" => "4", "name" => "Grimmiger Tribut" ),
	array( "id" => "40273", "qual" => "4", "name" => "Extrabein" ),
	array( "id" => "40281", "qual" => "4", "name" => "Nebel des Zwielichts" ),
	array( "id" => "40280", "qual" => "4", "name" => "Alptraumserzeuger" ),
	array( "id" => "40284", "qual" => "4", "name" => "Seuchenzünder" ),
);
?>