<?php
$loot = array(
	array( "id" => "47927", "qual" => "4", "name" => "Felspark Bindings" ),
	array( "id" => "47931", "qual" => "4", "name" => "Leggings of the Demonic Messenger" ),
	array( "id" => "47929", "qual" => "4", "name" => "Belt of the Winter Solstice" ),
	array( "id" => "47932", "qual" => "4", "name" => "Girdle of the Farseer" ),
	array( "id" => "49238", "qual" => "4", "name" => "Boots of Tortured Space" ),
	array( "id" => "47933", "qual" => "4", "name" => "Sentinel Scouting Greaves" ),
	array( "id" => "47935", "qual" => "4", "name" => "Armguards of the Nether Lord" ),
	array( "id" => "47937", "qual" => "4", "name" => "Girdle of the Nether Champion" ),
	array( "id" => "47930", "qual" => "4", "name" => "Amulet of Binding Elements" ),
	array( "id" => "47939", "qual" => "4", "name" => "Endurance of the Infernal" ),
	array( "id" => "47928", "qual" => "4", "name" => "Firestorm Ring" ),
	array( "id" => "47934", "qual" => "4", "name" => "Planestalker Signet" ),
	array( "id" => "47938", "qual" => "4", "name" => "Dirk of the Night Watch" ),
	array( "id" => "47242", "qual" => "4", "name" => "Trophäe des Kreuzzugs" ),
	array( "id" => "48000", "qual" => "4", "name" => "Felspark Bracers" ),
	array( "id" => "48004", "qual" => "4", "name" => "Legwraps of the Demonic Messenger" ),
	array( "id" => "48002", "qual" => "4", "name" => "Belt of the Bloodhoof Emissary" ),
	array( "id" => "48005", "qual" => "4", "name" => "Darkspear Ritual Binding" ),
	array( "id" => "49237", "qual" => "4", "name" => "Sabatons of Tortured Space" ),
	array( "id" => "48006", "qual" => "4", "name" => "Warsong Poacher's Greaves" ),
	array( "id" => "48008", "qual" => "4", "name" => "Armplates of the Nether Lord" ),
	array( "id" => "48009", "qual" => "4", "name" => "Belt of the Nether Champion" ),
	array( "id" => "48011", "qual" => "4", "name" => "Fortitude of the Infernal" ),
	array( "id" => "48003", "qual" => "4", "name" => "Pendant of Binding Elements" ),
	array( "id" => "48001", "qual" => "4", "name" => "Firestorm Band" ),
	array( "id" => "48007", "qual" => "4", "name" => "Planestalker Band" ),
	array( "id" => "48010", "qual" => "4", "name" => "Orcish Deathblade" ),
	array( "id" => "47242", "qual" => "4", "name" => "Trophäe des Kreuzzugs" ),
);
?>