<?php
if($this->get_faction() == 'alliance'){
$loot = array(
	array( "id" => "47753", "qual" => "4", "name" => "Khadgar's Gauntlets of Triumph" ),
	array( "id" => "47755", "qual" => "4", "name" => "Khadgar's Leggings of Triumph" ),
	array( "id" => "47983", "qual" => "4", "name" => "Velen's Gloves of Triumph" ),
	array( "id" => "47985", "qual" => "4", "name" => "Velen's Leggings of Triumph" ),
	array( "id" => "48077", "qual" => "4", "name" => "Velen's Handwraps of Triumph" ),
	array( "id" => "48079", "qual" => "4", "name" => "Velen's Pants of Triumph" ),
	array( "id" => "47782", "qual" => "4", "name" => "Kel'Thuzad's Gloves of Triumph" ),
	array( "id" => "47780", "qual" => "4", "name" => "Kel'Thuzad's Leggings of Triumph" ),
	array( "id" => "41972", "qual" => "4", "name" => "Relentless Gladiator's Silk Handguards" ),
	array( "id" => "41960", "qual" => "4", "name" => "Relentless Gladiator's Silk Trousers" ),
	array( "id" => "41875", "qual" => "4", "name" => "Relentless Gladiator's Mooncloth Gloves" ),
	array( "id" => "41865", "qual" => "4", "name" => "Relentless Gladiator's Mooncloth Leggings" ),
	array( "id" => "41941", "qual" => "4", "name" => "Relentless Gladiator's Satin Gloves" ),
	array( "id" => "41928", "qual" => "4", "name" => "Relentless Gladiator's Satin Leggings" ),
	array( "id" => "42018", "qual" => "4", "name" => "Relentless Gladiator's Felweave Handguards" ),
	array( "id" => "42006", "qual" => "4", "name" => "Relentless Gladiator's Felweave Trousers" ),
	array( "id" => "48163", "qual" => "4", "name" => "Malfurion's Gloves of Triumph" ),
	array( "id" => "48165", "qual" => "4", "name" => "Malfurion's Trousers of Triumph" ),
	array( "id" => "48212", "qual" => "4", "name" => "Malfurion's Handgrips of Triumph" ),
	array( "id" => "48210", "qual" => "4", "name" => "Malfurion's Legguards of Triumph" ),
	array( "id" => "48133", "qual" => "4", "name" => "Malfurion's Handguards of Triumph" ),
	array( "id" => "48135", "qual" => "4", "name" => "Malfurion's Leggings of Triumph" ),
	array( "id" => "48224", "qual" => "4", "name" => "VanCleef's Gauntlets of Triumph" ),
	array( "id" => "48226", "qual" => "4", "name" => "VanCleef's Legplates of Triumph" ),
	array( "id" => "41294", "qual" => "4", "name" => "Relentless Gladiator's Wyrmhide Gloves" ),
	array( "id" => "41305", "qual" => "4", "name" => "Relentless Gladiator's Wyrmhide Legguards" ),
	array( "id" => "41774", "qual" => "4", "name" => "Relentless Gladiator's Dragonhide Gloves" ),
	array( "id" => "41668", "qual" => "4", "name" => "Relentless Gladiator's Dragonhide Legguards" ),
	array( "id" => "41288", "qual" => "4", "name" => "Relentless Gladiator's Kodohide Gloves" ),
	array( "id" => "41299", "qual" => "4", "name" => "Relentless Gladiator's Kodohide Legguards" ),
	array( "id" => "41768", "qual" => "4", "name" => "Relentless Gladiator's Leather Gloves" ),
	array( "id" => "41656", "qual" => "4", "name" => "Relentless Gladiator's Leather Legguards" ),
	array( "id" => "48256", "qual" => "4", "name" => "Windrunner's Handguards of Triumph" ),
	array( "id" => "48258", "qual" => "4", "name" => "Windrunner's Legguards of Triumph" ),
	array( "id" => "48317", "qual" => "4", "name" => "Nobundo's Gloves of Triumph" ),
	array( "id" => "48319", "qual" => "4", "name" => "Nobundo's Kilt of Triumph" ),
	array( "id" => "48347", "qual" => "4", "name" => "Nobundo's Grips of Triumph" ),
	array( "id" => "48349", "qual" => "4", "name" => "Nobundo's War-Kilt of Triumph" ),
	array( "id" => "48286", "qual" => "4", "name" => "Nobundo's Handguards of Triumph" ),
	array( "id" => "48288", "qual" => "4", "name" => "Nobundo's Legguards of Triumph" ),
	array( "id" => "41144", "qual" => "4", "name" => "Relentless Gladiator's Chain Gauntlets" ),
	array( "id" => "41206", "qual" => "4", "name" => "Relentless Gladiator's Chain Leggings" ),
	array( "id" => "41008", "qual" => "4", "name" => "Relentless Gladiator's Mail Gauntlets" ),
	array( "id" => "41034", "qual" => "4", "name" => "Relentless Gladiator's Mail Leggings" ),
	array( "id" => "41138", "qual" => "4", "name" => "Relentless Gladiator's Linked Gauntlets" ),
	array( "id" => "41200", "qual" => "4", "name" => "Relentless Gladiator's Linked Leggings" ),
	array( "id" => "41002", "qual" => "4", "name" => "Relentless Gladiator's Ringmail Gauntlets" ),
	array( "id" => "41028", "qual" => "4", "name" => "Relentless Gladiator's Ringmail Leggings" ),
	array( "id" => "48482", "qual" => "4", "name" => "Thassarian's Gauntlets of Triumph" ),
	array( "id" => "48484", "qual" => "4", "name" => "Thassarian's Legplates of Triumph" ),
	array( "id" => "48539", "qual" => "4", "name" => "Thassarian's Handguards of Triumph" ),
	array( "id" => "48541", "qual" => "4", "name" => "Thassarian's Legguards of Triumph" ),
	array( "id" => "48576", "qual" => "4", "name" => "Turalyon's Gloves of Triumph" ),
	array( "id" => "48578", "qual" => "4", "name" => "Turalyon's Greaves of Triumph" ),
	array( "id" => "48608", "qual" => "4", "name" => "Turalyon's Gauntlets of Triumph" ),
	array( "id" => "48610", "qual" => "4", "name" => "Turalyon's Legplates of Triumph" ),
	array( "id" => "40811", "qual" => "4", "name" => "Relentless Gladiator's Dreadplate Gauntlets" ),
	array( "id" => "40851", "qual" => "4", "name" => "Relentless Gladiator's Dreadplate Legguards" ),
	array( "id" => "40928", "qual" => "4", "name" => "Relentless Gladiator's Ornamented Gloves" ),
	array( "id" => "40940", "qual" => "4", "name" => "Relentless Gladiator's Ornamented Legplates" ),
	array( "id" => "40812", "qual" => "4", "name" => "Relentless Gladiator's Scaled Gauntlets" ),
	array( "id" => "40852", "qual" => "4", "name" => "Relentless Gladiator's Scaled Legguards" ),
	array( "id" => "48640", "qual" => "4", "name" => "Turalyon's Handguards of Triumph" ),
	array( "id" => "48638", "qual" => "4", "name" => "Turalyon's Legguards of Triumph" ),
	array( "id" => "48377", "qual" => "4", "name" => "Wrynn's Gauntlets of Triumph" ),
	array( "id" => "48379", "qual" => "4", "name" => "Wrynn's Legplates of Triumph" ),
	array( "id" => "48452", "qual" => "4", "name" => "Wrynn's Handguards of Triumph" ),
	array( "id" => "48446", "qual" => "4", "name" => "Wrynn's Legguards of Triumph" ),
	array( "id" => "40810", "qual" => "4", "name" => "Relentless Gladiator's Plate Gauntlets" ),
	array( "id" => "40850", "qual" => "4", "name" => "Relentless Gladiator's Plate Legguards" ),
	array( "id" => "41910", "qual" => "4", "name" => "Relentless Gladiator's Cuffs of Dominance" ),
	array( "id" => "41899", "qual" => "4", "name" => "Relentless Gladiator's Cord of Dominance" ),
	array( "id" => "41904", "qual" => "4", "name" => "Relentless Gladiator's Treads of Dominance" ),
	array( "id" => "41894", "qual" => "4", "name" => "Relentless Gladiator's Cuffs of Salvation" ),
	array( "id" => "41882", "qual" => "4", "name" => "Relentless Gladiator's Cord of Salvation" ),
	array( "id" => "41886", "qual" => "4", "name" => "Relentless Gladiator's Treads of Salvation" ),
	array( "id" => "49181", "qual" => "4", "name" => "Relentless Gladiator's Cuffs of Alacrity" ),
	array( "id" => "49179", "qual" => "4", "name" => "Relentless Gladiator's Cord of Alacrity" ),
	array( "id" => "49183", "qual" => "4", "name" => "Relentless Gladiator's Treads of Alacrity" ),
	array( "id" => "41641", "qual" => "4", "name" => "Relentless Gladiator's Armwraps of Dominance" ),
	array( "id" => "41631", "qual" => "4", "name" => "Relentless Gladiator's Belt of Dominance" ),
	array( "id" => "41636", "qual" => "4", "name" => "Relentless Gladiator's Boots of Dominance" ),
	array( "id" => "41626", "qual" => "4", "name" => "Relentless Gladiator's Armwraps of Salvation" ),
	array( "id" => "41618", "qual" => "4", "name" => "Relentless Gladiator's Belt of Salvation" ),
	array( "id" => "41622", "qual" => "4", "name" => "Relentless Gladiator's Boots of Salvation" ),
	array( "id" => "41841", "qual" => "4", "name" => "Relentless Gladiator's Armwraps of Triumph" ),
	array( "id" => "41833", "qual" => "4", "name" => "Relentless Gladiator's Belt of Triumph" ),
	array( "id" => "41837", "qual" => "4", "name" => "Relentless Gladiator's Boots of Triumph" ),
	array( "id" => "41066", "qual" => "4", "name" => "Relentless Gladiator's Wristguards of Dominance" ),
	array( "id" => "41071", "qual" => "4", "name" => "Relentless Gladiator's Waistguard of Dominance" ),
	array( "id" => "41076", "qual" => "4", "name" => "Relentless Gladiator's Sabatons of Dominance" ),
	array( "id" => "41061", "qual" => "4", "name" => "Relentless Gladiator's Wristguards of Salvation" ),
	array( "id" => "41052", "qual" => "4", "name" => "Relentless Gladiator's Waistguard of Salvation" ),
	array( "id" => "41056", "qual" => "4", "name" => "Relentless Gladiator's Sabatons of Salvation" ),
	array( "id" => "41226", "qual" => "4", "name" => "Relentless Gladiator's Wristguards of Triumph" ),
	array( "id" => "41236", "qual" => "4", "name" => "Relentless Gladiator's Waistguard of Triumph" ),
	array( "id" => "41231", "qual" => "4", "name" => "Relentless Gladiator's Sabatons of Triumph" ),
	array( "id" => "40984", "qual" => "4", "name" => "Relentless Gladiator's Bracers of Salvation" ),
	array( "id" => "40978", "qual" => "4", "name" => "Relentless Gladiator's Girdle of Salvation" ),
	array( "id" => "40979", "qual" => "4", "name" => "Relentless Gladiator's Greaves of Salvation" ),
	array( "id" => "40890", "qual" => "4", "name" => "Relentless Gladiator's Bracers of Triumph" ),
	array( "id" => "40883", "qual" => "4", "name" => "Relentless Gladiator's Girdle of Triumph" ),
	array( "id" => "40884", "qual" => "4", "name" => "Relentless Gladiator's Greaves of Triumph" ),
	array( "id" => "42078", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Ascendancy" ),
	array( "id" => "42080", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Deliverance" ),
	array( "id" => "42076", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Dominance" ),
	array( "id" => "42079", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Salvation" ),
	array( "id" => "42077", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Subjugation" ),
	array( "id" => "42081", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Triumph" ),
	array( "id" => "42082", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Victory" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem of Triumph" ),
	array( "id" => "43959", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "44083", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "42044", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Ascendancy" ),
	array( "id" => "42046", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Deliverance" ),
	array( "id" => "42043", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Dominance" ),
	array( "id" => "42047", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Salvation" ),
	array( "id" => "42045", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Subjugation" ),
	array( "id" => "46374", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Sundering" ),
	array( "id" => "42041", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Triumph" ),
	array( "id" => "42042", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Victory" ),
	array( "id" => "42118", "qual" => "4", "name" => "Relentless Gladiator's Band of Ascendancy" ),
	array( "id" => "42119", "qual" => "4", "name" => "Relentless Gladiator's Band of Victory" ),
);
}else{
$loot = array(
	array( "id" => "47772", "qual" => "4", "name" => "Sunstrider's Gauntlets of Triumph" ),
	array( "id" => "47770", "qual" => "4", "name" => "Sunstrider's Leggings of Triumph" ),
	array( "id" => "48066", "qual" => "4", "name" => "Zabra's Gloves of Triumph" ),
	array( "id" => "48064", "qual" => "4", "name" => "Zabra's Leggings of Triumph" ),
	array( "id" => "48096", "qual" => "4", "name" => "Zabra's Handwraps of Triumph" ),
	array( "id" => "48094", "qual" => "4", "name" => "Zabra's Pants of Triumph" ),
	array( "id" => "47803", "qual" => "4", "name" => "Gul'dan's Gloves of Triumph" ),
	array( "id" => "47805", "qual" => "4", "name" => "Gul'dan's Leggings of Triumph" ),
	array( "id" => "41972", "qual" => "4", "name" => "Relentless Gladiator's Silk Handguards" ),
	array( "id" => "41960", "qual" => "4", "name" => "Relentless Gladiator's Silk Trousers" ),
	array( "id" => "41875", "qual" => "4", "name" => "Relentless Gladiator's Mooncloth Gloves" ),
	array( "id" => "41865", "qual" => "4", "name" => "Relentless Gladiator's Mooncloth Leggings" ),
	array( "id" => "41941", "qual" => "4", "name" => "Relentless Gladiator's Satin Gloves" ),
	array( "id" => "41928", "qual" => "4", "name" => "Relentless Gladiator's Satin Leggings" ),
	array( "id" => "42018", "qual" => "4", "name" => "Relentless Gladiator's Felweave Handguards" ),
	array( "id" => "42006", "qual" => "4", "name" => "Relentless Gladiator's Felweave Trousers" ),
	array( "id" => "48182", "qual" => "4", "name" => "Runetotem's Gloves of Triumph" ),
	array( "id" => "48180", "qual" => "4", "name" => "Runetotem's Trousers of Triumph" ),
	array( "id" => "48193", "qual" => "4", "name" => "Runetotem's Handgrips of Triumph" ),
	array( "id" => "48195", "qual" => "4", "name" => "Runetotem's Legguards of Triumph" ),
	array( "id" => "48152", "qual" => "4", "name" => "Runetotem's Handguards of Triumph" ),
	array( "id" => "48150", "qual" => "4", "name" => "Runetotem's Leggings of Triumph" ),
	array( "id" => "48241", "qual" => "4", "name" => "Garona's Gauntlets of Triumph" ),
	array( "id" => "48239", "qual" => "4", "name" => "Garona's Legplates of Triumph" ),
	array( "id" => "41294", "qual" => "4", "name" => "Relentless Gladiator's Wyrmhide Gloves" ),
	array( "id" => "41305", "qual" => "4", "name" => "Relentless Gladiator's Wyrmhide Legguards" ),
	array( "id" => "41774", "qual" => "4", "name" => "Relentless Gladiator's Dragonhide Gloves" ),
	array( "id" => "41668", "qual" => "4", "name" => "Relentless Gladiator's Dragonhide Legguards" ),
	array( "id" => "41288", "qual" => "4", "name" => "Relentless Gladiator's Kodohide Gloves" ),
	array( "id" => "41299", "qual" => "4", "name" => "Relentless Gladiator's Kodohide Legguards" ),
	array( "id" => "41768", "qual" => "4", "name" => "Relentless Gladiator's Leather Gloves" ),
	array( "id" => "41656", "qual" => "4", "name" => "Relentless Gladiator's Leather Legguards" ),
	array( "id" => "48273", "qual" => "4", "name" => "Windrunner's Handguards of Triumph" ),
	array( "id" => "48271", "qual" => "4", "name" => "Windrunner's Legguards of Triumph" ),
	array( "id" => "48334", "qual" => "4", "name" => "Thrall's Gloves of Triumph" ),
	array( "id" => "48332", "qual" => "4", "name" => "Thrall's Kilt of Triumph" ),
	array( "id" => "48364", "qual" => "4", "name" => "Thrall's Grips of Triumph" ),
	array( "id" => "48362", "qual" => "4", "name" => "Thrall's War-Kilt of Triumph" ),
	array( "id" => "48301", "qual" => "4", "name" => "Thrall's Handguards of Triumph" ),
	array( "id" => "48303", "qual" => "4", "name" => "Thrall's Legguards of Triumph" ),
	array( "id" => "41144", "qual" => "4", "name" => "Relentless Gladiator's Chain Gauntlets" ),
	array( "id" => "41206", "qual" => "4", "name" => "Relentless Gladiator's Chain Leggings" ),
	array( "id" => "41008", "qual" => "4", "name" => "Relentless Gladiator's Mail Gauntlets" ),
	array( "id" => "41034", "qual" => "4", "name" => "Relentless Gladiator's Mail Leggings" ),
	array( "id" => "41138", "qual" => "4", "name" => "Relentless Gladiator's Linked Gauntlets" ),
	array( "id" => "41200", "qual" => "4", "name" => "Relentless Gladiator's Linked Leggings" ),
	array( "id" => "41002", "qual" => "4", "name" => "Relentless Gladiator's Ringmail Gauntlets" ),
	array( "id" => "41028", "qual" => "4", "name" => "Relentless Gladiator's Ringmail Leggings" ),
	array( "id" => "48499", "qual" => "4", "name" => "Koltira's Gauntlets of Triumph" ),
	array( "id" => "48497", "qual" => "4", "name" => "Koltira's Legplates of Triumph" ),
	array( "id" => "48556", "qual" => "4", "name" => "Koltira's Handguards of Triumph" ),
	array( "id" => "48554", "qual" => "4", "name" => "Koltira's Legguards of Triumph" ),
	array( "id" => "48593", "qual" => "4", "name" => "Liadrin's Gloves of Triumph" ),
	array( "id" => "48591", "qual" => "4", "name" => "Liadrin's Greaves of Triumph" ),
	array( "id" => "48625", "qual" => "4", "name" => "Liadrin's Gauntlets of Triumph" ),
	array( "id" => "48623", "qual" => "4", "name" => "Liadrin's Legplates of Triumph" ),
	array( "id" => "40811", "qual" => "4", "name" => "Relentless Gladiator's Dreadplate Gauntlets" ),
	array( "id" => "40851", "qual" => "4", "name" => "Relentless Gladiator's Dreadplate Legguards" ),
	array( "id" => "40928", "qual" => "4", "name" => "Relentless Gladiator's Ornamented Gloves" ),
	array( "id" => "40940", "qual" => "4", "name" => "Relentless Gladiator's Ornamented Legplates" ),
	array( "id" => "40812", "qual" => "4", "name" => "Relentless Gladiator's Scaled Gauntlets" ),
	array( "id" => "40852", "qual" => "4", "name" => "Relentless Gladiator's Scaled Legguards" ),
	array( "id" => "48658", "qual" => "4", "name" => "Liadrin's Handguards of Triumph" ),
	array( "id" => "48660", "qual" => "4", "name" => "Liadrin's Legguards of Triumph" ),
	array( "id" => "48392", "qual" => "4", "name" => "Hellscream's Gauntlets of Triumph" ),
	array( "id" => "48394", "qual" => "4", "name" => "Hellscream's Legplates of Triumph" ),
	array( "id" => "48462", "qual" => "4", "name" => "Hellscream's Handguards of Triumph" ),
	array( "id" => "48464", "qual" => "4", "name" => "Hellscream's Legguards of Triumph" ),
	array( "id" => "40810", "qual" => "4", "name" => "Relentless Gladiator's Plate Gauntlets" ),
	array( "id" => "40850", "qual" => "4", "name" => "Relentless Gladiator's Plate Legguards" ),
	array( "id" => "41910", "qual" => "4", "name" => "Relentless Gladiator's Cuffs of Dominance" ),
	array( "id" => "41899", "qual" => "4", "name" => "Relentless Gladiator's Cord of Dominance" ),
	array( "id" => "41904", "qual" => "4", "name" => "Relentless Gladiator's Treads of Dominance" ),
	array( "id" => "41894", "qual" => "4", "name" => "Relentless Gladiator's Cuffs of Salvation" ),
	array( "id" => "41882", "qual" => "4", "name" => "Relentless Gladiator's Cord of Salvation" ),
	array( "id" => "41886", "qual" => "4", "name" => "Relentless Gladiator's Treads of Salvation" ),
	array( "id" => "49181", "qual" => "4", "name" => "Relentless Gladiator's Cuffs of Alacrity" ),
	array( "id" => "49179", "qual" => "4", "name" => "Relentless Gladiator's Cord of Alacrity" ),
	array( "id" => "49183", "qual" => "4", "name" => "Relentless Gladiator's Treads of Alacrity" ),
	array( "id" => "41641", "qual" => "4", "name" => "Relentless Gladiator's Armwraps of Dominance" ),
	array( "id" => "41631", "qual" => "4", "name" => "Relentless Gladiator's Belt of Dominance" ),
	array( "id" => "41636", "qual" => "4", "name" => "Relentless Gladiator's Boots of Dominance" ),
	array( "id" => "41626", "qual" => "4", "name" => "Relentless Gladiator's Armwraps of Salvation" ),
	array( "id" => "41618", "qual" => "4", "name" => "Relentless Gladiator's Belt of Salvation" ),
	array( "id" => "41622", "qual" => "4", "name" => "Relentless Gladiator's Boots of Salvation" ),
	array( "id" => "41841", "qual" => "4", "name" => "Relentless Gladiator's Armwraps of Triumph" ),
	array( "id" => "41833", "qual" => "4", "name" => "Relentless Gladiator's Belt of Triumph" ),
	array( "id" => "41837", "qual" => "4", "name" => "Relentless Gladiator's Boots of Triumph" ),
	array( "id" => "41066", "qual" => "4", "name" => "Relentless Gladiator's Wristguards of Dominance" ),
	array( "id" => "41071", "qual" => "4", "name" => "Relentless Gladiator's Waistguard of Dominance" ),
	array( "id" => "41076", "qual" => "4", "name" => "Relentless Gladiator's Sabatons of Dominance" ),
	array( "id" => "41061", "qual" => "4", "name" => "Relentless Gladiator's Wristguards of Salvation" ),
	array( "id" => "41052", "qual" => "4", "name" => "Relentless Gladiator's Waistguard of Salvation" ),
	array( "id" => "41056", "qual" => "4", "name" => "Relentless Gladiator's Sabatons of Salvation" ),
	array( "id" => "41226", "qual" => "4", "name" => "Relentless Gladiator's Wristguards of Triumph" ),
	array( "id" => "41236", "qual" => "4", "name" => "Relentless Gladiator's Waistguard of Triumph" ),
	array( "id" => "41231", "qual" => "4", "name" => "Relentless Gladiator's Sabatons of Triumph" ),
	array( "id" => "40984", "qual" => "4", "name" => "Relentless Gladiator's Bracers of Salvation" ),
	array( "id" => "40978", "qual" => "4", "name" => "Relentless Gladiator's Girdle of Salvation" ),
	array( "id" => "40979", "qual" => "4", "name" => "Relentless Gladiator's Greaves of Salvation" ),
	array( "id" => "40890", "qual" => "4", "name" => "Relentless Gladiator's Bracers of Triumph" ),
	array( "id" => "40883", "qual" => "4", "name" => "Relentless Gladiator's Girdle of Triumph" ),
	array( "id" => "40884", "qual" => "4", "name" => "Relentless Gladiator's Greaves of Triumph" ),
	array( "id" => "42078", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Ascendancy" ),
	array( "id" => "42080", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Deliverance" ),
	array( "id" => "42076", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Dominance" ),
	array( "id" => "42079", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Salvation" ),
	array( "id" => "42077", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Subjugation" ),
	array( "id" => "42081", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Triumph" ),
	array( "id" => "42082", "qual" => "4", "name" => "Relentless Gladiator's Cloak of Victory" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem of Triumph" ),
	array( "id" => "43959", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "44083", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "42044", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Ascendancy" ),
	array( "id" => "42046", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Deliverance" ),
	array( "id" => "42043", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Dominance" ),
	array( "id" => "42047", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Salvation" ),
	array( "id" => "42045", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Subjugation" ),
	array( "id" => "46374", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Sundering" ),
	array( "id" => "42041", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Triumph" ),
	array( "id" => "42042", "qual" => "4", "name" => "Relentless Gladiator's Pendant of Victory" ),
	array( "id" => "42118", "qual" => "4", "name" => "Relentless Gladiator's Band of Ascendancy" ),
	array( "id" => "42119", "qual" => "4", "name" => "Relentless Gladiator's Band of Victory" ),
);
}

?>