<?php
$loot = array(
	array( "id" => "47745", "qual" => "4", "name" => "Gloves of Looming Shadow" ),
	array( "id" => "49231", "qual" => "4", "name" => "Boots of the Grieving Soul" ),
	array( "id" => "47746", "qual" => "4", "name" => "Helm of the Snowy Grotto" ),
	array( "id" => "47739", "qual" => "4", "name" => "Armor of Shifting Shadows" ),
	array( "id" => "47744", "qual" => "4", "name" => "Gloves of the Azure Prophet" ),
	array( "id" => "47738", "qual" => "4", "name" => "Sabatons of the Lingering Vortex" ),
	array( "id" => "47747", "qual" => "4", "name" => "Darkbane Pendant" ),
	array( "id" => "47700", "qual" => "4", "name" => "Loop of the Twin Val'kyr" ),
	array( "id" => "47742", "qual" => "4", "name" => "Chalice of Benedictus" ),
	array( "id" => "47736", "qual" => "4", "name" => "Icefall Blade" ),
	array( "id" => "47737", "qual" => "4", "name" => "Reckoning" ),
	array( "id" => "47743", "qual" => "4", "name" => "Enlightenment" ),
	array( "id" => "47741", "qual" => "4", "name" => "Baelgun's Heavy Crossbow" ),
	array( "id" => "47740", "qual" => "4", "name" => "The Diplomat" ),
	array( "id" => "47889", "qual" => "4", "name" => "Looming Shadow Wraps" ),
	array( "id" => "49232", "qual" => "4", "name" => "Sandals of the Grieving Soul" ),
	array( "id" => "47891", "qual" => "4", "name" => "Helm of the High Mesa" ),
	array( "id" => "47887", "qual" => "4", "name" => "Vest of Shifting Shadows" ),
	array( "id" => "47893", "qual" => "4", "name" => "Sen'jin Ritualist Gloves" ),
	array( "id" => "47885", "qual" => "4", "name" => "Greaves of the Lingering Vortex" ),
	array( "id" => "47890", "qual" => "4", "name" => "Darkbane Amulet" ),
	array( "id" => "47888", "qual" => "4", "name" => "Band of the Twin Val'kyr" ),
	array( "id" => "47913", "qual" => "4", "name" => "Lightbane Focus" ),
	array( "id" => "47886", "qual" => "4", "name" => "Nemesis Blade" ),
	array( "id" => "47884", "qual" => "4", "name" => "Edge of Agony" ),
	array( "id" => "47892", "qual" => "4", "name" => "Illumination" ),
	array( "id" => "47883", "qual" => "4", "name" => "Widebarrel Flintlock" ),
);
?>