<?php
$loot = array(
	array( "id" => "47095", "qual" => "4", "name" => "Cloak of Displacement" ),
	array( "id" => "47084", "qual" => "4", "name" => "Cord of Biting Cold" ),
	array( "id" => "47097", "qual" => "4", "name" => "Boots of the Mourning Widow" ),
	array( "id" => "47096", "qual" => "4", "name" => "Vestments of the Shattered Fellowship" ),
	array( "id" => "47077", "qual" => "4", "name" => "Treads of the Icewalker" ),
	array( "id" => "47074", "qual" => "4", "name" => "Bracers of the Untold Massacre" ),
	array( "id" => "47087", "qual" => "4", "name" => "Legguards of Concealed Hatred" ),
	array( "id" => "47099", "qual" => "4", "name" => "Boots of Tremoring Earth" ),
	array( "id" => "47086", "qual" => "4", "name" => "Chestplate of the Frostborn Hero" ),
	array( "id" => "47098", "qual" => "4", "name" => "Vambraces of the Broken Bond" ),
	array( "id" => "47076", "qual" => "4", "name" => "Girdle of Bloodied Scars" ),
	array( "id" => "47075", "qual" => "4", "name" => "Ring of Callous Aggression" ),
	array( "id" => "47088", "qual" => "4", "name" => "Satrina's Impeding Scarab" ),
	array( "id" => "47078", "qual" => "4", "name" => "Justicebringer" ),
	array( "id" => "47085", "qual" => "4", "name" => "Bastion of Purity" ),
	array( "id" => "47557", "qual" => "4", "name" => "Regalia of the Grand Conqueror" ),
	array( "id" => "47557", "qual" => "4", "name" => "Regalia of the Grand Conqueror" ),
	array( "id" => "47558", "qual" => "4", "name" => "Regalia of the Grand Protector" ),
	array( "id" => "47452", "qual" => "4", "name" => "Shroud of Displacement" ),
	array( "id" => "47447", "qual" => "4", "name" => "Belt of Biting Cold" ),
	array( "id" => "47454", "qual" => "4", "name" => "Sandals of the Mourning Widow" ),
	array( "id" => "47453", "qual" => "4", "name" => "Robes of the Shattered Fellowship" ),
	array( "id" => "47445", "qual" => "4", "name" => "Icewalker Treads" ),
	array( "id" => "47442", "qual" => "4", "name" => "Bracers of the Silent Massacre" ),
	array( "id" => "47450", "qual" => "4", "name" => "Leggings of Concealed Hatred" ),
	array( "id" => "47456", "qual" => "4", "name" => "Sabatons of Tremoring Earth" ),
	array( "id" => "47449", "qual" => "4", "name" => "Chestplate of the Frostwolf Hero" ),
	array( "id" => "47455", "qual" => "4", "name" => "Bracers of the Broken Bond" ),
	array( "id" => "47444", "qual" => "4", "name" => "Belt of Bloodied Scars" ),
	array( "id" => "47443", "qual" => "4", "name" => "Band of Callous Aggression" ),
	array( "id" => "47451", "qual" => "4", "name" => "Juggernaut's Vitality" ),
	array( "id" => "47446", "qual" => "4", "name" => "Dual-blade Butcher" ),
	array( "id" => "47448", "qual" => "4", "name" => "Bastion of Resolve" ),
	array( "id" => "47557", "qual" => "4", "name" => "Regalia of the Grand Conqueror" ),
	array( "id" => "47557", "qual" => "4", "name" => "Regalia of the Grand Conqueror" ),
	array( "id" => "47558", "qual" => "4", "name" => "Regalia of the Grand Protector" ),
);
?>