<?php
$loot = array(
	array( "id" => "49491", "qual" => "4", "name" => "Flowing Sapphiron Drape" ),
	array( "id" => "49482", "qual" => "4", "name" => "Aurora of Transcendence" ),
	array( "id" => "49483", "qual" => "4", "name" => "Halo of Transcendence" ),
	array( "id" => "49484", "qual" => "4", "name" => "Nemesis Skullcap" ),
	array( "id" => "49481", "qual" => "4", "name" => "Netherwind Crown" ),
	array( "id" => "49477", "qual" => "4", "name" => "Bloodfang Hood" ),
	array( "id" => "49472", "qual" => "4", "name" => "Stormrage Crown" ),
	array( "id" => "49473", "qual" => "4", "name" => "Stormrage Cover" ),
	array( "id" => "49471", "qual" => "4", "name" => "Stormrage Coverlet" ),
	array( "id" => "49469", "qual" => "4", "name" => "Crown of Ten Storms" ),
	array( "id" => "49468", "qual" => "4", "name" => "Helm of Ten Storms" ),
	array( "id" => "49470", "qual" => "4", "name" => "Helmet of Ten Storms" ),
	array( "id" => "49480", "qual" => "4", "name" => "Dragonstalker's Helm" ),
	array( "id" => "49479", "qual" => "4", "name" => "Helm of Wrath" ),
	array( "id" => "49478", "qual" => "4", "name" => "Helmet of Wrath" ),
	array( "id" => "49467", "qual" => "4", "name" => "Frostforged Greathelm" ),
	array( "id" => "49466", "qual" => "4", "name" => "Frostforged Helm" ),
	array( "id" => "49476", "qual" => "4", "name" => "Judgement Crown" ),
	array( "id" => "49475", "qual" => "4", "name" => "Judgement Heaume" ),
	array( "id" => "49474", "qual" => "4", "name" => "Judgement Hood" ),
	array( "id" => "49492", "qual" => "4", "name" => "Eskhandar's Links" ),
	array( "id" => "49489", "qual" => "4", "name" => "Signified Ring of Binding" ),
	array( "id" => "49464", "qual" => "4", "name" => "Shiny Shard of the Flame" ),
	array( "id" => "49488", "qual" => "4", "name" => "Shiny Shard of the Scale" ),
	array( "id" => "49490", "qual" => "4", "name" => "Antediluvian Cornerstone Grimoire" ),
	array( "id" => "49295", "qual" => "4", "name" => "Enlarged Onyxia Hide Backpack" ),
	array( "id" => "49636", "qual" => "4", "name" => "Reins of the Onyxian Drake" ),
	array( "id" => "49294", "qual" => "4", "name" => "Ashen Sack of Gems" ),
	array( "id" => "49494", "qual" => "4", "name" => "Honed Fang of the Mystics" ),
	array( "id" => "49465", "qual" => "4", "name" => "Tarnished Gutgore Ripper" ),
	array( "id" => "49499", "qual" => "4", "name" => "Polished Azuresong Mageblade" ),
	array( "id" => "49495", "qual" => "4", "name" => "Burnished Quel'Serrar" ),
	array( "id" => "49501", "qual" => "4", "name" => "Tempered Vis'kag the Bloodletter" ),
	array( "id" => "49498", "qual" => "4", "name" => "Sharpened Obsidian Edged Blade" ),
	array( "id" => "49500", "qual" => "4", "name" => "Raging Deathbringer" ),
	array( "id" => "49496", "qual" => "4", "name" => "Reinforced Shadowstrike" ),
	array( "id" => "49497", "qual" => "4", "name" => "Reinforced Thunderstrike" ),
	array( "id" => "49493", "qual" => "4", "name" => "Rifled Blastershot Launcher" ),
	array( "id" => "49644", "qual" => "4", "name" => "Head of Onyxia" ),
	array( "id" => "49485", "qual" => "4", "name" => "Sparkling Onyxia Tooth Pendant" ),
	array( "id" => "49486", "qual" => "4", "name" => "Polished Dragonslayer's Signet" ),
	array( "id" => "49487", "qual" => "4", "name" => "Purified Onyxia Blood Talisman" ),
);

?>