<?php
$loot = array(
	array( "id" => "39719", "qual" => "4", "name" => "Mantle of the Locusts" ),
	array( "id" => "39721", "qual" => "4", "name" => "Sash of the Parlor" ),
	array( "id" => "39720", "qual" => "4", "name" => "Leggings of Atrophy" ),
	array( "id" => "39722", "qual" => "4", "name" => "Swarm Bindings" ),
	array( "id" => "39701", "qual" => "4", "name" => "Dawnwalkers" ),
	array( "id" => "39702", "qual" => "4", "name" => "Arachnoid Gold Band" ),
	array( "id" => "39718", "qual" => "4", "name" => "Corpse Scarab Handguards" ),
	array( "id" => "39704", "qual" => "4", "name" => "Pauldrons of Unnatural Death" ),
	array( "id" => "39703", "qual" => "4", "name" => "Rescinding Grips" ),
	array( "id" => "39717", "qual" => "4", "name" => "Inexorable Sabatons" ),
	array( "id" => "39706", "qual" => "4", "name" => "Sabatons of Sudden Reprisal" ),
	array( "id" => "40071", "qual" => "4", "name" => "Chains of Adoration" ),
	array( "id" => "40065", "qual" => "4", "name" => "Fool's Trial" ),
	array( "id" => "40069", "qual" => "4", "name" => "Heritage" ),
	array( "id" => "40064", "qual" => "4", "name" => "Thunderstorm Amulet" ),
	array( "id" => "40080", "qual" => "4", "name" => "Lost Jewel" ),
	array( "id" => "40075", "qual" => "4", "name" => "Ruthlessness" ),
	array( "id" => "40107", "qual" => "4", "name" => "Sand-Worn Band" ),
	array( "id" => "40074", "qual" => "4", "name" => "Strong-Handed Ring" ),
	array( "id" => "39716", "qual" => "4", "name" => "Shield of Assimilation" ),
	array( "id" => "40208", "qual" => "4", "name" => "Cryptfiend's Bite" ),
	array( "id" => "39712", "qual" => "4", "name" => "Gemmed Wand of the Nerubians" ),
	array( "id" => "39714", "qual" => "4", "name" => "Webbed Death" ),
);
?>