<?php
$loot = array(
	array( "id" => "40381", "qual" => "4", "name" => "Sympathy" ),
	array( "id" => "40380", "qual" => "4", "name" => "Gloves of Grandeur" ),
	array( "id" => "40376", "qual" => "4", "name" => "Legwraps of the Defeated Dragon" ),
	array( "id" => "40362", "qual" => "4", "name" => "Gloves of Fast Reactions" ),
	array( "id" => "40379", "qual" => "4", "name" => "Legguards of the Boneyard" ),
	array( "id" => "40367", "qual" => "4", "name" => "Boots of the Great Construct" ),
	array( "id" => "40366", "qual" => "4", "name" => "Platehelm of the Great Wyrm" ),
	array( "id" => "40377", "qual" => "4", "name" => "Noble Birthright Pauldrons" ),
	array( "id" => "40365", "qual" => "4", "name" => "Breastplate of Frozen Pain" ),
	array( "id" => "40363", "qual" => "4", "name" => "Bone-Inlaid Legguards" ),
	array( "id" => "40378", "qual" => "4", "name" => "Ceaseless Pity" ),
	array( "id" => "40374", "qual" => "4", "name" => "Cosmic Lights" ),
	array( "id" => "40369", "qual" => "4", "name" => "Icy Blast Amulet" ),
	array( "id" => "40370", "qual" => "4", "name" => "Gatekeeper" ),
	array( "id" => "40375", "qual" => "4", "name" => "Ring of Decaying Beauty" ),
	array( "id" => "40371", "qual" => "4", "name" => "Bandit's Insignia" ),
	array( "id" => "40373", "qual" => "4", "name" => "Extract of Necromantic Power" ),
	array( "id" => "40372", "qual" => "4", "name" => "Rune of Repulsion" ),
	array( "id" => "40382", "qual" => "4", "name" => "Soul of the Dead" ),
	array( "id" => "40368", "qual" => "4", "name" => "Murder" ),
	array( "id" => "44577", "qual" => "4", "name" => "Heroic Key to the Focusing Iris" ),
	array( "id" => "44581", "qual" => "4", "name" => "Heroic Key to the Focusing Iris" ),
);
?>