<?php
$loot = array(
	array( "id" => "39272", "qual" => "4", "name" => "Drape of Surgery" ),
	array( "id" => "39284", "qual" => "4", "name" => "Miasma Mantle" ),
	array( "id" => "39396", "qual" => "4", "name" => "Gown of Blaumeux" ),
	array( "id" => "39309", "qual" => "4", "name" => "Leggings of the Instructor" ),
	array( "id" => "39237", "qual" => "4", "name" => "Spaulders of Resumed Battle" ),
	array( "id" => "39279", "qual" => "4", "name" => "Blistered Belt of Decay" ),
	array( "id" => "39191", "qual" => "4", "name" => "Splint-Bound Leggings" ),
	array( "id" => "39215", "qual" => "4", "name" => "Boots of the Follower" ),
	array( "id" => "39294", "qual" => "4", "name" => "Arc-Scorched Helmet" ),
	array( "id" => "39248", "qual" => "4", "name" => "Tunic of the Lost Pack" ),
	array( "id" => "39194", "qual" => "4", "name" => "Rusted-Link Spiked Gauntlets" ),
	array( "id" => "39251", "qual" => "4", "name" => "Necrogenic Belt" ),
	array( "id" => "39379", "qual" => "4", "name" => "Spectral Rider's Girdle" ),
	array( "id" => "39188", "qual" => "4", "name" => "Chivalric Chestguard" ),
	array( "id" => "39345", "qual" => "4", "name" => "Girdle of the Ascended Phantom" ),
	array( "id" => "39146", "qual" => "4", "name" => "Collar of Dissolution" ),
	array( "id" => "39232", "qual" => "4", "name" => "Pendant of Lost Vocations" ),
	array( "id" => "39193", "qual" => "4", "name" => "Band of Neglected Pleas" ),
	array( "id" => "39388", "qual" => "4", "name" => "Spirit-World Glass" ),
	array( "id" => "39344", "qual" => "4", "name" => "Slayer of the Lifeless" ),
	array( "id" => "39281", "qual" => "4", "name" => "Infection Repulser" ),
	array( "id" => "39200", "qual" => "4", "name" => "Grieving Spellblade" ),
	array( "id" => "39394", "qual" => "4", "name" => "Charmed Cierge" ),
	array( "id" => "40622", "qual" => "4", "name" => "Spaulders of the Lost Conqueror" ),
	array( "id" => "40623", "qual" => "4", "name" => "Spaulders of the Lost Protector" ),
	array( "id" => "40624", "qual" => "4", "name" => "Spaulders of the Lost Vanquisher" ),
	array( "id" => "40610", "qual" => "4", "name" => "Chestguard of the Lost Conqueror" ),
	array( "id" => "40611", "qual" => "4", "name" => "Chestguard of the Lost Protector" ),
	array( "id" => "40612", "qual" => "4", "name" => "Chestguard of the Lost Vanquisher" ),
	array( "id" => "40619", "qual" => "4", "name" => "Leggings of the Lost Conqueror" ),
	array( "id" => "40620", "qual" => "4", "name" => "Leggings of the Lost Protector" ),
	array( "id" => "40621", "qual" => "4", "name" => "Leggings of the Lost Vanquisher" ),
);
?>