<?php
if($this->get_faction() == 'alliance'){
$loot = array(
	array( "id" => "47752", "qual" => "4", "name" => "Khadgar's Gauntlets of Conquest" ),
	array( "id" => "47750", "qual" => "4", "name" => "Khadgar's Leggings of Conquest" ),
	array( "id" => "47982", "qual" => "4", "name" => "Velen's Gloves of Conquest" ),
	array( "id" => "47980", "qual" => "4", "name" => "Velen's Leggings of Conquest" ),
	array( "id" => "48072", "qual" => "4", "name" => "Velen's Handwraps of Conquest" ),
	array( "id" => "48074", "qual" => "4", "name" => "Velen's Pants of Conquest" ),
	array( "id" => "47783", "qual" => "4", "name" => "Kel'Thuzad's Gloves of Conquest" ),
	array( "id" => "47785", "qual" => "4", "name" => "Kel'Thuzad's Leggings of Conquest" ),
	array( "id" => "41971", "qual" => "4", "name" => "Furious Gladiator's Silk Handguards" ),
	array( "id" => "41959", "qual" => "4", "name" => "Furious Gladiator's Silk Trousers" ),
	array( "id" => "41874", "qual" => "4", "name" => "Furious Gladiator's Mooncloth Gloves" ),
	array( "id" => "41864", "qual" => "4", "name" => "Furious Gladiator's Mooncloth Leggings" ),
	array( "id" => "41940", "qual" => "4", "name" => "Furious Gladiator's Satin Gloves" ),
	array( "id" => "41927", "qual" => "4", "name" => "Furious Gladiator's Satin Leggings" ),
	array( "id" => "42017", "qual" => "4", "name" => "Furious Gladiator's Felweave Handguards" ),
	array( "id" => "42005", "qual" => "4", "name" => "Furious Gladiator's Felweave Trousers" ),
	array( "id" => "48162", "qual" => "4", "name" => "Malfurion's Gloves of Conquest" ),
	array( "id" => "48160", "qual" => "4", "name" => "Malfurion's Trousers of Conquest" ),
	array( "id" => "48213", "qual" => "4", "name" => "Malfurion's Handgrips of Conquest" ),
	array( "id" => "48215", "qual" => "4", "name" => "Malfurion's Legguards of Conquest" ),
	array( "id" => "48132", "qual" => "4", "name" => "Malfurion's Handguards of Conquest" ),
	array( "id" => "48130", "qual" => "4", "name" => "Malfurion's Leggings of Conquest" ),
	array( "id" => "48222", "qual" => "4", "name" => "VanCleef's Gauntlets of Conquest" ),
	array( "id" => "48220", "qual" => "4", "name" => "VanCleef's Legplates of Conquest" ),
	array( "id" => "41293", "qual" => "4", "name" => "Furious Gladiator's Wyrmhide Gloves" ),
	array( "id" => "41304", "qual" => "4", "name" => "Furious Gladiator's Wyrmhide Legguards" ),
	array( "id" => "41773", "qual" => "4", "name" => "Furious Gladiator's Dragonhide Gloves" ),
	array( "id" => "41667", "qual" => "4", "name" => "Furious Gladiator's Dragonhide Legguards" ),
	array( "id" => "41287", "qual" => "4", "name" => "Furious Gladiator's Kodohide Gloves" ),
	array( "id" => "41298", "qual" => "4", "name" => "Furious Gladiator's Kodohide Legguards" ),
	array( "id" => "41767", "qual" => "4", "name" => "Furious Gladiator's Leather Gloves" ),
	array( "id" => "41655", "qual" => "4", "name" => "Furious Gladiator's Leather Legguards" ),
	array( "id" => "48254", "qual" => "4", "name" => "Windrunner's Handguards of Conquest" ),
	array( "id" => "48252", "qual" => "4", "name" => "Windrunner's Legguards of Conquest" ),
	array( "id" => "48312", "qual" => "4", "name" => "Nobundo's Gloves of Conquest" ),
	array( "id" => "48314", "qual" => "4", "name" => "Nobundo's Kilt of Conquest" ),
	array( "id" => "48342", "qual" => "4", "name" => "Nobundo's Grips of Conquest" ),
	array( "id" => "48344", "qual" => "4", "name" => "Nobundo's War-Kilt of Conquest" ),
	array( "id" => "48284", "qual" => "4", "name" => "Nobundo's Handguards of Conquest" ),
	array( "id" => "48282", "qual" => "4", "name" => "Nobundo's Legguards of Conquest" ),
	array( "id" => "41143", "qual" => "4", "name" => "Furious Gladiator's Chain Gauntlets" ),
	array( "id" => "41205", "qual" => "4", "name" => "Furious Gladiator's Chain Leggings" ),
	array( "id" => "41007", "qual" => "4", "name" => "Furious Gladiator's Mail Gauntlets" ),
	array( "id" => "41033", "qual" => "4", "name" => "Furious Gladiator's Mail Leggings" ),
	array( "id" => "41137", "qual" => "4", "name" => "Furious Gladiator's Linked Gauntlets" ),
	array( "id" => "41199", "qual" => "4", "name" => "Furious Gladiator's Linked Leggings" ),
	array( "id" => "41001", "qual" => "4", "name" => "Furious Gladiator's Ringmail Gauntlets" ),
	array( "id" => "41027", "qual" => "4", "name" => "Furious Gladiator's Ringmail Leggings" ),
	array( "id" => "48480", "qual" => "4", "name" => "Thassarian's Gauntlets of Conquest" ),
	array( "id" => "48476", "qual" => "4", "name" => "Thassarian's Legplates of Conquest" ),
	array( "id" => "48537", "qual" => "4", "name" => "Thassarian's Handguards of Conquest" ),
	array( "id" => "48533", "qual" => "4", "name" => "Thassarian's Legguards of Conquest" ),
	array( "id" => "48574", "qual" => "4", "name" => "Turalyon's Gloves of Conquest" ),
	array( "id" => "48568", "qual" => "4", "name" => "Turalyon's Greaves of Conquest" ),
	array( "id" => "48603", "qual" => "4", "name" => "Turalyon's Gauntlets of Conquest" ),
	array( "id" => "48605", "qual" => "4", "name" => "Turalyon's Legplates of Conquest" ),
	array( "id" => "40809", "qual" => "4", "name" => "Furious Gladiator's Dreadplate Gauntlets" ),
	array( "id" => "40848", "qual" => "4", "name" => "Furious Gladiator's Dreadplate Legguards" ),
	array( "id" => "40927", "qual" => "4", "name" => "Furious Gladiator's Ornamented Gloves" ),
	array( "id" => "40939", "qual" => "4", "name" => "Furious Gladiator's Ornamented Legplates" ),
	array( "id" => "40808", "qual" => "4", "name" => "Furious Gladiator's Scaled Gauntlets" ),
	array( "id" => "40849", "qual" => "4", "name" => "Furious Gladiator's Scaled Legguards" ),
	array( "id" => "48633", "qual" => "4", "name" => "Turalyon's Handguards of Conquest" ),
	array( "id" => "48635", "qual" => "4", "name" => "Turalyon's Legguards of Conquest" ),
	array( "id" => "48375", "qual" => "4", "name" => "Wrynn's Gauntlets of Conquest" ),
	array( "id" => "48373", "qual" => "4", "name" => "Wrynn's Legplates of Conquest" ),
	array( "id" => "48449", "qual" => "4", "name" => "Wrynn's Handguards of Conquest" ),
	array( "id" => "48445", "qual" => "4", "name" => "Wrynn's Legguards of Conquest" ),
	array( "id" => "40807", "qual" => "4", "name" => "Furious Gladiator's Plate Gauntlets" ),
	array( "id" => "40847", "qual" => "4", "name" => "Furious Gladiator's Plate Legguards" ),
	array( "id" => "41909", "qual" => "4", "name" => "Furious Gladiator's Cuffs of Dominance" ),
	array( "id" => "41898", "qual" => "4", "name" => "Furious Gladiator's Cord of Dominance" ),
	array( "id" => "41903", "qual" => "4", "name" => "Furious Gladiator's Slippers of Dominance" ),
	array( "id" => "41893", "qual" => "4", "name" => "Furious Gladiator's Cuffs of Salvation" ),
	array( "id" => "41881", "qual" => "4", "name" => "Furious Gladiator's Cord of Salvation" ),
	array( "id" => "41885", "qual" => "4", "name" => "Furious Gladiator's Slippers of Salvation" ),
	array( "id" => "41640", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Dominance" ),
	array( "id" => "41630", "qual" => "4", "name" => "Furious Gladiator's Belt of Dominance" ),
	array( "id" => "41635", "qual" => "4", "name" => "Furious Gladiator's Boots of Dominance" ),
	array( "id" => "41625", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Salvation" ),
	array( "id" => "41617", "qual" => "4", "name" => "Furious Gladiator's Belt of Salvation" ),
	array( "id" => "41621", "qual" => "4", "name" => "Furious Gladiator's Boots of Salvation" ),
	array( "id" => "41840", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Triumph" ),
	array( "id" => "41832", "qual" => "4", "name" => "Furious Gladiator's Belt of Triumph" ),
	array( "id" => "41836", "qual" => "4", "name" => "Furious Gladiator's Boots of Triumph" ),
	array( "id" => "41065", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Dominance" ),
	array( "id" => "41070", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Dominance" ),
	array( "id" => "41075", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Dominance" ),
	array( "id" => "41060", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Salvation" ),
	array( "id" => "41051", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Salvation" ),
	array( "id" => "41055", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Salvation" ),
	array( "id" => "41225", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Triumph" ),
	array( "id" => "41235", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Triumph" ),
	array( "id" => "41230", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Triumph" ),
	array( "id" => "40983", "qual" => "4", "name" => "Furious Gladiator's Bracers of Salvation" ),
	array( "id" => "40976", "qual" => "4", "name" => "Furious Gladiator's Girdle of Salvation" ),
	array( "id" => "40977", "qual" => "4", "name" => "Furious Gladiator's Greaves of Salvation" ),
	array( "id" => "40889", "qual" => "4", "name" => "Furious Gladiator's Bracers of Triumph" ),
	array( "id" => "40881", "qual" => "4", "name" => "Furious Gladiator's Girdle of Triumph" ),
	array( "id" => "40882", "qual" => "4", "name" => "Furious Gladiator's Greaves of Triumph" ),
	array( "id" => "42071", "qual" => "4", "name" => "Furious Gladiator's Cloak of Ascendancy" ),
	array( "id" => "42073", "qual" => "4", "name" => "Furious Gladiator's Cloak of Deliverance" ),
	array( "id" => "42069", "qual" => "4", "name" => "Furious Gladiator's Cloak of Dominance" ),
	array( "id" => "42072", "qual" => "4", "name" => "Furious Gladiator's Cloak of Salvation" ),
	array( "id" => "42070", "qual" => "4", "name" => "Furious Gladiator's Cloak of Subjugation" ),
	array( "id" => "42074", "qual" => "4", "name" => "Furious Gladiator's Cloak of Triumph" ),
	array( "id" => "42075", "qual" => "4", "name" => "Furious Gladiator's Cloak of Victory" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem of Triumph" ),
	array( "id" => "43959", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "44083", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "42037", "qual" => "4", "name" => "Furious Gladiator's Pendant of Ascendancy" ),
	array( "id" => "42039", "qual" => "4", "name" => "Furious Gladiator's Pendant of Deliverance" ),
	array( "id" => "42036", "qual" => "4", "name" => "Furious Gladiator's Pendant of Dominance" ),
	array( "id" => "42040", "qual" => "4", "name" => "Furious Gladiator's Pendant of Salvation" ),
	array( "id" => "42038", "qual" => "4", "name" => "Furious Gladiator's Pendant of Subjugation" ),
	array( "id" => "46373", "qual" => "4", "name" => "Furious Gladiator's Pendant of Sundering" ),
	array( "id" => "42034", "qual" => "4", "name" => "Furious Gladiator's Pendant of Triumph" ),
	array( "id" => "42035", "qual" => "4", "name" => "Furious Gladiator's Pendant of Victory" ),
	array( "id" => "42116", "qual" => "4", "name" => "Furious Gladiator's Band of Dominance" ),
	array( "id" => "42117", "qual" => "4", "name" => "Furious Gladiator's Band of Triumph" ),
);
}else{
$loot = array(
	array( "id" => "47773", "qual" => "4", "name" => "Sunstrider's Gauntlets of Conquest" ),
	array( "id" => "47775", "qual" => "4", "name" => "Sunstrider's Leggings of Conquest" ),
	array( "id" => "48067", "qual" => "4", "name" => "Zabra's Gloves of Conquest" ),
	array( "id" => "48069", "qual" => "4", "name" => "Zabra's Leggings of Conquest" ),
	array( "id" => "48097", "qual" => "4", "name" => "Zabra's Handwraps of Conquest" ),
	array( "id" => "48099", "qual" => "4", "name" => "Zabra's Pants of Conquest" ),
	array( "id" => "47802", "qual" => "4", "name" => "Gul'dan's Gloves of Conquest" ),
	array( "id" => "47800", "qual" => "4", "name" => "Gul'dan's Leggings of Conquest" ),
	array( "id" => "41971", "qual" => "4", "name" => "Furious Gladiator's Silk Handguards" ),
	array( "id" => "41959", "qual" => "4", "name" => "Furious Gladiator's Silk Trousers" ),
	array( "id" => "41874", "qual" => "4", "name" => "Furious Gladiator's Mooncloth Gloves" ),
	array( "id" => "41864", "qual" => "4", "name" => "Furious Gladiator's Mooncloth Leggings" ),
	array( "id" => "41940", "qual" => "4", "name" => "Furious Gladiator's Satin Gloves" ),
	array( "id" => "41927", "qual" => "4", "name" => "Furious Gladiator's Satin Leggings" ),
	array( "id" => "42017", "qual" => "4", "name" => "Furious Gladiator's Felweave Handguards" ),
	array( "id" => "42005", "qual" => "4", "name" => "Furious Gladiator's Felweave Trousers" ),
	array( "id" => "48183", "qual" => "4", "name" => "Runetotem's Gloves of Conquest" ),
	array( "id" => "48185", "qual" => "4", "name" => "Runetotem's Trousers of Conquest" ),
	array( "id" => "48192", "qual" => "4", "name" => "Runetotem's Handgrips of Conquest" ),
	array( "id" => "48190", "qual" => "4", "name" => "Runetotem's Legguards of Conquest" ),
	array( "id" => "48153", "qual" => "4", "name" => "Runetotem's Handguards of Conquest" ),
	array( "id" => "48155", "qual" => "4", "name" => "Runetotem's Leggings of Conquest" ),
	array( "id" => "48244", "qual" => "4", "name" => "Garona's Gauntlets of Conquest" ),
	array( "id" => "48246", "qual" => "4", "name" => "Garona's Legplates of Conquest" ),
	array( "id" => "41293", "qual" => "4", "name" => "Furious Gladiator's Wyrmhide Gloves" ),
	array( "id" => "41304", "qual" => "4", "name" => "Furious Gladiator's Wyrmhide Legguards" ),
	array( "id" => "41773", "qual" => "4", "name" => "Furious Gladiator's Dragonhide Gloves" ),
	array( "id" => "41667", "qual" => "4", "name" => "Furious Gladiator's Dragonhide Legguards" ),
	array( "id" => "41287", "qual" => "4", "name" => "Furious Gladiator's Kodohide Gloves" ),
	array( "id" => "41298", "qual" => "4", "name" => "Furious Gladiator's Kodohide Legguards" ),
	array( "id" => "41767", "qual" => "4", "name" => "Furious Gladiator's Leather Gloves" ),
	array( "id" => "41655", "qual" => "4", "name" => "Furious Gladiator's Leather Legguards" ),
	array( "id" => "48276", "qual" => "4", "name" => "Windrunner's Handguards of Conquest" ),
	array( "id" => "48278", "qual" => "4", "name" => "Windrunner's Legguards of Conquest" ),
	array( "id" => "48337", "qual" => "4", "name" => "Thrall's Gloves of Conquest" ),
	array( "id" => "48339", "qual" => "4", "name" => "Thrall's Kilt of Conquest" ),
	array( "id" => "48367", "qual" => "4", "name" => "Thrall's Grips of Conquest" ),
	array( "id" => "48369", "qual" => "4", "name" => "Thrall's War-Kilt of Conquest" ),
	array( "id" => "48296", "qual" => "4", "name" => "Thrall's Handguards of Conquest" ),
	array( "id" => "48298", "qual" => "4", "name" => "Thrall's Legguards of Conquest" ),
	array( "id" => "41143", "qual" => "4", "name" => "Furious Gladiator's Chain Gauntlets" ),
	array( "id" => "41205", "qual" => "4", "name" => "Furious Gladiator's Chain Leggings" ),
	array( "id" => "41007", "qual" => "4", "name" => "Furious Gladiator's Mail Gauntlets" ),
	array( "id" => "41033", "qual" => "4", "name" => "Furious Gladiator's Mail Leggings" ),
	array( "id" => "41137", "qual" => "4", "name" => "Furious Gladiator's Linked Gauntlets" ),
	array( "id" => "41199", "qual" => "4", "name" => "Furious Gladiator's Linked Leggings" ),
	array( "id" => "41001", "qual" => "4", "name" => "Furious Gladiator's Ringmail Gauntlets" ),
	array( "id" => "41027", "qual" => "4", "name" => "Furious Gladiator's Ringmail Leggings" ),
	array( "id" => "48502", "qual" => "4", "name" => "Koltira's Gauntlets of Conquest" ),
	array( "id" => "48504", "qual" => "4", "name" => "Koltira's Legplates of Conquest" ),
	array( "id" => "48559", "qual" => "4", "name" => "Koltira's Handguards of Conquest" ),
	array( "id" => "48561", "qual" => "4", "name" => "Koltira's Legguards of Conquest" ),
	array( "id" => "48598", "qual" => "4", "name" => "Liadrin's Gloves of Conquest" ),
	array( "id" => "48596", "qual" => "4", "name" => "Liadrin's Greaves of Conquest" ),
	array( "id" => "48630", "qual" => "4", "name" => "Liadrin's Gauntlets of Conquest" ),
	array( "id" => "48628", "qual" => "4", "name" => "Liadrin's Legplates of Conquest" ),
	array( "id" => "40809", "qual" => "4", "name" => "Furious Gladiator's Dreadplate Gauntlets" ),
	array( "id" => "40848", "qual" => "4", "name" => "Furious Gladiator's Dreadplate Legguards" ),
	array( "id" => "40927", "qual" => "4", "name" => "Furious Gladiator's Ornamented Gloves" ),
	array( "id" => "40939", "qual" => "4", "name" => "Furious Gladiator's Ornamented Legplates" ),
	array( "id" => "40808", "qual" => "4", "name" => "Furious Gladiator's Scaled Gauntlets" ),
	array( "id" => "40849", "qual" => "4", "name" => "Furious Gladiator's Scaled Legguards" ),
	array( "id" => "48653", "qual" => "4", "name" => "Liadrin's Handguards of Conquest" ),
	array( "id" => "48655", "qual" => "4", "name" => "Liadrin's Legguards of Conquest" ),
	array( "id" => "48387", "qual" => "4", "name" => "Hellscream's Gauntlets of Conquest" ),
	array( "id" => "48389", "qual" => "4", "name" => "Hellscream's Legplates of Conquest" ),
	array( "id" => "48457", "qual" => "4", "name" => "Hellscream's Handguards of Conquest" ),
	array( "id" => "48459", "qual" => "4", "name" => "Hellscream's Legguards of Conquest" ),
	array( "id" => "40807", "qual" => "4", "name" => "Furious Gladiator's Plate Gauntlets" ),
	array( "id" => "40847", "qual" => "4", "name" => "Furious Gladiator's Plate Legguards" ),
	array( "id" => "41909", "qual" => "4", "name" => "Furious Gladiator's Cuffs of Dominance" ),
	array( "id" => "41898", "qual" => "4", "name" => "Furious Gladiator's Cord of Dominance" ),
	array( "id" => "41903", "qual" => "4", "name" => "Furious Gladiator's Slippers of Dominance" ),
	array( "id" => "41893", "qual" => "4", "name" => "Furious Gladiator's Cuffs of Salvation" ),
	array( "id" => "41881", "qual" => "4", "name" => "Furious Gladiator's Cord of Salvation" ),
	array( "id" => "41885", "qual" => "4", "name" => "Furious Gladiator's Slippers of Salvation" ),
	array( "id" => "41640", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Dominance" ),
	array( "id" => "41630", "qual" => "4", "name" => "Furious Gladiator's Belt of Dominance" ),
	array( "id" => "41635", "qual" => "4", "name" => "Furious Gladiator's Boots of Dominance" ),
	array( "id" => "41625", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Salvation" ),
	array( "id" => "41617", "qual" => "4", "name" => "Furious Gladiator's Belt of Salvation" ),
	array( "id" => "41621", "qual" => "4", "name" => "Furious Gladiator's Boots of Salvation" ),
	array( "id" => "41840", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Triumph" ),
	array( "id" => "41832", "qual" => "4", "name" => "Furious Gladiator's Belt of Triumph" ),
	array( "id" => "41836", "qual" => "4", "name" => "Furious Gladiator's Boots of Triumph" ),
	array( "id" => "41065", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Dominance" ),
	array( "id" => "41070", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Dominance" ),
	array( "id" => "41075", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Dominance" ),
	array( "id" => "41060", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Salvation" ),
	array( "id" => "41051", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Salvation" ),
	array( "id" => "41055", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Salvation" ),
	array( "id" => "41225", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Triumph" ),
	array( "id" => "41235", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Triumph" ),
	array( "id" => "41230", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Triumph" ),
	array( "id" => "40983", "qual" => "4", "name" => "Furious Gladiator's Bracers of Salvation" ),
	array( "id" => "40976", "qual" => "4", "name" => "Furious Gladiator's Girdle of Salvation" ),
	array( "id" => "40977", "qual" => "4", "name" => "Furious Gladiator's Greaves of Salvation" ),
	array( "id" => "40889", "qual" => "4", "name" => "Furious Gladiator's Bracers of Triumph" ),
	array( "id" => "40881", "qual" => "4", "name" => "Furious Gladiator's Girdle of Triumph" ),
	array( "id" => "40882", "qual" => "4", "name" => "Furious Gladiator's Greaves of Triumph" ),
	array( "id" => "42071", "qual" => "4", "name" => "Furious Gladiator's Cloak of Ascendancy" ),
	array( "id" => "42073", "qual" => "4", "name" => "Furious Gladiator's Cloak of Deliverance" ),
	array( "id" => "42069", "qual" => "4", "name" => "Furious Gladiator's Cloak of Dominance" ),
	array( "id" => "42072", "qual" => "4", "name" => "Furious Gladiator's Cloak of Salvation" ),
	array( "id" => "42070", "qual" => "4", "name" => "Furious Gladiator's Cloak of Subjugation" ),
	array( "id" => "42074", "qual" => "4", "name" => "Furious Gladiator's Cloak of Triumph" ),
	array( "id" => "42075", "qual" => "4", "name" => "Furious Gladiator's Cloak of Victory" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem of Triumph" ),
	array( "id" => "43959", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "44083", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "42037", "qual" => "4", "name" => "Furious Gladiator's Pendant of Ascendancy" ),
	array( "id" => "42039", "qual" => "4", "name" => "Furious Gladiator's Pendant of Deliverance" ),
	array( "id" => "42036", "qual" => "4", "name" => "Furious Gladiator's Pendant of Dominance" ),
	array( "id" => "42040", "qual" => "4", "name" => "Furious Gladiator's Pendant of Salvation" ),
	array( "id" => "42038", "qual" => "4", "name" => "Furious Gladiator's Pendant of Subjugation" ),
	array( "id" => "46373", "qual" => "4", "name" => "Furious Gladiator's Pendant of Sundering" ),
	array( "id" => "42034", "qual" => "4", "name" => "Furious Gladiator's Pendant of Triumph" ),
	array( "id" => "42035", "qual" => "4", "name" => "Furious Gladiator's Pendant of Victory" ),
	array( "id" => "42116", "qual" => "4", "name" => "Furious Gladiator's Band of Dominance" ),
	array( "id" => "42117", "qual" => "4", "name" => "Furious Gladiator's Band of Triumph" ),
);
}

?>