<?php
$loot = array(
	array( "id" => "40247", "qual" => "4", "name" => "Cowl of Innocent Delight" ),
	array( "id" => "40289", "qual" => "4", "name" => "Sympathetic Amice" ),
	array( "id" => "40602", "qual" => "4", "name" => "Robes of Mutation" ),
	array( "id" => "39733", "qual" => "4", "name" => "Gloves of Token Respect" ),
	array( "id" => "40303", "qual" => "4", "name" => "Wraps of the Persecuted" ),
	array( "id" => "40326", "qual" => "4", "name" => "Boots of Forlorn Wishes" ),
	array( "id" => "40296", "qual" => "4", "name" => "Cover of Silence" ),
	array( "id" => "39768", "qual" => "4", "name" => "Cowl of the Perished" ),
	array( "id" => "40319", "qual" => "4", "name" => "Chestpiece of Suspicion" ),
	array( "id" => "40260", "qual" => "4", "name" => "Belt of the Tortured" ),
	array( "id" => "40205", "qual" => "4", "name" => "Stalk-Skin Belt" ),
	array( "id" => "40270", "qual" => "4", "name" => "Boots of Septic Wounds" ),
	array( "id" => "40193", "qual" => "4", "name" => "Tunic of Masked Suffering" ),
	array( "id" => "40209", "qual" => "4", "name" => "Bindings of the Decrepit" ),
	array( "id" => "40302", "qual" => "4", "name" => "Benefactor's Gauntlets" ),
	array( "id" => "39718", "qual" => "4", "name" => "Corpse Scarab Handguards" ),
	array( "id" => "40242", "qual" => "4", "name" => "Grotesque Handgrips" ),
	array( "id" => "39760", "qual" => "4", "name" => "Helm of Diminished Pride" ),
	array( "id" => "40185", "qual" => "4", "name" => "Shoulderguards of Opportunity" ),
	array( "id" => "40203", "qual" => "4", "name" => "Breastplate of Tormented Rage" ),
	array( "id" => "40332", "qual" => "4", "name" => "Abetment Bracers" ),
	array( "id" => "40188", "qual" => "4", "name" => "Gauntlets of the Disobedient" ),
	array( "id" => "40259", "qual" => "4", "name" => "Waistguard of Divine Grace" ),
	array( "id" => "40204", "qual" => "4", "name" => "Legguards of the Apostle" ),
	array( "id" => "39717", "qual" => "4", "name" => "Inexorable Sabatons" ),
	array( "id" => "40206", "qual" => "4", "name" => "Iron-Spring Jumpers" ),
	array( "id" => "40297", "qual" => "4", "name" => "Sabatons of Endurance" ),
	array( "id" => "40350", "qual" => "4", "name" => "Urn of Lost Memories" ),
	array( "id" => "40191", "qual" => "4", "name" => "Libram of Radiance" ),
	array( "id" => "39716", "qual" => "4", "name" => "Shield of Assimilation" ),
	array( "id" => "40281", "qual" => "4", "name" => "Twilight Mist" ),
	array( "id" => "39714", "qual" => "4", "name" => "Webbed Death" ),
	array( "id" => "39730", "qual" => "4", "name" => "Widow's Fury" ),
	array( "id" => "40239", "qual" => "4", "name" => "The Hand of Nerub" ),
	array( "id" => "40280", "qual" => "4", "name" => "Origin of Nightmares" ),
	array( "id" => "40343", "qual" => "4", "name" => "Armageddon" ),
	array( "id" => "40265", "qual" => "4", "name" => "Arrowsong" ),
	array( "id" => "40346", "qual" => "4", "name" => "Final Voyage" ),
	array( "id" => "40637", "qual" => "4", "name" => "Mantle of the Lost Conqueror" ),
	array( "id" => "40638", "qual" => "4", "name" => "Mantle of the Lost Protector" ),
	array( "id" => "40639", "qual" => "4", "name" => "Mantle of the Lost Vanquisher" ),
	array( "id" => "40625", "qual" => "4", "name" => "Breastplate of the Lost Conqueror" ),
	array( "id" => "40626", "qual" => "4", "name" => "Breastplate of the Lost Protector" ),
	array( "id" => "40627", "qual" => "4", "name" => "Breastplate of the Lost Vanquisher" ),
	array( "id" => "40634", "qual" => "4", "name" => "Legplates of the Lost Conqueror" ),
	array( "id" => "40635", "qual" => "4", "name" => "Legplates of the Lost Protector" ),
	array( "id" => "40636", "qual" => "4", "name" => "Legplates of the Lost Vanquisher" ),
);
?>