<?php
$loot = array(
	array( "id" => "47974", "qual" => "4", "name" => "Vestments of the Sleepless" ),
	array( "id" => "47977", "qual" => "4", "name" => "Cinch of the Undying" ),
	array( "id" => "47972", "qual" => "4", "name" => "Spaulders of the Snow Bandit" ),
	array( "id" => "47965", "qual" => "4", "name" => "Headpiece of the Crypt Lord" ),
	array( "id" => "47969", "qual" => "4", "name" => "Pauldrons of the Timeless Hunter" ),
	array( "id" => "47964", "qual" => "4", "name" => "Chestguard of the Warden" ),
	array( "id" => "47976", "qual" => "4", "name" => "Legplates of the Immortal Spider" ),
	array( "id" => "47970", "qual" => "4", "name" => "Legplates of the Silver Hand" ),
	array( "id" => "47967", "qual" => "4", "name" => "Crusader's Glory" ),
	array( "id" => "47971", "qual" => "4", "name" => "Westfall Saber" ),
	array( "id" => "47966", "qual" => "4", "name" => "The Lion's Maw" ),
	array( "id" => "47962", "qual" => "4", "name" => "Argent Resolve" ),
	array( "id" => "47973", "qual" => "4", "name" => "The Grinder" ),
	array( "id" => "47979", "qual" => "4", "name" => "Fordragon Blades" ),
	array( "id" => "47968", "qual" => "4", "name" => "Cold Convergence" ),
	array( "id" => "47978", "qual" => "4", "name" => "Bulwark of the Royal Guard" ),
	array( "id" => "47963", "qual" => "4", "name" => "Vigilant Ward" ),
	array( "id" => "47975", "qual" => "4", "name" => "Baelgun's Heavy Crossbow" ),
	array( "id" => "48051", "qual" => "4", "name" => "Robes of the Sleepless" ),
	array( "id" => "48054", "qual" => "4", "name" => "Belt of the Eternal" ),
	array( "id" => "48049", "qual" => "4", "name" => "Shoulderpads of the Snow Bandit" ),
	array( "id" => "48042", "qual" => "4", "name" => "Helm of the Crypt Lord" ),
	array( "id" => "48046", "qual" => "4", "name" => "Pauldrons of the Shadow Hunter" ),
	array( "id" => "48041", "qual" => "4", "name" => "Stoneskin Chestplate" ),
	array( "id" => "48047", "qual" => "4", "name" => "Legplates of the Redeemed Blood Knight" ),
	array( "id" => "48053", "qual" => "4", "name" => "Sunwalker Legguards" ),
	array( "id" => "48044", "qual" => "4", "name" => "Ardent Guard" ),
	array( "id" => "48048", "qual" => "4", "name" => "Forsaken Bonecarver" ),
	array( "id" => "48043", "qual" => "4", "name" => "Frostblade Hatchet" ),
	array( "id" => "48039", "qual" => "4", "name" => "Mace of the Earthborn Chieftain" ),
	array( "id" => "48050", "qual" => "4", "name" => "Blackhorn Bludgeon" ),
	array( "id" => "48056", "qual" => "4", "name" => "Anguish" ),
	array( "id" => "48045", "qual" => "4", "name" => "Perdition" ),
	array( "id" => "48055", "qual" => "4", "name" => "Aegis of the Coliseum" ),
	array( "id" => "48040", "qual" => "4", "name" => "Pride of the Kor'kron" ),
	array( "id" => "48052", "qual" => "4", "name" => "Darkmaw Crossbow" ),
);
?>