<?php
if($this->get_faction() == 'alliance'){
$loot = array(
	array( "id" => "47238", "qual" => "4", "name" => "Maiden's Favor" ),
	array( "id" => "47192", "qual" => "4", "name" => "Strength of the Nerub" ),
	array( "id" => "47208", "qual" => "4", "name" => "Armbands of the Ashen Saint" ),
	array( "id" => "47236", "qual" => "4", "name" => "Gloves of the Lifeless Touch" ),
	array( "id" => "47189", "qual" => "4", "name" => "Leggings of the Deepening Void" ),
	array( "id" => "47205", "qual" => "4", "name" => "Footpads of the Icy Floe" ),
	array( "id" => "47155", "qual" => "4", "name" => "Bracers of Dark Determination" ),
	array( "id" => "47190", "qual" => "4", "name" => "Legwraps of the Awakening" ),
	array( "id" => "47209", "qual" => "4", "name" => "Chestguard of Flowing Elements" ),
	array( "id" => "47153", "qual" => "4", "name" => "Belt of Deathly Dominion" ),
	array( "id" => "47191", "qual" => "4", "name" => "Legguards of the Lurking Threat" ),
	array( "id" => "47240", "qual" => "4", "name" => "Gloves of Bitter Reprisal" ),
	array( "id" => "47207", "qual" => "4", "name" => "Belt of the Forgotten Martyr" ),
	array( "id" => "47154", "qual" => "4", "name" => "Greaves of the 7th Legion" ),
	array( "id" => "47237", "qual" => "4", "name" => "Band of Deplorable Violence" ),
	array( "id" => "47157", "qual" => "4", "name" => "Signet of the Traitor King" ),
	array( "id" => "47188", "qual" => "4", "name" => "Reign of the Unliving" ),
	array( "id" => "47156", "qual" => "4", "name" => "Stormpike Cleaver" ),
	array( "id" => "47206", "qual" => "4", "name" => "Misery's End" ),
	array( "id" => "47239", "qual" => "4", "name" => "Archon Glaive" ),
	array( "id" => "47557", "qual" => "4", "name" => "Regalia of the Grand Conqueror" ),
	array( "id" => "47557", "qual" => "4", "name" => "Regalia of the Grand Conqueror" ),
	array( "id" => "47558", "qual" => "4", "name" => "Regalia of the Grand Protector" ),
);
}else{
$loot = array(
	array( "id" => "47490", "qual" => "4", "name" => "Maiden's Adoration" ),
	array( "id" => "47481", "qual" => "4", "name" => "Might of the Nerub" ),
	array( "id" => "47485", "qual" => "4", "name" => "Bindings of the Ashen Saint" ),
	array( "id" => "47487", "qual" => "4", "name" => "Handwraps of the Lifeless Touch" ),
	array( "id" => "47478", "qual" => "4", "name" => "Breeches of the Deepening Void" ),
	array( "id" => "47482", "qual" => "4", "name" => "Boots of the Icy Floe" ),
	array( "id" => "47474", "qual" => "4", "name" => "Armbands of Dark Determination" ),
	array( "id" => "47479", "qual" => "4", "name" => "Leggings of the Awakening" ),
	array( "id" => "47486", "qual" => "4", "name" => "Cuirass of Flowing Elements" ),
	array( "id" => "47472", "qual" => "4", "name" => "Waistguard of Deathly Dominion" ),
	array( "id" => "47480", "qual" => "4", "name" => "Leggings of the Lurking Threat" ),
	array( "id" => "47492", "qual" => "4", "name" => "Gauntlets of Bitter Reprisal" ),
	array( "id" => "47484", "qual" => "4", "name" => "Girdle of the Forgotten Martyr" ),
	array( "id" => "47473", "qual" => "4", "name" => "Greaves of the Saronite Citadel" ),
	array( "id" => "47489", "qual" => "4", "name" => "Lurid Manifestation" ),
	array( "id" => "47476", "qual" => "4", "name" => "Band of the Traitor King" ),
	array( "id" => "47477", "qual" => "4", "name" => "Reign of the Dead" ),
	array( "id" => "47475", "qual" => "4", "name" => "Hellscream Slicer" ),
	array( "id" => "47483", "qual" => "4", "name" => "Suffering's End" ),
	array( "id" => "47491", "qual" => "4", "name" => "Hellion Glaive" ),
	array( "id" => "47557", "qual" => "4", "name" => "Regalia of the Grand Conqueror" ),
	array( "id" => "47557", "qual" => "4", "name" => "Regalia of the Grand Conqueror" ),
	array( "id" => "47558", "qual" => "4", "name" => "Regalia of the Grand Protector" ),
);
}

?>