<?php
$loot = array(
	array( "id" => "45665", "qual" => "4", "name" => "Pharos Gloves" ),
	array( "id" => "45619", "qual" => "4", "name" => "Starwatcher's Binding" ),
	array( "id" => "45611", "qual" => "4", "name" => "Solar Bindings" ),
	array( "id" => "45616", "qual" => "4", "name" => "Star-beaded Clutch" ),
	array( "id" => "45610", "qual" => "4", "name" => "Boundless Gaze" ),
	array( "id" => "45615", "qual" => "4", "name" => "Planewalker Treads" ),
	array( "id" => "45594", "qual" => "4", "name" => "Legplates of the Endless Void" ),
	array( "id" => "45599", "qual" => "4", "name" => "Sabatons of Lifeless Night" ),
	array( "id" => "45617", "qual" => "4", "name" => "Cosmos" ),
	array( "id" => "45620", "qual" => "4", "name" => "Starshard Edge" ),
	array( "id" => "45607", "qual" => "4", "name" => "Fang of Oblivion" ),
	array( "id" => "45612", "qual" => "4", "name" => "Constellus" ),
	array( "id" => "45613", "qual" => "4", "name" => "Dreambinder" ),
	array( "id" => "45587", "qual" => "4", "name" => "Bulwark of Algalon" ),
	array( "id" => "45570", "qual" => "4", "name" => "Skyforge Crossbow" ),
	array( "id" => "45609", "qual" => "4", "name" => "Comet's Trail" ),
	array( "id" => "46053", "qual" => "4", "name" => "Reply-Code Alpha" ),
	array( "id" => "45588", "qual" => "4", "name" => "Drape of the Skyborn" ),
	array( "id" => "45618", "qual" => "4", "name" => "Sunglimmer Cloak" ),
	array( "id" => "45608", "qual" => "4", "name" => "Brann's Signet Ring" ),
	array( "id" => "45614", "qual" => "4", "name" => "Starshine Circle" ),
);
?>