<?php
$loot = array(
	array( "id" => "45038", "qual" => "5", "name" => "Fragment of Val'anyr" ),
	array( "id" => "46017", "qual" => "5", "name" => "Val'anyr, Hammer of Ancient Kings" ),
	array( "id" => "45224", "qual" => "4", "name" => "Drape of the Lithe" ),
	array( "id" => "45240", "qual" => "4", "name" => "Raiments of the Iron Council" ),
	array( "id" => "45238", "qual" => "4", "name" => "Overload Legwraps" ),
	array( "id" => "45237", "qual" => "4", "name" => "Phaelia's Vestments of the Sprouting Seed" ),
	array( "id" => "45232", "qual" => "4", "name" => "Runed Ironhide Boots" ),
	array( "id" => "45227", "qual" => "4", "name" => "Iron-studded Mantle" ),
	array( "id" => "45239", "qual" => "4", "name" => "Runeshaper's Gloves" ),
	array( "id" => "45226", "qual" => "4", "name" => "Ancient Iron Heaume" ),
	array( "id" => "45225", "qual" => "4", "name" => "Steelbreaker's Embrace" ),
	array( "id" => "45228", "qual" => "4", "name" => "Handguards of the Enclave" ),
	array( "id" => "45193", "qual" => "4", "name" => "Insurmountable Fervor" ),
	array( "id" => "45236", "qual" => "4", "name" => "Unblinking Eye" ),
	array( "id" => "45235", "qual" => "4", "name" => "Radiant Seal" ),
	array( "id" => "45233", "qual" => "4", "name" => "Stormrune Edge" ),
	array( "id" => "45234", "qual" => "4", "name" => "Rapture" ),
	array( "id" => "45242", "qual" => "4", "name" => "Drape of Mortal Downfall" ),
	array( "id" => "45245", "qual" => "4", "name" => "Shoulderpads of the Intruder" ),
	array( "id" => "45244", "qual" => "4", "name" => "Greaves of Swift Vengeance" ),
	array( "id" => "45241", "qual" => "4", "name" => "Belt of Colossal Rage" ),
	array( "id" => "45243", "qual" => "4", "name" => "Sapphire Amulet of Renewal" ),
	array( "id" => "45607", "qual" => "4", "name" => "Fang of Oblivion" ),
	array( "id" => "45857", "qual" => "4", "name" => "Archivum Data Disc" ),
);
?>