<?php
$loot = array(
	array( "id" => "46131", "qual" => "4", "name" => "Valorous Kirin Tor Gauntlets" ),
	array( "id" => "45367", "qual" => "4", "name" => "Valorous Kirin Tor Leggings" ),
	array( "id" => "45387", "qual" => "4", "name" => "Valorous Gloves of Sanctification" ),
	array( "id" => "45388", "qual" => "4", "name" => "Valorous Leggings of Sanctification" ),
	array( "id" => "45392", "qual" => "4", "name" => "Valorous Handwraps of Sanctification" ),
	array( "id" => "45394", "qual" => "4", "name" => "Valorous Pants of Sanctification" ),
	array( "id" => "45419", "qual" => "4", "name" => "Valorous Deathbringer Gloves" ),
	array( "id" => "45420", "qual" => "4", "name" => "Valorous Deathbringer Leggings" ),
	array( "id" => "41970", "qual" => "4", "name" => "Deadly Gladiator's Silk Handguards" ),
	array( "id" => "41958", "qual" => "4", "name" => "Deadly Gladiator's Silk Trousers" ),
	array( "id" => "41873", "qual" => "4", "name" => "Deadly Gladiator's Mooncloth Gloves" ),
	array( "id" => "41863", "qual" => "4", "name" => "Deadly Gladiator's Mooncloth Leggings" ),
	array( "id" => "41939", "qual" => "4", "name" => "Deadly Gladiator's Satin Gloves" ),
	array( "id" => "41926", "qual" => "4", "name" => "Deadly Gladiator's Satin Leggings" ),
	array( "id" => "42016", "qual" => "4", "name" => "Deadly Gladiator's Felweave Handguards" ),
	array( "id" => "42004", "qual" => "4", "name" => "Deadly Gladiator's Felweave Trousers" ),
	array( "id" => "45351", "qual" => "4", "name" => "Valorous Nightsong Gloves" ),
	array( "id" => "45353", "qual" => "4", "name" => "Valorous Nightsong Trousers" ),
	array( "id" => "45355", "qual" => "4", "name" => "Valorous Nightsong Handgrips" ),
	array( "id" => "45357", "qual" => "4", "name" => "Valorous Nightsong Legguards" ),
	array( "id" => "45345", "qual" => "4", "name" => "Valorous Nightsong Handguards" ),
	array( "id" => "45347", "qual" => "4", "name" => "Valorous Nightsong Leggings" ),
	array( "id" => "45397", "qual" => "4", "name" => "Valorous Terrorblade Gauntlets" ),
	array( "id" => "45399", "qual" => "4", "name" => "Valorous Terrorblade Legplates" ),
	array( "id" => "41292", "qual" => "4", "name" => "Deadly Gladiator's Wyrmhide Gloves" ),
	array( "id" => "41303", "qual" => "4", "name" => "Deadly Gladiator's Wyrmhide Legguards" ),
	array( "id" => "41772", "qual" => "4", "name" => "Deadly Gladiator's Dragonhide Gloves" ),
	array( "id" => "41666", "qual" => "4", "name" => "Deadly Gladiator's Dragonhide Legguards" ),
	array( "id" => "41286", "qual" => "4", "name" => "Deadly Gladiator's Kodohide Gloves" ),
	array( "id" => "41297", "qual" => "4", "name" => "Deadly Gladiator's Kodohide Legguards" ),
	array( "id" => "41766", "qual" => "4", "name" => "Deadly Gladiator's Leather Gloves" ),
	array( "id" => "41654", "qual" => "4", "name" => "Deadly Gladiator's Leather Legguards" ),
	array( "id" => "45360", "qual" => "4", "name" => "Valorous Scourgestalker Handguards" ),
	array( "id" => "45362", "qual" => "4", "name" => "Valorous Scourgestalker Legguards" ),
	array( "id" => "45406", "qual" => "4", "name" => "Valorous Worldbreaker Gloves" ),
	array( "id" => "45409", "qual" => "4", "name" => "Valorous Worldbreaker Kilt" ),
	array( "id" => "45414", "qual" => "4", "name" => "Valorous Worldbreaker Grips" ),
	array( "id" => "45416", "qual" => "4", "name" => "Valorous Worldbreaker War-Kilt" ),
	array( "id" => "45401", "qual" => "4", "name" => "Valorous Worldbreaker Handguards" ),
	array( "id" => "45403", "qual" => "4", "name" => "Valorous Worldbreaker Legguards" ),
	array( "id" => "41142", "qual" => "4", "name" => "Deadly Gladiator's Chain Gauntlets" ),
	array( "id" => "41204", "qual" => "4", "name" => "Deadly Gladiator's Chain Leggings" ),
	array( "id" => "41006", "qual" => "4", "name" => "Deadly Gladiator's Mail Gauntlets" ),
	array( "id" => "41032", "qual" => "4", "name" => "Deadly Gladiator's Mail Leggings" ),
	array( "id" => "41136", "qual" => "4", "name" => "Deadly Gladiator's Linked Gauntlets" ),
	array( "id" => "41198", "qual" => "4", "name" => "Deadly Gladiator's Linked Leggings" ),
	array( "id" => "41000", "qual" => "4", "name" => "Deadly Gladiator's Ringmail Gauntlets" ),
	array( "id" => "41026", "qual" => "4", "name" => "Deadly Gladiator's Ringmail Leggings" ),
	array( "id" => "45341", "qual" => "4", "name" => "Valorous Darkruned Gauntlets" ),
	array( "id" => "45343", "qual" => "4", "name" => "Valorous Darkruned Legplates" ),
	array( "id" => "45337", "qual" => "4", "name" => "Valorous Darkruned Handguards" ),
	array( "id" => "45338", "qual" => "4", "name" => "Valorous Darkruned Legguards" ),
	array( "id" => "45370", "qual" => "4", "name" => "Valorous Aegis Gloves" ),
	array( "id" => "45371", "qual" => "4", "name" => "Valorous Aegis Greaves" ),
	array( "id" => "45376", "qual" => "4", "name" => "Valorous Aegis Gauntlets" ),
	array( "id" => "45379", "qual" => "4", "name" => "Valorous Aegis Legplates" ),
	array( "id" => "40806", "qual" => "4", "name" => "Deadly Gladiator's Dreadplate Gauntlets" ),
	array( "id" => "40845", "qual" => "4", "name" => "Deadly Gladiator's Dreadplate Legguards" ),
	array( "id" => "40926", "qual" => "4", "name" => "Deadly Gladiator's Ornamented Gloves" ),
	array( "id" => "40938", "qual" => "4", "name" => "Deadly Gladiator's Ornamented Legplates" ),
	array( "id" => "40805", "qual" => "4", "name" => "Deadly Gladiator's Scaled Gauntlets" ),
	array( "id" => "40846", "qual" => "4", "name" => "Deadly Gladiator's Scaled Legguards" ),
	array( "id" => "45383", "qual" => "4", "name" => "Valorous Aegis Handguards" ),
	array( "id" => "45384", "qual" => "4", "name" => "Valorous Aegis Legguards" ),
	array( "id" => "45430", "qual" => "4", "name" => "Valorous Siegebreaker Gauntlets" ),
	array( "id" => "45432", "qual" => "4", "name" => "Valorous Siegebreaker Legplates" ),
	array( "id" => "45426", "qual" => "4", "name" => "Valorous Siegebreaker Handguards" ),
	array( "id" => "45427", "qual" => "4", "name" => "Valorous Siegebreaker Legguards" ),
	array( "id" => "40804", "qual" => "4", "name" => "Deadly Gladiator's Plate Gauntlets" ),
	array( "id" => "40844", "qual" => "4", "name" => "Deadly Gladiator's Plate Legguards" ),
	array( "id" => "41908", "qual" => "4", "name" => "Deadly Gladiator's Cuffs of Dominance" ),
	array( "id" => "41897", "qual" => "4", "name" => "Deadly Gladiator's Cord of Dominance" ),
	array( "id" => "41902", "qual" => "4", "name" => "Deadly Gladiator's Treads of Dominance" ),
	array( "id" => "41892", "qual" => "4", "name" => "Deadly Gladiator's Cuffs of Salvation" ),
	array( "id" => "41880", "qual" => "4", "name" => "Deadly Gladiator's Cord of Salvation" ),
	array( "id" => "41884", "qual" => "4", "name" => "Deadly Gladiator's Treads of Salvation" ),
	array( "id" => "41639", "qual" => "4", "name" => "Deadly Gladiator's Armwraps of Dominance" ),
	array( "id" => "41629", "qual" => "4", "name" => "Deadly Gladiator's Belt of Dominance" ),
	array( "id" => "41634", "qual" => "4", "name" => "Deadly Gladiator's Boots of Dominance" ),
	array( "id" => "41624", "qual" => "4", "name" => "Deadly Gladiator's Armwraps of Salvation" ),
	array( "id" => "41616", "qual" => "4", "name" => "Deadly Gladiator's Belt of Salvation" ),
	array( "id" => "41620", "qual" => "4", "name" => "Deadly Gladiator's Boots of Salvation" ),
	array( "id" => "41839", "qual" => "4", "name" => "Deadly Gladiator's Armwraps of Triumph" ),
	array( "id" => "41831", "qual" => "4", "name" => "Deadly Gladiator's Belt of Triumph" ),
	array( "id" => "41835", "qual" => "4", "name" => "Deadly Gladiator's Boots of Triumph" ),
	array( "id" => "41064", "qual" => "4", "name" => "Deadly Gladiator's Wristguards of Dominance" ),
	array( "id" => "41069", "qual" => "4", "name" => "Deadly Gladiator's Waistguard of Dominance" ),
	array( "id" => "41074", "qual" => "4", "name" => "Deadly Gladiator's Sabatons of Dominance" ),
	array( "id" => "41059", "qual" => "4", "name" => "Deadly Gladiator's Wristguards of Salvation" ),
	array( "id" => "41048", "qual" => "4", "name" => "Deadly Gladiator's Waistguard of Salvation" ),
	array( "id" => "41054", "qual" => "4", "name" => "Deadly Gladiator's Sabatons of Salvation" ),
	array( "id" => "41224", "qual" => "4", "name" => "Deadly Gladiator's Wristguards of Triumph" ),
	array( "id" => "41234", "qual" => "4", "name" => "Deadly Gladiator's Waistguard of Triumph" ),
	array( "id" => "41229", "qual" => "4", "name" => "Deadly Gladiator's Sabatons of Triumph" ),
	array( "id" => "40982", "qual" => "4", "name" => "Deadly Gladiator's Bracers of Salvation" ),
	array( "id" => "40974", "qual" => "4", "name" => "Deadly Gladiator's Girdle of Salvation" ),
	array( "id" => "40975", "qual" => "4", "name" => "Deadly Gladiator's Greaves of Salvation" ),
	array( "id" => "40888", "qual" => "4", "name" => "Deadly Gladiator's Bracers of Triumph" ),
	array( "id" => "40879", "qual" => "4", "name" => "Deadly Gladiator's Girdle of Triumph" ),
	array( "id" => "40880", "qual" => "4", "name" => "Deadly Gladiator's Greaves of Triumph" ),
	array( "id" => "42064", "qual" => "4", "name" => "Deadly Gladiator's Cloak of Ascendancy" ),
	array( "id" => "42066", "qual" => "4", "name" => "Deadly Gladiator's Cloak of Deliverance" ),
	array( "id" => "42062", "qual" => "4", "name" => "Deadly Gladiator's Cloak of Dominance" ),
	array( "id" => "42065", "qual" => "4", "name" => "Deadly Gladiator's Cloak of Salvation" ),
	array( "id" => "42063", "qual" => "4", "name" => "Deadly Gladiator's Cloak of Subjugation" ),
	array( "id" => "42067", "qual" => "4", "name" => "Deadly Gladiator's Cloak of Triumph" ),
	array( "id" => "42068", "qual" => "4", "name" => "Deadly Gladiator's Cloak of Victory" ),
	array( "id" => "47241", "qual" => "4", "name" => "Emblem of Triumph" ),
	array( "id" => "43959", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "44083", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "42030", "qual" => "4", "name" => "Deadly Gladiator's Pendant of Ascendancy" ),
	array( "id" => "42032", "qual" => "4", "name" => "Deadly Gladiator's Pendant of Deliverance" ),
	array( "id" => "42029", "qual" => "4", "name" => "Deadly Gladiator's Pendant of Dominance" ),
	array( "id" => "42033", "qual" => "4", "name" => "Deadly Gladiator's Pendant of Salvation" ),
	array( "id" => "42031", "qual" => "4", "name" => "Deadly Gladiator's Pendant of Subjugation" ),
	array( "id" => "42027", "qual" => "4", "name" => "Deadly Gladiator's Pendant of Triumph" ),
	array( "id" => "42028", "qual" => "4", "name" => "Deadly Gladiator's Pendant of Victory" ),
	array( "id" => "42114", "qual" => "4", "name" => "Deadly Gladiator's Band of Ascendancy" ),
	array( "id" => "42115", "qual" => "4", "name" => "Deadly Gladiator's Band of Victory" ),
);

?>