<?php
$loot = array(
	array( "id" => "46132", "qual" => "4", "name" => "Conqueror's Kirin Tor Gauntlets" ),
	array( "id" => "46133", "qual" => "4", "name" => "Conqueror's Kirin Tor Leggings" ),
	array( "id" => "46188", "qual" => "4", "name" => "Conqueror's Gloves of Sanctification" ),
	array( "id" => "46195", "qual" => "4", "name" => "Conqueror's Leggings of Sanctification" ),
	array( "id" => "46163", "qual" => "4", "name" => "Conqueror's Handwraps of Sanctification" ),
	array( "id" => "46170", "qual" => "4", "name" => "Conqueror's Pants of Sanctification" ),
	array( "id" => "46135", "qual" => "4", "name" => "Conqueror's Deathbringer Gloves" ),
	array( "id" => "46139", "qual" => "4", "name" => "Conqueror's Deathbringer Leggings" ),
	array( "id" => "41971", "qual" => "4", "name" => "Furious Gladiator's Silk Handguards" ),
	array( "id" => "41959", "qual" => "4", "name" => "Furious Gladiator's Silk Trousers" ),
	array( "id" => "41874", "qual" => "4", "name" => "Furious Gladiator's Mooncloth Gloves" ),
	array( "id" => "41864", "qual" => "4", "name" => "Furious Gladiator's Mooncloth Leggings" ),
	array( "id" => "41940", "qual" => "4", "name" => "Furious Gladiator's Satin Gloves" ),
	array( "id" => "41927", "qual" => "4", "name" => "Furious Gladiator's Satin Leggings" ),
	array( "id" => "42017", "qual" => "4", "name" => "Furious Gladiator's Felweave Handguards" ),
	array( "id" => "42005", "qual" => "4", "name" => "Furious Gladiator's Felweave Trousers" ),
	array( "id" => "46189", "qual" => "4", "name" => "Conqueror's Nightsong Gloves" ),
	array( "id" => "46192", "qual" => "4", "name" => "Conqueror's Nightsong Trousers" ),
	array( "id" => "46158", "qual" => "4", "name" => "Conqueror's Nightsong Handgrips" ),
	array( "id" => "46160", "qual" => "4", "name" => "Conqueror's Nightsong Legguards" ),
	array( "id" => "46183", "qual" => "4", "name" => "Conqueror's Nightsong Handguards" ),
	array( "id" => "46185", "qual" => "4", "name" => "Conqueror's Nightsong Leggings" ),
	array( "id" => "46124", "qual" => "4", "name" => "Conqueror's Terrorblade Gauntlets" ),
	array( "id" => "46126", "qual" => "4", "name" => "Conqueror's Terrorblade Legplates" ),
	array( "id" => "41293", "qual" => "4", "name" => "Furious Gladiator's Wyrmhide Gloves" ),
	array( "id" => "41304", "qual" => "4", "name" => "Furious Gladiator's Wyrmhide Legguards" ),
	array( "id" => "41773", "qual" => "4", "name" => "Furious Gladiator's Dragonhide Gloves" ),
	array( "id" => "41667", "qual" => "4", "name" => "Furious Gladiator's Dragonhide Legguards" ),
	array( "id" => "41287", "qual" => "4", "name" => "Furious Gladiator's Kodohide Gloves" ),
	array( "id" => "41298", "qual" => "4", "name" => "Furious Gladiator's Kodohide Legguards" ),
	array( "id" => "41767", "qual" => "4", "name" => "Furious Gladiator's Leather Gloves" ),
	array( "id" => "41655", "qual" => "4", "name" => "Furious Gladiator's Leather Legguards" ),
	array( "id" => "46142", "qual" => "4", "name" => "Conqueror's Scourgestalker Handguards" ),
	array( "id" => "46144", "qual" => "4", "name" => "Conqueror's Scourgestalker Legguards" ),
	array( "id" => "46207", "qual" => "4", "name" => "Conqueror's Worldbreaker Gloves" ),
	array( "id" => "46210", "qual" => "4", "name" => "Conqueror's Worldbreaker Kilt" ),
	array( "id" => "46200", "qual" => "4", "name" => "Conqueror's Worldbreaker Grips" ),
	array( "id" => "46208", "qual" => "4", "name" => "Conqueror's Worldbreaker War-Kilt" ),
	array( "id" => "46199", "qual" => "4", "name" => "Conqueror's Worldbreaker Handguards" ),
	array( "id" => "46202", "qual" => "4", "name" => "Conqueror's Worldbreaker Legguards" ),
	array( "id" => "41143", "qual" => "4", "name" => "Furious Gladiator's Chain Gauntlets" ),
	array( "id" => "41205", "qual" => "4", "name" => "Furious Gladiator's Chain Leggings" ),
	array( "id" => "41007", "qual" => "4", "name" => "Furious Gladiator's Mail Gauntlets" ),
	array( "id" => "41033", "qual" => "4", "name" => "Furious Gladiator's Mail Leggings" ),
	array( "id" => "41137", "qual" => "4", "name" => "Furious Gladiator's Linked Gauntlets" ),
	array( "id" => "41199", "qual" => "4", "name" => "Furious Gladiator's Linked Leggings" ),
	array( "id" => "41001", "qual" => "4", "name" => "Furious Gladiator's Ringmail Gauntlets" ),
	array( "id" => "41027", "qual" => "4", "name" => "Furious Gladiator's Ringmail Leggings" ),
	array( "id" => "46113", "qual" => "4", "name" => "Conqueror's Darkruned Gauntlets" ),
	array( "id" => "46116", "qual" => "4", "name" => "Conqueror's Darkruned Legplates" ),
	array( "id" => "46119", "qual" => "4", "name" => "Conqueror's Darkruned Handguards" ),
	array( "id" => "46121", "qual" => "4", "name" => "Conqueror's Darkruned Legguards" ),
	array( "id" => "46179", "qual" => "4", "name" => "Conqueror's Aegis Gloves" ),
	array( "id" => "46181", "qual" => "4", "name" => "Conqueror's Aegis Greaves" ),
	array( "id" => "46155", "qual" => "4", "name" => "Conqueror's Aegis Gauntlets" ),
	array( "id" => "46153", "qual" => "4", "name" => "Conqueror's Aegis Legplates" ),
	array( "id" => "40809", "qual" => "4", "name" => "Furious Gladiator's Dreadplate Gauntlets" ),
	array( "id" => "40848", "qual" => "4", "name" => "Furious Gladiator's Dreadplate Legguards" ),
	array( "id" => "40927", "qual" => "4", "name" => "Furious Gladiator's Ornamented Gloves" ),
	array( "id" => "40939", "qual" => "4", "name" => "Furious Gladiator's Ornamented Legplates" ),
	array( "id" => "40808", "qual" => "4", "name" => "Furious Gladiator's Scaled Gauntlets" ),
	array( "id" => "40849", "qual" => "4", "name" => "Furious Gladiator's Scaled Legguards" ),
	array( "id" => "46174", "qual" => "4", "name" => "Conqueror's Aegis Handguards" ),
	array( "id" => "46176", "qual" => "4", "name" => "Conqueror's Aegis Legguards" ),
	array( "id" => "46148", "qual" => "4", "name" => "Conqueror's Siegebreaker Gauntlets" ),
	array( "id" => "46150", "qual" => "4", "name" => "Conqueror's Siegebreaker Legplates" ),
	array( "id" => "46164", "qual" => "4", "name" => "Conqueror's Siegebreaker Handguards" ),
	array( "id" => "46169", "qual" => "4", "name" => "Conqueror's Siegebreaker Legguards" ),
	array( "id" => "40807", "qual" => "4", "name" => "Furious Gladiator's Plate Gauntlets" ),
	array( "id" => "40847", "qual" => "4", "name" => "Furious Gladiator's Plate Legguards" ),
	array( "id" => "41909", "qual" => "4", "name" => "Furious Gladiator's Cuffs of Dominance" ),
	array( "id" => "41898", "qual" => "4", "name" => "Furious Gladiator's Cord of Dominance" ),
	array( "id" => "41903", "qual" => "4", "name" => "Furious Gladiator's Slippers of Dominance" ),
	array( "id" => "41893", "qual" => "4", "name" => "Furious Gladiator's Cuffs of Salvation" ),
	array( "id" => "41881", "qual" => "4", "name" => "Furious Gladiator's Cord of Salvation" ),
	array( "id" => "41885", "qual" => "4", "name" => "Furious Gladiator's Slippers of Salvation" ),
	array( "id" => "41640", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Dominance" ),
	array( "id" => "41630", "qual" => "4", "name" => "Furious Gladiator's Belt of Dominance" ),
	array( "id" => "41635", "qual" => "4", "name" => "Furious Gladiator's Boots of Dominance" ),
	array( "id" => "41625", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Salvation" ),
	array( "id" => "41617", "qual" => "4", "name" => "Furious Gladiator's Belt of Salvation" ),
	array( "id" => "41621", "qual" => "4", "name" => "Furious Gladiator's Boots of Salvation" ),
	array( "id" => "41840", "qual" => "4", "name" => "Furious Gladiator's Armwraps of Triumph" ),
	array( "id" => "41832", "qual" => "4", "name" => "Furious Gladiator's Belt of Triumph" ),
	array( "id" => "41836", "qual" => "4", "name" => "Furious Gladiator's Boots of Triumph" ),
	array( "id" => "41065", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Dominance" ),
	array( "id" => "41070", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Dominance" ),
	array( "id" => "41075", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Dominance" ),
	array( "id" => "41060", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Salvation" ),
	array( "id" => "41051", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Salvation" ),
	array( "id" => "41055", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Salvation" ),
	array( "id" => "41225", "qual" => "4", "name" => "Furious Gladiator's Wristguards of Triumph" ),
	array( "id" => "41235", "qual" => "4", "name" => "Furious Gladiator's Waistguard of Triumph" ),
	array( "id" => "41230", "qual" => "4", "name" => "Furious Gladiator's Sabatons of Triumph" ),
	array( "id" => "40983", "qual" => "4", "name" => "Furious Gladiator's Bracers of Salvation" ),
	array( "id" => "40976", "qual" => "4", "name" => "Furious Gladiator's Girdle of Salvation" ),
	array( "id" => "40977", "qual" => "4", "name" => "Furious Gladiator's Greaves of Salvation" ),
	array( "id" => "40889", "qual" => "4", "name" => "Furious Gladiator's Bracers of Triumph" ),
	array( "id" => "40881", "qual" => "4", "name" => "Furious Gladiator's Girdle of Triumph" ),
	array( "id" => "40882", "qual" => "4", "name" => "Furious Gladiator's Greaves of Triumph" ),
	array( "id" => "42071", "qual" => "4", "name" => "Furious Gladiator's Cloak of Ascendancy" ),
	array( "id" => "42073", "qual" => "4", "name" => "Furious Gladiator's Cloak of Deliverance" ),
	array( "id" => "42069", "qual" => "4", "name" => "Furious Gladiator's Cloak of Dominance" ),
	array( "id" => "42072", "qual" => "4", "name" => "Furious Gladiator's Cloak of Salvation" ),
	array( "id" => "42070", "qual" => "4", "name" => "Furious Gladiator's Cloak of Subjugation" ),
	array( "id" => "42074", "qual" => "4", "name" => "Furious Gladiator's Cloak of Triumph" ),
	array( "id" => "42075", "qual" => "4", "name" => "Furious Gladiator's Cloak of Victory" ),
	array( "id" => "45624", "qual" => "4", "name" => "Emblem of Conquest" ),
	array( "id" => "43959", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "44083", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "42037", "qual" => "4", "name" => "Furious Gladiator's Pendant of Ascendancy" ),
	array( "id" => "42039", "qual" => "4", "name" => "Furious Gladiator's Pendant of Deliverance" ),
	array( "id" => "42036", "qual" => "4", "name" => "Furious Gladiator's Pendant of Dominance" ),
	array( "id" => "42040", "qual" => "4", "name" => "Furious Gladiator's Pendant of Salvation" ),
	array( "id" => "42038", "qual" => "4", "name" => "Furious Gladiator's Pendant of Subjugation" ),
	array( "id" => "46373", "qual" => "4", "name" => "Furious Gladiator's Pendant of Sundering" ),
	array( "id" => "42034", "qual" => "4", "name" => "Furious Gladiator's Pendant of Triumph" ),
	array( "id" => "42035", "qual" => "4", "name" => "Furious Gladiator's Pendant of Victory" ),
	array( "id" => "42116", "qual" => "4", "name" => "Furious Gladiator's Band of Dominance" ),
	array( "id" => "42117", "qual" => "4", "name" => "Furious Gladiator's Band of Triumph" ),
);

?>