<?php
$loot = array(
	array( "id" => "40271", "qual" => "4", "name" => "Sash of Solitude" ),
	array( "id" => "40269", "qual" => "4", "name" => "Boots of Persuasion" ),
	array( "id" => "40260", "qual" => "4", "name" => "Belt of the Tortured" ),
	array( "id" => "40270", "qual" => "4", "name" => "Boots of Septic Wounds" ),
	array( "id" => "40262", "qual" => "4", "name" => "Gloves of Calculated Risk" ),
	array( "id" => "40272", "qual" => "4", "name" => "Girdle of the Gambit" ),
	array( "id" => "40261", "qual" => "4", "name" => "Crude Discolored Battlegrips" ),
	array( "id" => "40263", "qual" => "4", "name" => "Fleshless Girdle" ),
	array( "id" => "40259", "qual" => "4", "name" => "Waistguard of Divine Grace" ),
	array( "id" => "40071", "qual" => "4", "name" => "Chains of Adoration" ),
	array( "id" => "40065", "qual" => "4", "name" => "Fool's Trial" ),
	array( "id" => "40069", "qual" => "4", "name" => "Heritage" ),
	array( "id" => "40064", "qual" => "4", "name" => "Thunderstorm Amulet" ),
	array( "id" => "40080", "qual" => "4", "name" => "Lost Jewel" ),
	array( "id" => "40075", "qual" => "4", "name" => "Ruthlessness" ),
	array( "id" => "40107", "qual" => "4", "name" => "Sand-Worn Band" ),
	array( "id" => "40074", "qual" => "4", "name" => "Strong-Handed Ring" ),
	array( "id" => "40267", "qual" => "4", "name" => "Totem of Hex" ),
	array( "id" => "40268", "qual" => "4", "name" => "Libram of Tolerance" ),
	array( "id" => "40266", "qual" => "4", "name" => "Hero's Surrender" ),
	array( "id" => "40264", "qual" => "4", "name" => "Split Greathammer" ),
	array( "id" => "40265", "qual" => "4", "name" => "Arrowsong" ),
);
?>