<?php
$loot = array(
	array( "id" => "39492", "qual" => "4", "name" => "Heroes' Frostfire Robe" ),
	array( "id" => "39495", "qual" => "4", "name" => "Heroes' Frostfire Gloves" ),
	array( "id" => "39493", "qual" => "4", "name" => "Heroes' Frostfire Leggings" ),
	array( "id" => "39515", "qual" => "4", "name" => "Heroes' Robe of Faith" ),
	array( "id" => "39519", "qual" => "4", "name" => "Heroes' Gloves of Faith" ),
	array( "id" => "39517", "qual" => "4", "name" => "Heroes' Leggings of Faith" ),
	array( "id" => "39523", "qual" => "4", "name" => "Heroes' Raiments of Faith" ),
	array( "id" => "39530", "qual" => "4", "name" => "Heroes' Handwraps of Faith" ),
	array( "id" => "39528", "qual" => "4", "name" => "Heroes' Pants of Faith" ),
	array( "id" => "39497", "qual" => "4", "name" => "Heroes' Plagueheart Robe" ),
	array( "id" => "39500", "qual" => "4", "name" => "Heroes' Plagueheart Gloves" ),
	array( "id" => "39498", "qual" => "4", "name" => "Heroes' Plagueheart Leggings" ),
	array( "id" => "41950", "qual" => "4", "name" => "Hateful Gladiator's Silk Raiment" ),
	array( "id" => "41969", "qual" => "4", "name" => "Hateful Gladiator's Silk Handguards" ),
	array( "id" => "41957", "qual" => "4", "name" => "Hateful Gladiator's Silk Trousers" ),
	array( "id" => "41857", "qual" => "4", "name" => "Hateful Gladiator's Mooncloth Robe" ),
	array( "id" => "41872", "qual" => "4", "name" => "Hateful Gladiator's Mooncloth Gloves" ),
	array( "id" => "41862", "qual" => "4", "name" => "Hateful Gladiator's Mooncloth Leggings" ),
	array( "id" => "41919", "qual" => "4", "name" => "Hateful Gladiator's Satin Robe" ),
	array( "id" => "41938", "qual" => "4", "name" => "Hateful Gladiator's Satin Gloves" ),
	array( "id" => "41925", "qual" => "4", "name" => "Hateful Gladiator's Satin Leggings" ),
	array( "id" => "42001", "qual" => "4", "name" => "Hateful Gladiator's Felweave Raiment" ),
	array( "id" => "42015", "qual" => "4", "name" => "Hateful Gladiator's Felweave Handguards" ),
	array( "id" => "42003", "qual" => "4", "name" => "Hateful Gladiator's Felweave Trousers" ),
	array( "id" => "39547", "qual" => "4", "name" => "Heroes' Dreamwalker Vestments" ),
	array( "id" => "39544", "qual" => "4", "name" => "Heroes' Dreamwalker Gloves" ),
	array( "id" => "39546", "qual" => "4", "name" => "Heroes' Dreamwalker Trousers" ),
	array( "id" => "39554", "qual" => "4", "name" => "Heroes' Dreamwalker Raiments" ),
	array( "id" => "39557", "qual" => "4", "name" => "Heroes' Dreamwalker Handgrips" ),
	array( "id" => "39555", "qual" => "4", "name" => "Heroes' Dreamwalker Legguards" ),
	array( "id" => "39538", "qual" => "4", "name" => "Heroes' Dreamwalker Robe" ),
	array( "id" => "39543", "qual" => "4", "name" => "Heroes' Dreamwalker Handguards" ),
	array( "id" => "39539", "qual" => "4", "name" => "Heroes' Dreamwalker Leggings" ),
	array( "id" => "39558", "qual" => "4", "name" => "Heroes' Bonescythe Breastplate" ),
	array( "id" => "39560", "qual" => "4", "name" => "Heroes' Bonescythe Gauntlets" ),
	array( "id" => "39564", "qual" => "4", "name" => "Heroes' Bonescythe Legplates" ),
	array( "id" => "41314", "qual" => "4", "name" => "Hateful Gladiator's Wyrmhide Robes" ),
	array( "id" => "41291", "qual" => "4", "name" => "Hateful Gladiator's Wyrmhide Gloves" ),
	array( "id" => "41302", "qual" => "4", "name" => "Hateful Gladiator's Wyrmhide Legguards" ),
	array( "id" => "41659", "qual" => "4", "name" => "Hateful Gladiator's Dragonhide Robes" ),
	array( "id" => "41771", "qual" => "4", "name" => "Hateful Gladiator's Dragonhide Gloves" ),
	array( "id" => "41665", "qual" => "4", "name" => "Hateful Gladiator's Dragonhide Legguards" ),
	array( "id" => "41308", "qual" => "4", "name" => "Hateful Gladiator's Kodohide Robes" ),
	array( "id" => "41284", "qual" => "4", "name" => "Hateful Gladiator's Kodohide Gloves" ),
	array( "id" => "41296", "qual" => "4", "name" => "Hateful Gladiator's Kodohide Legguards" ),
	array( "id" => "41648", "qual" => "4", "name" => "Hateful Gladiator's Leather Tunic" ),
	array( "id" => "41765", "qual" => "4", "name" => "Hateful Gladiator's Leather Gloves" ),
	array( "id" => "41653", "qual" => "4", "name" => "Hateful Gladiator's Leather Legguards" ),
	array( "id" => "39579", "qual" => "4", "name" => "Heroes' Cryptstalker Tunic" ),
	array( "id" => "39582", "qual" => "4", "name" => "Heroes' Cryptstalker Handguards" ),
	array( "id" => "39580", "qual" => "4", "name" => "Heroes' Cryptstalker Legguards" ),
	array( "id" => "39592", "qual" => "4", "name" => "Heroes' Earthshatter Hauberk" ),
	array( "id" => "39593", "qual" => "4", "name" => "Heroes' Earthshatter Gloves" ),
	array( "id" => "39595", "qual" => "4", "name" => "Heroes' Earthshatter Kilt" ),
	array( "id" => "39597", "qual" => "4", "name" => "Heroes' Earthshatter Chestguard" ),
	array( "id" => "39601", "qual" => "4", "name" => "Heroes' Earthshatter Grips" ),
	array( "id" => "39603", "qual" => "4", "name" => "Heroes' Earthshatter War-Kilt" ),
	array( "id" => "39588", "qual" => "4", "name" => "Heroes' Earthshatter Tunic" ),
	array( "id" => "39591", "qual" => "4", "name" => "Heroes' Earthshatter Handguards" ),
	array( "id" => "39589", "qual" => "4", "name" => "Heroes' Earthshatter Legguards" ),
	array( "id" => "41085", "qual" => "4", "name" => "Hateful Gladiator's Chain Armor" ),
	array( "id" => "41141", "qual" => "4", "name" => "Hateful Gladiator's Chain Gauntlets" ),
	array( "id" => "41203", "qual" => "4", "name" => "Hateful Gladiator's Chain Leggings" ),
	array( "id" => "40989", "qual" => "4", "name" => "Hateful Gladiator's Mail Armor" ),
	array( "id" => "41005", "qual" => "4", "name" => "Hateful Gladiator's Mail Gauntlets" ),
	array( "id" => "41031", "qual" => "4", "name" => "Hateful Gladiator's Mail Leggings" ),
	array( "id" => "41079", "qual" => "4", "name" => "Hateful Gladiator's Linked Armor" ),
	array( "id" => "41135", "qual" => "4", "name" => "Hateful Gladiator's Linked Gauntlets" ),
	array( "id" => "41162", "qual" => "4", "name" => "Hateful Gladiator's Linked Leggings" ),
	array( "id" => "40988", "qual" => "4", "name" => "Hateful Gladiator's Ringmail Armor" ),
	array( "id" => "40999", "qual" => "4", "name" => "Hateful Gladiator's Ringmail Gauntlets" ),
	array( "id" => "41025", "qual" => "4", "name" => "Hateful Gladiator's Ringmail Leggings" ),
	array( "id" => "39617", "qual" => "4", "name" => "Heroes' Scourgeborne Battleplate" ),
	array( "id" => "39618", "qual" => "4", "name" => "Heroes' Scourgeborne Gauntlets" ),
	array( "id" => "39620", "qual" => "4", "name" => "Heroes' Scourgeborne Legplates" ),
	array( "id" => "39623", "qual" => "4", "name" => "Heroes' Scourgeborne Chestguard" ),
	array( "id" => "39624", "qual" => "4", "name" => "Heroes' Scourgeborne Handguards" ),
	array( "id" => "39626", "qual" => "4", "name" => "Heroes' Scourgeborne Legguards" ),
	array( "id" => "39629", "qual" => "4", "name" => "Heroes' Redemption Tunic" ),
	array( "id" => "39632", "qual" => "4", "name" => "Heroes' Redemption Gloves" ),
	array( "id" => "39630", "qual" => "4", "name" => "Heroes' Redemption Greaves" ),
	array( "id" => "39633", "qual" => "4", "name" => "Heroes' Redemption Chestpiece" ),
	array( "id" => "39634", "qual" => "4", "name" => "Heroes' Redemption Gauntlets" ),
	array( "id" => "39636", "qual" => "4", "name" => "Heroes' Redemption Legplates" ),
	array( "id" => "40781", "qual" => "4", "name" => "Hateful Gladiator's Dreadplate Chestpiece" ),
	array( "id" => "40803", "qual" => "4", "name" => "Hateful Gladiator's Dreadplate Gauntlets" ),
	array( "id" => "40841", "qual" => "4", "name" => "Hateful Gladiator's Dreadplate Legguards" ),
	array( "id" => "40925", "qual" => "4", "name" => "Hateful Gladiator's Ornamented Gloves" ),
	array( "id" => "40904", "qual" => "4", "name" => "Hateful Gladiator's Ornamented Chestguard" ),
	array( "id" => "40937", "qual" => "4", "name" => "Hateful Gladiator's Ornamented Legplates" ),
	array( "id" => "40782", "qual" => "4", "name" => "Hateful Gladiator's Scaled Chestpiece" ),
	array( "id" => "40802", "qual" => "4", "name" => "Hateful Gladiator's Scaled Gauntlets" ),
	array( "id" => "40842", "qual" => "4", "name" => "Hateful Gladiator's Scaled Legguards" ),
	array( "id" => "39638", "qual" => "4", "name" => "Heroes' Redemption Breastplate" ),
	array( "id" => "39639", "qual" => "4", "name" => "Heroes' Redemption Handguards" ),
	array( "id" => "39641", "qual" => "4", "name" => "Heroes' Redemption Legguards" ),
	array( "id" => "39606", "qual" => "4", "name" => "Heroes' Dreadnaught Battleplate" ),
	array( "id" => "39609", "qual" => "4", "name" => "Heroes' Dreadnaught Gauntlets" ),
	array( "id" => "39607", "qual" => "4", "name" => "Heroes' Dreadnaught Legplates" ),
	array( "id" => "39611", "qual" => "4", "name" => "Heroes' Dreadnaught Breastplate" ),
	array( "id" => "39622", "qual" => "4", "name" => "Heroes' Dreadnaught Handguards" ),
	array( "id" => "39612", "qual" => "4", "name" => "Heroes' Dreadnaught Legguards" ),
	array( "id" => "40752", "qual" => "4", "name" => "Emblem of Heroism" ),
	array( "id" => "43959", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "44083", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "40783", "qual" => "4", "name" => "Hateful Gladiator's Plate Chestpiece" ),
	array( "id" => "40801", "qual" => "4", "name" => "Hateful Gladiator's Plate Gauntlets" ),
	array( "id" => "40840", "qual" => "4", "name" => "Hateful Gladiator's Plate Legguards" ),
);
?>