<?php
$loot = array(
	array( "id" => "40428", "qual" => "4", "name" => "Titan's Outlook" ),
	array( "id" => "40427", "qual" => "4", "name" => "Circle of Arcane Streams" ),
	array( "id" => "40426", "qual" => "4", "name" => "Signet of the Accord" ),
	array( "id" => "40433", "qual" => "4", "name" => "Wyrmrest Band" ),
	array( "id" => "40430", "qual" => "4", "name" => "Majestic Dragon Figurine" ),
	array( "id" => "40429", "qual" => "4", "name" => "Crimson Steel" ),
	array( "id" => "43345", "qual" => "4", "name" => "Dragon Hide Bag" ),
	array( "id" => "43347", "qual" => "4", "name" => "Satchel of Spoils" ),
	array( "id" => "40613", "qual" => "4", "name" => "Gloves of the Lost Conqueror" ),
	array( "id" => "40614", "qual" => "4", "name" => "Gloves of the Lost Protector" ),
	array( "id" => "40615", "qual" => "4", "name" => "Gloves of the Lost Vanquisher" ),
	array( "id" => "43988", "qual" => "4", "name" => "Gale-Proof Cloak" ),
	array( "id" => "43990", "qual" => "4", "name" => "Blade-Scarred Tunic" ),
	array( "id" => "43991", "qual" => "4", "name" => "Legguards of Composure" ),
	array( "id" => "43989", "qual" => "4", "name" => "Remembrance Gridle" ),
	array( "id" => "43992", "qual" => "4", "name" => "Volitant Amulet" ),
	array( "id" => "43995", "qual" => "4", "name" => "Enamored Cowl" ),
	array( "id" => "43998", "qual" => "4", "name" => "Chestguard of Flagrant Prowess" ),
	array( "id" => "43996", "qual" => "4", "name" => "Sabatons of Firmament" ),
	array( "id" => "43994", "qual" => "4", "name" => "Belabored Legplates" ),
	array( "id" => "43993", "qual" => "4", "name" => "Greatring of Collision" ),
);
?>