<?php
$loot = array(
	array( "id" => "39732", "qual" => "4", "name" => "Faerlina's Madness" ),
	array( "id" => "39731", "qual" => "4", "name" => "Punctilious Bindings" ),
	array( "id" => "39733", "qual" => "4", "name" => "Gloves of Token Respect" ),
	array( "id" => "39735", "qual" => "4", "name" => "Belt of False Dignity" ),
	array( "id" => "39756", "qual" => "4", "name" => "Tunic of Prejudice" ),
	array( "id" => "39727", "qual" => "4", "name" => "Dislocating Handguards" ),
	array( "id" => "39724", "qual" => "4", "name" => "Cult's Chestguard" ),
	array( "id" => "39734", "qual" => "4", "name" => "Atonement Greaves" ),
	array( "id" => "39723", "qual" => "4", "name" => "Fire-Scorched Greathelm" ),
	array( "id" => "39725", "qual" => "4", "name" => "Epaulets of the Grieving Servant" ),
	array( "id" => "39729", "qual" => "4", "name" => "Bracers of the Tyrant" ),
	array( "id" => "39726", "qual" => "4", "name" => "Callous-Hearted Gauntlets" ),
	array( "id" => "40071", "qual" => "4", "name" => "Chains of Adoration" ),
	array( "id" => "40065", "qual" => "4", "name" => "Fool's Trial" ),
	array( "id" => "40069", "qual" => "4", "name" => "Heritage" ),
	array( "id" => "40064", "qual" => "4", "name" => "Thunderstorm Amulet" ),
	array( "id" => "40080", "qual" => "4", "name" => "Lost Jewel" ),
	array( "id" => "40075", "qual" => "4", "name" => "Ruthlessness" ),
	array( "id" => "40107", "qual" => "4", "name" => "Sand-Worn Band" ),
	array( "id" => "40108", "qual" => "4", "name" => "Seized Beauty" ),
	array( "id" => "40074", "qual" => "4", "name" => "Strong-Handed Ring" ),
	array( "id" => "39757", "qual" => "4", "name" => "Idol of Worship" ),
	array( "id" => "39728", "qual" => "4", "name" => "Totem of Misery" ),
	array( "id" => "39730", "qual" => "4", "name" => "Widow's Fury" ),
);
?>