<?php
$loot = array(
	array( "id" => "40418", "qual" => "4", "name" => "Valorous Frostfire Robe" ),
	array( "id" => "40415", "qual" => "4", "name" => "Valorous Frostfire Gloves" ),
	array( "id" => "40417", "qual" => "4", "name" => "Valorous Frostfire Leggings" ),
	array( "id" => "40449", "qual" => "4", "name" => "Valorous Robe of Faith" ),
	array( "id" => "40445", "qual" => "4", "name" => "Valorous Gloves of Faith" ),
	array( "id" => "40448", "qual" => "4", "name" => "Valorous Leggings of Faith" ),
	array( "id" => "40458", "qual" => "4", "name" => "Valorous Raiments of Faith" ),
	array( "id" => "40454", "qual" => "4", "name" => "Valorous Handwraps of Faith" ),
	array( "id" => "40457", "qual" => "4", "name" => "Valorous Pants of Faith" ),
	array( "id" => "40423", "qual" => "4", "name" => "Valorous Plagueheart Robe" ),
	array( "id" => "40420", "qual" => "4", "name" => "Valorous Plagueheart Gloves" ),
	array( "id" => "40422", "qual" => "4", "name" => "Valorous Plagueheart Leggings" ),
	array( "id" => "41951", "qual" => "4", "name" => "Deadly Gladiator's Silk Raiment" ),
	array( "id" => "41970", "qual" => "4", "name" => "Deadly Gladiator's Silk Handguards" ),
	array( "id" => "41958", "qual" => "4", "name" => "Deadly Gladiator's Silk Trousers" ),
	array( "id" => "41858", "qual" => "4", "name" => "Deadly Gladiator's Mooncloth Robe" ),
	array( "id" => "41873", "qual" => "4", "name" => "Deadly Gladiator's Mooncloth Gloves" ),
	array( "id" => "41863", "qual" => "4", "name" => "Deadly Gladiator's Mooncloth Leggings" ),
	array( "id" => "41920", "qual" => "4", "name" => "Deadly Gladiator's Satin Robe" ),
	array( "id" => "41939", "qual" => "4", "name" => "Deadly Gladiator's Satin Gloves" ),
	array( "id" => "41926", "qual" => "4", "name" => "Deadly Gladiator's Satin Leggings" ),
	array( "id" => "41997", "qual" => "4", "name" => "Deadly Gladiator's Felweave Raiment" ),
	array( "id" => "42016", "qual" => "4", "name" => "Deadly Gladiator's Felweave Handguards" ),
	array( "id" => "42004", "qual" => "4", "name" => "Deadly Gladiator's Felweave Trousers" ),
	array( "id" => "40469", "qual" => "4", "name" => "Valorous Dreamwalker Vestments" ),
	array( "id" => "40466", "qual" => "4", "name" => "Valorous Dreamwalker Gloves" ),
	array( "id" => "40468", "qual" => "4", "name" => "Valorous Dreamwalker Trousers" ),
	array( "id" => "40471", "qual" => "4", "name" => "Valorous Dreamwalker Raiments" ),
	array( "id" => "40472", "qual" => "4", "name" => "Valorous Dreamwalker Handgrips" ),
	array( "id" => "40493", "qual" => "4", "name" => "Valorous Dreamwalker Legguards" ),
	array( "id" => "40463", "qual" => "4", "name" => "Valorous Dreamwalker Robe" ),
	array( "id" => "40460", "qual" => "4", "name" => "Valorous Dreamwalker Handguards" ),
	array( "id" => "40462", "qual" => "4", "name" => "Valorous Dreamwalker Leggings" ),
	array( "id" => "40495", "qual" => "4", "name" => "Valorous Bonescythe Breastplate" ),
	array( "id" => "40496", "qual" => "4", "name" => "Valorous Bonescythe Gauntlets" ),
	array( "id" => "40500", "qual" => "4", "name" => "Valorous Bonescythe Legplates" ),
	array( "id" => "41315", "qual" => "4", "name" => "Deadly Gladiator's Wyrmhide Robes" ),
	array( "id" => "41292", "qual" => "4", "name" => "Deadly Gladiator's Wyrmhide Gloves" ),
	array( "id" => "41303", "qual" => "4", "name" => "Deadly Gladiator's Wyrmhide Legguards" ),
	array( "id" => "41660", "qual" => "4", "name" => "Deadly Gladiator's Dragonhide Robes" ),
	array( "id" => "41772", "qual" => "4", "name" => "Deadly Gladiator's Dragonhide Gloves" ),
	array( "id" => "41666", "qual" => "4", "name" => "Deadly Gladiator's Dragonhide Legguards" ),
	array( "id" => "41309", "qual" => "4", "name" => "Deadly Gladiator's Kodohide Robes" ),
	array( "id" => "41286", "qual" => "4", "name" => "Deadly Gladiator's Kodohide Gloves" ),
	array( "id" => "41297", "qual" => "4", "name" => "Deadly Gladiator's Kodohide Legguards" ),
	array( "id" => "41649", "qual" => "4", "name" => "Deadly Gladiator's Leather Tunic" ),
	array( "id" => "41766", "qual" => "4", "name" => "Deadly Gladiator's Leather Gloves" ),
	array( "id" => "41654", "qual" => "4", "name" => "Deadly Gladiator's Leather Legguards" ),
	array( "id" => "40503", "qual" => "4", "name" => "Valorous Cryptstalker Tunic" ),
	array( "id" => "40504", "qual" => "4", "name" => "Valorous Cryptstalker Handguards" ),
	array( "id" => "40506", "qual" => "4", "name" => "Valorous Cryptstalker Legguards" ),
	array( "id" => "40514", "qual" => "4", "name" => "Valorous Earthshatter Hauberk" ),
	array( "id" => "40515", "qual" => "4", "name" => "Valorous Earthshatter Gloves" ),
	array( "id" => "40517", "qual" => "4", "name" => "Valorous Earthshatter Kilt" ),
	array( "id" => "40523", "qual" => "4", "name" => "Valorous Earthshatter Chestguard" ),
	array( "id" => "40520", "qual" => "4", "name" => "Valorous Earthshatter Grips" ),
	array( "id" => "40522", "qual" => "4", "name" => "Valorous Earthshatter War-Kilt" ),
	array( "id" => "40508", "qual" => "4", "name" => "Valorous Earthshatter Tunic" ),
	array( "id" => "40509", "qual" => "4", "name" => "Valorous Earthshatter Handguards" ),
	array( "id" => "40512", "qual" => "4", "name" => "Valorous Earthshatter Legguards" ),
	array( "id" => "41086", "qual" => "4", "name" => "Deadly Gladiator's Chain Armor" ),
	array( "id" => "41142", "qual" => "4", "name" => "Deadly Gladiator's Chain Gauntlets" ),
	array( "id" => "41204", "qual" => "4", "name" => "Deadly Gladiator's Chain Leggings" ),
	array( "id" => "40991", "qual" => "4", "name" => "Deadly Gladiator's Mail Armor" ),
	array( "id" => "41006", "qual" => "4", "name" => "Deadly Gladiator's Mail Gauntlets" ),
	array( "id" => "41032", "qual" => "4", "name" => "Deadly Gladiator's Mail Leggings" ),
	array( "id" => "41080", "qual" => "4", "name" => "Deadly Gladiator's Linked Armor" ),
	array( "id" => "41136", "qual" => "4", "name" => "Deadly Gladiator's Linked Gauntlets" ),
	array( "id" => "41198", "qual" => "4", "name" => "Deadly Gladiator's Linked Leggings" ),
	array( "id" => "40990", "qual" => "4", "name" => "Deadly Gladiator's Ringmail Armor" ),
	array( "id" => "41000", "qual" => "4", "name" => "Deadly Gladiator's Ringmail Gauntlets" ),
	array( "id" => "41026", "qual" => "4", "name" => "Deadly Gladiator's Ringmail Leggings" ),
	array( "id" => "40550", "qual" => "4", "name" => "Valorous Scourgeborne Battleplate" ),
	array( "id" => "40552", "qual" => "4", "name" => "Valorous Scourgeborne Gauntlets" ),
	array( "id" => "40556", "qual" => "4", "name" => "Valorous Scourgeborne Legplates" ),
	array( "id" => "40559", "qual" => "4", "name" => "Valorous Scourgeborne Chestguard" ),
	array( "id" => "40563", "qual" => "4", "name" => "Valorous Scourgeborne Handguards" ),
	array( "id" => "40567", "qual" => "4", "name" => "Valorous Scourgeborne Legguards" ),
	array( "id" => "40569", "qual" => "4", "name" => "Valorous Redemption Tunic" ),
	array( "id" => "40570", "qual" => "4", "name" => "Valorous Redemption Gloves" ),
	array( "id" => "40572", "qual" => "4", "name" => "Valorous Redemption Greaves" ),
	array( "id" => "40574", "qual" => "4", "name" => "Valorous Redemption Chestpiece" ),
	array( "id" => "40575", "qual" => "4", "name" => "Valorous Redemption Gauntlets" ),
	array( "id" => "40577", "qual" => "4", "name" => "Valorous Redemption Legplates" ),
	array( "id" => "40784", "qual" => "4", "name" => "Deadly Gladiator's Dreadplate Chestpiece" ),
	array( "id" => "40806", "qual" => "4", "name" => "Deadly Gladiator's Dreadplate Gauntlets" ),
	array( "id" => "40845", "qual" => "4", "name" => "Deadly Gladiator's Dreadplate Legguards" ),
	array( "id" => "40785", "qual" => "4", "name" => "Deadly Gladiator's Scaled Chestpiece" ),
	array( "id" => "40805", "qual" => "4", "name" => "Deadly Gladiator's Scaled Gauntlets" ),
	array( "id" => "40846", "qual" => "4", "name" => "Deadly Gladiator's Scaled Legguards" ),
	array( "id" => "40905", "qual" => "4", "name" => "Deadly Gladiator's Ornamented Chestguard" ),
	array( "id" => "40926", "qual" => "4", "name" => "Deadly Gladiator's Ornamented Gloves" ),
	array( "id" => "40938", "qual" => "4", "name" => "Deadly Gladiator's Ornamented Legplates" ),
	array( "id" => "40579", "qual" => "4", "name" => "Valorous Redemption Breastplate" ),
	array( "id" => "40580", "qual" => "4", "name" => "Valorous Redemption Handguards" ),
	array( "id" => "40583", "qual" => "4", "name" => "Valorous Redemption Legguards" ),
	array( "id" => "40525", "qual" => "4", "name" => "Valorous Dreadnaught Battleplate" ),
	array( "id" => "40527", "qual" => "4", "name" => "Valorous Dreadnaught Gauntlets" ),
	array( "id" => "40529", "qual" => "4", "name" => "Valorous Dreadnaught Legplates" ),
	array( "id" => "40544", "qual" => "4", "name" => "Valorous Dreadnaught Breastplate" ),
	array( "id" => "40545", "qual" => "4", "name" => "Valorous Dreadnaught Handguards" ),
	array( "id" => "40547", "qual" => "4", "name" => "Valorous Dreadnaught Legguards" ),
	array( "id" => "40753", "qual" => "4", "name" => "Emblem of Valor" ),
	array( "id" => "43959", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "44083", "qual" => "4", "name" => "Reins of the Grand Black War Mammoth" ),
	array( "id" => "40786", "qual" => "4", "name" => "Deadly Gladiator's Plate Chestpiece" ),
	array( "id" => "40804", "qual" => "4", "name" => "Deadly Gladiator's Plate Gauntlets" ),
	array( "id" => "40844", "qual" => "4", "name" => "Deadly Gladiator's Plate Legguards" ),
);
?>