<?php
$loot = array(
	array( "id" => "40194", "qual" => "4", "name" => "Blanketing Robes of Snow" ),
	array( "id" => "40602", "qual" => "4", "name" => "Robes of Mutation" ),
	array( "id" => "40198", "qual" => "4", "name" => "Bands of Impurity" ),
	array( "id" => "40197", "qual" => "4", "name" => "Gloves of the Fallen Wizard" ),
	array( "id" => "40186", "qual" => "4", "name" => "Thrusting Bands" ),
	array( "id" => "40200", "qual" => "4", "name" => "Belt of Potent Chanting" ),
	array( "id" => "40193", "qual" => "4", "name" => "Tunic of Masked Suffering" ),
	array( "id" => "40196", "qual" => "4", "name" => "Legguards of the Undisturbed" ),
	array( "id" => "40184", "qual" => "4", "name" => "Crippled Treads" ),
	array( "id" => "40185", "qual" => "4", "name" => "Shoulderguards of Opportunity" ),
	array( "id" => "40188", "qual" => "4", "name" => "Gauntlets of the Disobedient" ),
	array( "id" => "40187", "qual" => "4", "name" => "Poignant Sabatons" ),
	array( "id" => "40071", "qual" => "4", "name" => "Chains of Adoration" ),
	array( "id" => "40065", "qual" => "4", "name" => "Fool's Trial" ),
	array( "id" => "40069", "qual" => "4", "name" => "Heritage" ),
	array( "id" => "40064", "qual" => "4", "name" => "Thunderstorm Amulet" ),
	array( "id" => "40080", "qual" => "4", "name" => "Lost Jewel" ),
	array( "id" => "40075", "qual" => "4", "name" => "Ruthlessness" ),
	array( "id" => "40107", "qual" => "4", "name" => "Sand-Worn Band" ),
	array( "id" => "40074", "qual" => "4", "name" => "Strong-Handed Ring" ),
	array( "id" => "40192", "qual" => "4", "name" => "Accursed Spine" ),
	array( "id" => "40191", "qual" => "4", "name" => "Libram of Radiance" ),
	array( "id" => "40189", "qual" => "4", "name" => "Angry Dread" ),
	array( "id" => "40190", "qual" => "4", "name" => "Spinning Fate" ),
);
?>