<?php
$loot = array(
	array( "id" => "49307", "qual" => "4", "name" => "Fluttering Sapphiron Drape" ),
	array( "id" => "49316", "qual" => "4", "name" => "Circlet of Transcendence" ),
	array( "id" => "49317", "qual" => "4", "name" => "Coronet of Transcendence" ),
	array( "id" => "49315", "qual" => "4", "name" => "Nemesis Skullcover" ),
	array( "id" => "49318", "qual" => "4", "name" => "Netherwind Hood" ),
	array( "id" => "49322", "qual" => "4", "name" => "Bloodfang Mask" ),
	array( "id" => "49327", "qual" => "4", "name" => "Stormrage Antlers" ),
	array( "id" => "49328", "qual" => "4", "name" => "Stormrage Helm" ),
	array( "id" => "49326", "qual" => "4", "name" => "Stormrage Hood" ),
	array( "id" => "49331", "qual" => "4", "name" => "Coif of Ten Storms" ),
	array( "id" => "49330", "qual" => "4", "name" => "Cowl of Ten Storms" ),
	array( "id" => "49329", "qual" => "4", "name" => "Gaze of Ten Storms" ),
	array( "id" => "49319", "qual" => "4", "name" => "Dragonstalker's Helmet" ),
	array( "id" => "49320", "qual" => "4", "name" => "Faceguard of Wrath" ),
	array( "id" => "49321", "qual" => "4", "name" => "Greathelm of Wrath" ),
	array( "id" => "49333", "qual" => "4", "name" => "Frostforged Helmet" ),
	array( "id" => "49332", "qual" => "4", "name" => "Frostforged Ringhelm" ),
	array( "id" => "49323", "qual" => "4", "name" => "Judgement Cover" ),
	array( "id" => "49325", "qual" => "4", "name" => "Judgement Helm" ),
	array( "id" => "49324", "qual" => "4", "name" => "Judgement Helmet" ),
	array( "id" => "49306", "qual" => "4", "name" => "Eskhandar's Choker" ),
	array( "id" => "49309", "qual" => "4", "name" => "Runed Ring of Binding" ),
	array( "id" => "49463", "qual" => "4", "name" => "Purified Shard of the Flame" ),
	array( "id" => "49310", "qual" => "4", "name" => "Purified Shard of the Scale" ),
	array( "id" => "49308", "qual" => "4", "name" => "Antique Cornerstone Grimoire" ),
	array( "id" => "49304", "qual" => "4", "name" => "Sharpened Fang of the Mystics" ),
	array( "id" => "49437", "qual" => "4", "name" => "Rusted Gutgore Ripper" ),
	array( "id" => "49298", "qual" => "4", "name" => "Glinting Azuresong Mageblade" ),
	array( "id" => "49303", "qual" => "4", "name" => "Gleaming Quel'Serrar" ),
	array( "id" => "49296", "qual" => "4", "name" => "Singed Vis'kag the Bloodletter" ),
	array( "id" => "49299", "qual" => "4", "name" => "Keen Obsidian Edged Blade" ),
	array( "id" => "49297", "qual" => "4", "name" => "Empowered Deathbringer" ),
	array( "id" => "49302", "qual" => "4", "name" => "Reclaimed Shadowstrike" ),
	array( "id" => "49301", "qual" => "4", "name" => "Reclaimed Thunderstrike" ),
	array( "id" => "49305", "qual" => "4", "name" => "Snub-Nose Blastershot Launcher" ),
	array( "id" => "49644", "qual" => "4", "name" => "Head of Onyxia" ),
	array( "id" => "49485", "qual" => "4", "name" => "Sparkling Onyxia Tooth Pendant" ),
	array( "id" => "49486", "qual" => "4", "name" => "Polished Dragonslayer's Signet" ),
	array( "id" => "49487", "qual" => "4", "name" => "Purified Onyxia Blood Talisman" ),
	array( "id" => "49295", "qual" => "4", "name" => "Enlarged Onyxia Hide Backpack" ),
	array( "id" => "49294", "qual" => "4", "name" => "Ashen Sack of Gems" ),
	array( "id" => "49636", "qual" => "4", "name" => "Reins of the Onyxian Drake" ),
);

?>