<?php
$loot = array(
array( "id" => "71107", "qual" => "4", "name" => "Obsidian Arborweave Gloves" ),
array( "id" => "71109", "qual" => "4", "name" => "Obsidian Arborweave Leggings" ),
array( "id" => "71097", "qual" => "4", "name" => "Obsidian Arborweave Grips" ),
array( "id" => "71099", "qual" => "4", "name" => "Obsidian Arborweave Legguards" ),
array( "id" => "71102", "qual" => "4", "name" => "Obsidian Arborweave Handwraps" ),
array( "id" => "71104", "qual" => "4", "name" => "Obsidian Arborweave Legwraps" ),
array( "id" => "70289", "qual" => "4", "name" => "Ruthless Gladiator's Wyrmhide Gloves" ),
array( "id" => "70291", "qual" => "4", "name" => "Ruthless Gladiator's Wyrmhide Legguards" ),
array( "id" => "70279", "qual" => "4", "name" => "Ruthless Gladiator's Dragonhide Gloves" ),
array( "id" => "70281", "qual" => "4", "name" => "Ruthless Gladiator's Dragonhide Legguards" ),
array( "id" => "70284", "qual" => "4", "name" => "Ruthless Gladiator's Kodohide Gloves" ),
array( "id" => "70286", "qual" => "4", "name" => "Ruthless Gladiator's Kodohide Legguards" ),
array( "id" => "71286", "qual" => "4", "name" => "Firehawk Gloves" ),
array( "id" => "71288", "qual" => "4", "name" => "Firehawk Leggings" ),
array( "id" => "71050", "qual" => "4", "name" => "Flamewaker's Gloves" ),
array( "id" => "71052", "qual" => "4", "name" => "Flamewaker's Legguards" ),
array( "id" => "71046", "qual" => "4", "name" => "Dark Phoenix Gloves" ),
array( "id" => "71048", "qual" => "4", "name" => "Dark Phoenix Legguards" ),
array( "id" => "71281", "qual" => "4", "name" => "Balespider's Handwraps" ),
array( "id" => "71283", "qual" => "4", "name" => "Balespider's Leggings" ),
array( "id" => "70299", "qual" => "4", "name" => "Ruthless Gladiator's Silk Handguards" ),
array( "id" => "70301", "qual" => "4", "name" => "Ruthless Gladiator's Silk Trousers" ),
array( "id" => "70260", "qual" => "4", "name" => "Ruthless Gladiator's Chain Gauntlets" ),
array( "id" => "70262", "qual" => "4", "name" => "Ruthless Gladiator's Chain Leggings" ),
array( "id" => "70295", "qual" => "4", "name" => "Ruthless Gladiator's Leather Gloves" ),
array( "id" => "70297", "qual" => "4", "name" => "Ruthless Gladiator's Leather Legguards" ),
array( "id" => "70314", "qual" => "4", "name" => "Ruthless Gladiator's Felweave Handguards" ),
array( "id" => "70316", "qual" => "4", "name" => "Ruthless Gladiator's Felweave Trousers" ),
array( "id" => "71092", "qual" => "4", "name" => "Immolation Gloves" ),
array( "id" => "71094", "qual" => "4", "name" => "Immolation Greaves" ),
array( "id" => "71064", "qual" => "4", "name" => "Immolation Gauntlets" ),
array( "id" => "71066", "qual" => "4", "name" => "Immolation Legplates" ),
array( "id" => "70949", "qual" => "4", "name" => "Immolation Handguards" ),
array( "id" => "70947", "qual" => "4", "name" => "Immolation Legguards" ),
array( "id" => "70354", "qual" => "4", "name" => "Ruthless Gladiator's Ornamented Gloves" ),
array( "id" => "70356", "qual" => "4", "name" => "Ruthless Gladiator's Ornamented Legplates" ),
array( "id" => "70250", "qual" => "4", "name" => "Ruthless Gladiator's Scaled Gauntlets" ),
array( "id" => "70252", "qual" => "4", "name" => "Ruthless Gladiator's Scaled Legguards" ),
array( "id" => "71271", "qual" => "4", "name" => "Handwraps of the Cleansing Flame" ),
array( "id" => "71273", "qual" => "4", "name" => "Legwraps of the Cleansing Flame" ),
array( "id" => "71276", "qual" => "4", "name" => "Gloves of the Cleansing Flame" ),
array( "id" => "71278", "qual" => "4", "name" => "Leggings of the Cleansing Flame" ),
array( "id" => "70309", "qual" => "4", "name" => "Ruthless Gladiator's Satin Gloves" ),
array( "id" => "70311", "qual" => "4", "name" => "Ruthless Gladiator's Satin Leggings" ),
array( "id" => "70304", "qual" => "4", "name" => "Ruthless Gladiator's Mooncloth Gloves" ),
array( "id" => "70306", "qual" => "4", "name" => "Ruthless Gladiator's Mooncloth Leggings" ),
array( "id" => "71292", "qual" => "4", "name" => "Erupting Volcanic Gloves" ),
array( "id" => "71291", "qual" => "4", "name" => "Erupting Volcanic Kilt" ),
array( "id" => "71302", "qual" => "4", "name" => "Erupting Volcanic Grips" ),
array( "id" => "71304", "qual" => "4", "name" => "Erupting Volcanic Legguards" ),
array( "id" => "71297", "qual" => "4", "name" => "Erupting Volcanic Handwraps" ),
array( "id" => "71299", "qual" => "4", "name" => "Erupting Volcanic Legwraps" ),
array( "id" => "70275", "qual" => "4", "name" => "Ruthless Gladiator's Mail Gauntlets" ),
array( "id" => "70277", "qual" => "4", "name" => "Ruthless Gladiator's Mail Leggings" ),
array( "id" => "70270", "qual" => "4", "name" => "Ruthless Gladiator's Linked Gauntlets" ),
array( "id" => "70272", "qual" => "4", "name" => "Ruthless Gladiator's Linked Leggings" ),
array( "id" => "70265", "qual" => "4", "name" => "Ruthless Gladiator's Ringmail Gauntlets" ),
array( "id" => "70267", "qual" => "4", "name" => "Ruthless Gladiator's Ringmail Leggings" ),
array( "id" => "71059", "qual" => "4", "name" => "Elementium Deathplate Gauntlets" ),
array( "id" => "71061", "qual" => "4", "name" => "Elementium Deathplate Greaves" ),
array( "id" => "70953", "qual" => "4", "name" => "Elementium Deathplate Handguards" ),
array( "id" => "70952", "qual" => "4", "name" => "Elementium Deathplate Legguards" ),
array( "id" => "71069", "qual" => "4", "name" => "Gauntlets of the Molten Giant" ),
array( "id" => "71071", "qual" => "4", "name" => "Legplates of the Molten Giant" ),
array( "id" => "70943", "qual" => "4", "name" => "Handguards of the Molten Giant" ),
array( "id" => "70942", "qual" => "4", "name" => "Legguards of the Molten Giant" ),
array( "id" => "70245", "qual" => "4", "name" => "Ruthless Gladiator's Dreadplate Gauntlets" ),
array( "id" => "70247", "qual" => "4", "name" => "Ruthless Gladiator's Dreadplate Legguards" ),
array( "id" => "70255", "qual" => "4", "name" => "Ruthless Gladiator's Plate Gauntlets" ),
array( "id" => "70257", "qual" => "4", "name" => "Ruthless Gladiator's Plate Legguards" ),
array( "id" => "70363", "qual" => "4", "name" => "Ruthless Gladiator's Cuffs of Accuracy" ),
array( "id" => "70362", "qual" => "4", "name" => "Ruthless Gladiator's Cord of Accuracy" ),
array( "id" => "70364", "qual" => "4", "name" => "Ruthless Gladiator's Treads of Alacrity" ),
array( "id" => "70366", "qual" => "4", "name" => "Ruthless Gladiator's Cuffs of Meditation" ),
array( "id" => "70368", "qual" => "4", "name" => "Ruthless Gladiator's Cord of Meditation" ),
array( "id" => "70367", "qual" => "4", "name" => "Ruthless Gladiator's Treads of Meditation" ),
array( "id" => "70365", "qual" => "4", "name" => "Ruthless Gladiator's Cuffs of Prowess" ),
array( "id" => "70360", "qual" => "4", "name" => "Ruthless Gladiator's Cord of Cruelty" ),
array( "id" => "70361", "qual" => "4", "name" => "Ruthless Gladiator's Treads of Cruelty" ),
array( "id" => "70350", "qual" => "4", "name" => "Ruthless Gladiator's Armwraps of Accuracy" ),
array( "id" => "70349", "qual" => "4", "name" => "Ruthless Gladiator's Waistband of Accuracy" ),
array( "id" => "70348", "qual" => "4", "name" => "Ruthless Gladiator's Boots of Cruelty" ),
array( "id" => "70352", "qual" => "4", "name" => "Ruthless Gladiator's Armwraps of Alacrity" ),
array( "id" => "70347", "qual" => "4", "name" => "Ruthless Gladiator's Waistband of Cruelty" ),
array( "id" => "70351", "qual" => "4", "name" => "Ruthless Gladiator's Boots of Alacrity" ),
array( "id" => "70359", "qual" => "4", "name" => "Ruthless Gladiator's Bindings of Prowess" ),
array( "id" => "70346", "qual" => "4", "name" => "Ruthless Gladiator's Belt of Cruelty" ),
array( "id" => "70358", "qual" => "4", "name" => "Ruthless Gladiator's Footguards of Alacrity" ),
array( "id" => "70345", "qual" => "4", "name" => "Ruthless Gladiator's Bindings of Meditation" ),
array( "id" => "70343", "qual" => "4", "name" => "Ruthless Gladiator's Belt of Meditation" ),
array( "id" => "70344", "qual" => "4", "name" => "Ruthless Gladiator's Footguards of Meditation" ),
array( "id" => "70330", "qual" => "4", "name" => "Ruthless Gladiator's Armbands of Meditation" ),
array( "id" => "70328", "qual" => "4", "name" => "Ruthless Gladiator's Waistguard of Meditation" ),
array( "id" => "70329", "qual" => "4", "name" => "Ruthless Gladiator's Sabatons of Meditation" ),
array( "id" => "70342", "qual" => "4", "name" => "Ruthless Gladiator's Armbands of Prowess" ),
array( "id" => "70331", "qual" => "4", "name" => "Ruthless Gladiator's Waistguard of Cruelty" ),
array( "id" => "70341", "qual" => "4", "name" => "Ruthless Gladiator's Sabatons of Alacrity" ),
array( "id" => "70338", "qual" => "4", "name" => "Ruthless Gladiator's Wristguards of Alacrity" ),
array( "id" => "70336", "qual" => "4", "name" => "Ruthless Gladiator's Links of Cruelty" ),
array( "id" => "70337", "qual" => "4", "name" => "Ruthless Gladiator's Sabatons of Alacrity" ),
array( "id" => "70340", "qual" => "4", "name" => "Ruthless Gladiator's Wristguards of Accuracy" ),
array( "id" => "70339", "qual" => "4", "name" => "Ruthless Gladiator's Links of Accuracy" ),
array( "id" => "70335", "qual" => "4", "name" => "Ruthless Gladiator's Sabatons of Cruelty" ),
array( "id" => "70334", "qual" => "4", "name" => "Ruthless Gladiator's Bracers of Meditation" ),
array( "id" => "70332", "qual" => "4", "name" => "Ruthless Gladiator's Clasp of Meditation" ),
array( "id" => "70333", "qual" => "4", "name" => "Ruthless Gladiator's Greaves of Meditation" ),
array( "id" => "70327", "qual" => "4", "name" => "Ruthless Gladiator's Armplates of Proficiency" ),
array( "id" => "70326", "qual" => "4", "name" => "Ruthless Gladiator's Girdle of Prowess" ),
array( "id" => "70323", "qual" => "4", "name" => "Ruthless Gladiator's Warboots of Alacrity" ),
array( "id" => "70325", "qual" => "4", "name" => "Ruthless Gladiator's Bracers of Prowess" ),
array( "id" => "70319", "qual" => "4", "name" => "Ruthless Gladiator's Clasp of Cruelty" ),
array( "id" => "70324", "qual" => "4", "name" => "Ruthless Gladiator's Greaves of Alacrity" ),
array( "id" => "70322", "qual" => "4", "name" => "Ruthless Gladiator's Armplates of Alacrity" ),
array( "id" => "70320", "qual" => "4", "name" => "Ruthless Gladiator's Girdle of Cruelty" ),
array( "id" => "70321", "qual" => "4", "name" => "Ruthless Gladiator's Warboots of Cruelty" ),
array( "id" => "70386", "qual" => "4", "name" => "Ruthless Gladiator's Cape of Cruelty" ),
array( "id" => "70385", "qual" => "4", "name" => "Ruthless Gladiator's Cape of Prowess" ),
array( "id" => "70383", "qual" => "4", "name" => "Ruthless Gladiator's Cloak of Alacrity" ),
array( "id" => "70384", "qual" => "4", "name" => "Ruthless Gladiator's Cloak of Prowess" ),
array( "id" => "70387", "qual" => "4", "name" => "Ruthless Gladiator's Drape of Diffusion" ),
array( "id" => "70389", "qual" => "4", "name" => "Ruthless Gladiator's Drape of Meditation" ),
array( "id" => "70388", "qual" => "4", "name" => "Ruthless Gladiator's Drape of Prowess" ),
array( "id" => "70370", "qual" => "4", "name" => "Ruthless Gladiator's Band of Accuracy" ),
array( "id" => "70369", "qual" => "4", "name" => "Ruthless Gladiator's Band of Cruelty" ),
array( "id" => "70371", "qual" => "4", "name" => "Ruthless Gladiator's Band of Dominance" ),
array( "id" => "70373", "qual" => "4", "name" => "Ruthless Gladiator's Signet of Accuracy" ),
array( "id" => "70372", "qual" => "4", "name" => "Ruthless Gladiator's Signet of Cruelty" ),
array( "id" => "70374", "qual" => "4", "name" => "Ruthless Gladiator's Ring of Accuracy" ),
array( "id" => "70375", "qual" => "4", "name" => "Ruthless Gladiator's Ring of Cruelty" ),
array( "id" => "70382", "qual" => "4", "name" => "Ruthless Gladiator's Choker of Accuracy" ),
array( "id" => "70381", "qual" => "4", "name" => "Ruthless Gladiator's Choker of Proficiency" ),
array( "id" => "70380", "qual" => "4", "name" => "Ruthless Gladiator's Necklace of Proficiency" ),
array( "id" => "70379", "qual" => "4", "name" => "Ruthless Gladiator's Necklace of Prowess" ),
array( "id" => "70377", "qual" => "4", "name" => "Ruthless Gladiator's Pendant of Alacrity" ),
array( "id" => "70376", "qual" => "4", "name" => "Ruthless Gladiator's Pendant of Diffusion" ),
array( "id" => "70378", "qual" => "4", "name" => "Ruthless Gladiator's Pendant of Meditation" ),
array( "id" => "70408", "qual" => "4", "name" => "Ruthless Gladiator's Relic of Conquest" ),
array( "id" => "70405", "qual" => "4", "name" => "Ruthless Gladiator's Relic of Dominance" ),
array( "id" => "70406", "qual" => "4", "name" => "Ruthless Gladiator's Relic of Salvation" ),
array( "id" => "70407", "qual" => "4", "name" => "Ruthless Gladiator's Relic of Triumph" ),
array( "id" => "70399", "qual" => "4", "name" => "Ruthless Gladiator's Badge of Conquest" ),
array( "id" => "70401", "qual" => "4", "name" => "Ruthless Gladiator's Badge of Dominance" ),
array( "id" => "70400", "qual" => "4", "name" => "Ruthless Gladiator's Badge of Victory" ),
array( "id" => "70396", "qual" => "4", "name" => "Ruthless Gladiator's Emblem of Cruelty" ),
array( "id" => "70397", "qual" => "4", "name" => "Ruthless Gladiator's Emblem of Meditation" ),
array( "id" => "70398", "qual" => "4", "name" => "Ruthless Gladiator's Emblem of Tenacity" ),
array( "id" => "70393", "qual" => "4", "name" => "Ruthless Gladiator's Medallion of Cruelty" ),
array( "id" => "70390", "qual" => "4", "name" => "Ruthless Gladiator's Medallion of Cruelty" ),
array( "id" => "70394", "qual" => "4", "name" => "Ruthless Gladiator's Medallion of Meditation" ),
array( "id" => "70391", "qual" => "4", "name" => "Ruthless Gladiator's Medallion of Meditation" ),
array( "id" => "70395", "qual" => "4", "name" => "Ruthless Gladiator's Medallion of Tenacity" ),
array( "id" => "70392", "qual" => "4", "name" => "Ruthless Gladiator's Medallion of Tenacity" ),
array( "id" => "70404", "qual" => "4", "name" => "Ruthless Gladiator's Insignia of Conquest" ),
array( "id" => "70402", "qual" => "4", "name" => "Ruthless Gladiator's Insignia of Dominance" ),
array( "id" => "70403", "qual" => "4", "name" => "Ruthless Gladiator's Insignia of Victory" ), 
);


?>